### ISSUE TITLE
实时硬盘IO，投票

### ISSUE THREAD

**Issue by baosi1234** [cppla/ServerStatus#10]
1 windows客户端可否监控
2 加入对硬盘的io的监控
3 显示服务器的CPU的核数
4 我使用nginx的htpasswd给监控页面作了授权访问页面
5 想问一下作者的微信或者QQ，可否联系一下

**Comment by tenyue** [comment]
@baosi1234 
1、windows可以监控，安装python for windows, 然后安装psutil for windows, 运行 client-psutil.py即可
2、硬盘io有太大必要吗？？
3、CPU使用状态已经是总使用率了，感觉分开意义不大。
4、8575497零,  联系方式会及时编辑掉。

**Comment by baosi1234** [comment]
1 就是硬盘的io速度，像网络速度一样显示
2 只要显示CPU的核数就可以了

**Comment by myqmdx** [comment]
我现在很需要这个功能，可否加上，谢谢!

**Comment by cppla** [comment]
[https://github.com/cppla/ServerStatus/issues/16](url)
