### ISSUE TITLE
丢包测试里电信节点的可用性问题

### ISSUE THREAD

**Issue by MortyFx** [cppla/ServerStatus#104]
ct.tz.cloudcpp.com 节点实际指向的是 www.chinatelecom.com.cn 。而经过测试，这个电信站点在 socket 连接时会选择性拒绝连接，使得程序判定丢包。

![WX20210809-114419.png](https://i.loli.net/2021/08/09/VLJAw6XOG27tz5P.png)

作者可以多测试几次。

**Comment by MortyFx** [comment]
不知道 ct.tz.cloudcpp.com 是不是作者所有，如果是，可以将其指向到 sh.189.cn 上海电信节点，不是的话可以在程序里将其修改为 sh.189.cn

**Comment by cppla** [comment]
@FaithPatrick 已修改，Thanks。   

dns缓存周期较长，生效较慢。
