### ISSUE TITLE
有windows的版本么

### ISSUE THREAD

**Issue by hurui79** [cppla/ServerStatus#107]

**Comment by cppla** [comment]
client-psutil.py is for windows

**Comment by hurui79** [comment]
哦哦，那服务端呢，windows docker 用不太明白。

**Comment by cppla** [comment]
服务端 那就需要自己编译了。。

**Comment by hurui79** [comment]
帮帮忙大佬(๑＞ڡ＜)☆

**Comment by cppla** [comment]
> 帮帮忙大佬(๑＞ڡ＜)☆

没什么意义啊。 即使编译了，然后你还得搞Nginx on windows，或者 IIS on Windows ，还得开放防火墙。。自己玩还是算了。。
商用可以付费帮解决。
