### ISSUE TITLE
Docker 重启或者关闭后启动，月流量全部清零

### ISSUE THREAD

**Issue by AndersonGhost** [cppla/ServerStatus#111]
经过测试，Docker 重启或者关闭后启动，月流量全部清零。

这样的话，每次添加新的节点，之前的节点流量信息将全部清零，这样的话太不人性了啊。

**Comment by cppla** [comment]
这两天修复 @AndersonGhost ，tks

**Comment by cppla** [comment]
已经修复。@AndersonGhost

**Comment by AndersonGhost** [comment]
是在服务端重新下载docker吗？

**Comment by cppla** [comment]
@AndersonGhost 

docker rmi cppla/serverstatus && docker pull cppla/serverstatus

**Comment by AndersonGhost** [comment]
重新安装后，流量变成负数了
![image](https://user-images.githubusercontent.com/33820659/137489370-c3c3cfff-1f79-4046-9265-b60d138c4ffe.png)

**Comment by cppla** [comment]
@AndersonGhost 清空缓存

**Comment by AndersonGhost** [comment]
如何清空啊   有命令吗？

**Comment by cppla** [comment]
> 如何清空啊 有命令吗？

问百度，清空浏览器缓存

**Comment by AndersonGhost** [comment]
确定已清空，还是无用

**Comment by cppla** [comment]
发地址我看看，@AndersonGhost

**Comment by AndersonGhost** [comment]
那两个机器是DD后出现的问题   其他的机器都正常

**Comment by AndersonGhost** [comment]
Docker 重启或者关闭后启动，月流量仍然全部清零啊

**Comment by cppla** [comment]
更新镜像了吗？ @AndersonGhost

**Comment by AndersonGhost** [comment]
更新了啊

**Comment by cppla** [comment]
什么环境呀。或者探针地址 多少 @AndersonGhost

**Comment by AndersonGhost** [comment]
全新的Debian 10啊   将系统DD成了Debian 10，专门用于安装探针的服务器，没有装其他的应用

**Comment by cppla** [comment]
已经修复，试下。@AndersonGhost
```
# 已经测试 docker restart serverstatus
# 已经测试 docker stop serverstatus && docker start serverstatus
```

拉下最新的代码make  或者拉下最新的容器

**Comment by AndersonGhost** [comment]
大佬，您好~ 是我的操作有误吗？ 刚拉了最新代码，并重启docker或者关闭后启动，月流量还是清零了。

操作步骤：
1.拉最新代码： docker rmi cppla/serverstatus && docker pull cppla/serverstatus
2.重启docker：  
A: docker restart serverstatus
B: docker stop serverstatus && docker start serverstatus
如上操作后，月流量仍然清零。

**Comment by cppla** [comment]
docker images 看下你的镜像版本 ？ 怀疑你拉到的镜像有缓存，是不是用国内docker代理了？
```
REPOSITORY           TAG       IMAGE ID       CREATED         SIZE
cppla/serverstatus   latest    f6d922eb3ac1   4 hours ago     135MB
```

**Comment by AndersonGhost** [comment]
root@**:~# docker images 
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
cppla/serverstatus   latest              f6d922eb3ac1        5 hours ago         135MB
<none>               <none>              7334be4adbe6        8 days ago          135MB

这个是不是有问题？

**Comment by AndersonGhost** [comment]
root@***:~# docker images 
 REPOSITORY                   TAG                IMAGE ID              CREATED            SIZE
 cppla/serverstatus          latest              f6d922eb3ac1       5 hours ago        135MB
 <none>                         <none>           7334be4adbe6      8 days ago         135MB

似乎我的有问题。但是，我就是使用 docker rmi cppla/serverstatus该命令来删除镜像的。

**Comment by cppla** [comment]
你发的这是什么鬼? 到底是f6d922eb3ac1 还是 7334be4adbe6

**Comment by AndersonGhost** [comment]
有两个
![image](https://user-images.githubusercontent.com/33820659/137749240-c16c353d-82b3-43fe-873f-b4628c379878.png)

**Comment by AndersonGhost** [comment]
刚才把两个镜像全部删除了，然后下载您的最新镜像，然后重启docker，流量还是清零了。o(╥﹏╥)o

**Comment by cppla** [comment]
经全新环境测试，Debian10  ,Debian11 下 docker方式均正常。 @AndersonGhost

**Comment by cppla** [comment]
创建容器的命令发下

**Comment by AndersonGhost** [comment]
服务器端完整的安装代码：
apt install docker.io -y
docker pull cppla/serverstatus:latest
wget https://raw.githubusercontent.com/cppla/ServerStatus/master/autodeploy/config.json
docker run -d --restart=always --name=serverstatus -v ~/serverstatus/config.json:/ServerStatus/server/config.json -p 80:80 -p 35601:35601 cppla/serverstatus:latest

**Comment by cppla** [comment]
> 服务器端完整的安装代码： apt install docker.io -y docker pull cppla/serverstatus:latest wget https://raw.githubusercontent.com/cppla/ServerStatus/master/autodeploy/config.json docker run -d --restart=always --name=serverstatus -v ~/serverstatus/config.json:/ServerStatus/server/config.json -p 80:80 -p 35601:35601 cppla/serverstatus:latest

已测试，无误。 @AndersonGhost

**Comment by AndersonGhost** [comment]
好奇怪啊 只要我docker restart serverstatus 流量就清零了  也下载最新的镜像了

我的系统是 Debian 10   内核已经升级到最新 5.10.0-0.bpo.8-amd64 #1 SMP Debian 5.10.46-4~bpo10+1

谢谢大佬，那我DD下系统然后再测试下。

**Comment by AndersonGhost** [comment]
重新DD 系统后，发现重启docker或者关闭后启动，月流量正常显示了！

辛苦作者了~~Thanks♪(･ω･)ﾉ  ٩(๑❛ᴗ❛๑)۶

**Comment by AndersonGhost** [comment]
将内核升级到最新 5.10 ，重启docker或者关闭后启动，月流量仍然正常。

**Comment by cppla** [comment]
> 将内核升级到最新 5.10 ，重启docker或者关闭后启动，月流量仍然正常。

估计先前是系统的原因，没DD好。😂

**Comment by AndersonGhost** [comment]
> > 将内核升级到最新 5.10 ，重启docker或者关闭后启动，月流量仍然正常。
> 
> 估计先前是系统的原因，没DD好。joy

应该是的   感谢作者！！
