### ISSUE TITLE
如何优雅地添加客户端

### ISSUE THREAD

**Issue by luckiestone** [cppla/ServerStatus#112]
环境为手动配置linux，非docker。
新增一个客户端之后，我这边实际情况是需要重启服务端让配置生效，重启服务端之后无法连接其他客户端，所有客户端也要重启一遍，这样月流量全部清零了，本人比较小白，不知道有没有比较优雅的添加客户端的方法。

**Comment by cppla** [comment]
1、月流量清零的问题，昨天晚上已经修复，尝试下新版本。
2、重启服务端后，无需重启客户端，客户端会反复重试连接。
3、统一密码，USER递增例如： nohup python3 client-linux.py SERVER=你的地址 USER=s01 &

@luckiestone

**Comment by luckiestone** [comment]
> 1、月流量清零的问题，昨天晚上已经修复，尝试下新版本。 2、重启服务端后，无需重启客户端，客户端会反复重试连接。 3、统一密码，USER递增例如： nohup python3 client-linux.py SERVER=你的地址 USER=s01 &
> 
> @luckiestone

非常感谢！马上去试试。BTW,clone了新版本之后还要重新make一下的吧

**Comment by cppla** [comment]
是的 @luckiestone

**Comment by luckiestone** [comment]
> 是的 @luckiestone

好的，谢谢。我刚尝试了下，按照之前issue中一个提到的添加service的方法，systemctl好像无法stop进程，无法make，应该怎么完全杀掉进程释放端口呀
%%%%%%%%%%%%%%%
已经搞定，之前月流量清零，现在月流量为总流量，不知道是不是bug。

**Comment by cppla** [comment]
清楚浏览器缓存就正常了。。。@luckiestone

**Comment by luckiestone** [comment]
> 清楚浏览器缓存就正常了。。。@luckiestone

是的，谢谢！

**Comment by luckiestone** [comment]
刚发现systemctl重启服务端后，月流量仍然清零。

**Comment by cppla** [comment]
> 刚发现systemctl重启服务端后，月流量仍然清零。

经测试，没发现该bug ，确认编译最新的服务端，手动kill -15 进程，然后启动试试，一切正常。

**Comment by luckiestone** [comment]
> > 刚发现systemctl重启服务端后，月流量仍然清零。
> 
> 经测试，没发现该bug ，确认编译最新的服务端，手动kill -15 进程，然后启动试试，一切正常。

我是删除文件夹后重新clone，然后make的服务端，客户端也clone了最新的。
```
kill -15 `ps -ef | grep sergate | grep -v "grep" | awk '{print $2}'` 
```
仍然会清零数据。
系统为Centos 7

**Comment by luckiestone** [comment]
经测试，使用重新加载的方式月流量正常
```
kill -s HUP `ps -ef | grep sergate | grep -v "grep" | awk '{print $2}'`
```

**Comment by cppla** [comment]
@luckiestone ok，下周我看下

**Comment by cppla** [comment]
已经修复，试下。@luckiestone 
```
# 已经测试kill -15
# 已经测试kill -9
# 已经测试kill -s HUP
```

最新版本应该已经支持systemctl管理了。拉下最新的代码make 或 拉下最新的容器

**Comment by luckiestone** [comment]
> 已经修复，试下。@luckiestone
> 
> ```
> # 已经测试kill -15
> # 已经测试kill -9
> # 已经测试kill -s HUP
> ```
> 
> 最新版本应该已经支持systemctl管理了。拉下最新的代码make 或 拉下最新的容器

经测试，kill -15, kill -9, kill -s HUP以及systemctl restart和reload均正常工作。非常感谢！
