### ISSUE TITLE
更新 服务端 docker 容器后 一直显示m370

### ISSUE THREAD

**Issue by sitsh** [cppla/ServerStatus#113]
> #60
> #74
> 
> @xingzhuanxing
> 
> 你修改三网探测了吧。

没有改过。 服务端用你的docker， 
该如何修改三网探测？

月度流量 这一列 显示的m370

_Originally posted by @xingzhuanxing in https://github.com/cppla/ServerStatus/issues/78#issuecomment-657373232_

**Comment by sitsh** [comment]
客户端脚本 也更新过。

**Comment by cppla** [comment]
清空浏览器缓存 @sitsh

**Comment by sitsh** [comment]
> 清空浏览器缓存 @sitsh 

可以了用其他 游览器打开显示正常了，之前删除过chrome cookie 没起作用 

最后chrome 进入到f12 application storage clear 才显示正常了

**Comment by escapezn** [comment]
从旧版本更新上来，出现同样的问题。建议在readme中标注一下
