### ISSUE TITLE
重启docker  发现月流量变成负数

### ISSUE THREAD

**Issue by AndersonGhost** [cppla/ServerStatus#114]
如题所述，服务器重启docker，有些月流量变成负数，如下所示，不知何故。
操作：docker restart serverstatus
![image](https://user-images.githubusercontent.com/33820659/138193488-e141f0e1-4e70-4a13-a88c-7dc90ee69a4e.png)

**Comment by cppla** [comment]
清空浏览器缓存 @AndersonGhost

**Comment by AndersonGhost** [comment]
已经清除了啊  使用多个浏览器登陆   还是有负流量的啊

**Comment by cppla** [comment]
前一个ticket 让你发地址你也不发，问题发生的环境你也不说，只是说问题。。我测试了各个发行版还是测试不出来问题。。你这么一直发，我追着你问一堆情况然后我在去做复现， 有点尴尬。

要是老外，早跑路了。

```
# 问题描述
# 问题环境
# 复现条件
```

**Comment by AndersonGhost** [comment]
不好意思啊   大佬  o(╥﹏╥)o
地址刚才给您了

**Comment by AndersonGhost** [comment]
还是之前DD后正常显示的系统：Debian 10

**Comment by cppla** [comment]
ok，我测试一下 @AndersonGhost

**Comment by cppla** [comment]
你是用的这个版本吗？ @AndersonGhost 
```
REPOSITORY           TAG       IMAGE ID       CREATED      SIZE
cppla/serverstatus   latest    f6d922eb3ac1   2 days ago   135MB
```

**Comment by AndersonGhost** [comment]
好像是的
![image](https://user-images.githubusercontent.com/33820659/138234650-81e7e53b-9e9a-42a6-971d-3471b648bffb.png)

**Comment by cppla** [comment]
我不太清楚，我为什么复现不了，已经测试的宿主机环境 ，反复重启均未发现异常。
```
debian 9 
debian 10
debian 11 
```
或者你可以删掉重新启动一下serverstatus 看看会不会复现？？

**Comment by AndersonGhost** [comment]
把镜像删除，然后重新下载，并重启物理机器。流量似乎又恢复正常了，全部清零了。

**Comment by AndersonGhost** [comment]
先把这个关闭吧，等我找到了复现条件然后在开启

**Comment by ligongfu** [comment]
我遇到的情况是节点重启后运行最新client-linux.py后，该节点显示月流量是负的

**Comment by cppla** [comment]
清空浏览器缓存，js未更新 @ligongfu

**Comment by ligongfu** [comment]
尝试了下面操作都不行：
1、换电脑、换浏览器、用IP直接访问（排除CDN缓存）
2、docker restart serverstatus
3、client-linux.py换回之前版本

排查：
1、问题节点的服务器时间和时区没问题
2、其它机器运行最新client-linux.py后没发生该问题

问题节点的系统:CentOS 7.9.2009 x86_64(Py3.7.9)，协议是双栈

**Comment by cppla** [comment]
我一会儿找机器测试下这个bug，怀疑是旧的docker镜像导致的。

你先删除服务端镜像，然后重新拉一下运行，试试是否正常? @ligongfu

**Comment by ligongfu** [comment]
月流量清0了，也算解决问题了:）
@cppla

**Comment by AndersonGhost** [comment]
有一条复现路径：重启服务器机器（reboot），流量就变成负数了。

**Comment by ligongfu** [comment]
要怎么备份流量数据？
我另一个监控面板重启容器后月流量也变负数了 @cppla

**Comment by se7enmuting** [comment]
我今天也发现有变负数的情况，今天流程大致是这样的：
server 机 DD 重装 debian 10，再装 docker（以前的docker data），server 的 client-linux.py 用 supervisor 托管，server 的流量正常是正数。没有reboot。
然后 client 02 (debian 9)，kill 掉 client-linux.py，再换用 supervisor 托管 .py，然后再 reboot ，client 02 的流量现在就变成负数了，不清楚是哪个阶段变负的，最后都搞完才发现变负的。
然后再测试另一台 client 03 (centos8.4)，操作流程和 client 02 一样，发现 reboot 前流量是正常的，reboot 之后流量就变负数了。
最后我在写这个回复的时候 reboot 了一下 server ，发现它的流量也变成 -0.00G|-0.00G，过个几分钟，负号就没了。

**Comment by cppla** [comment]
已经修复 @AndersonGhost @ligongfu @Se7enMuting

**Comment by cppla** [comment]
已经修复 @AndersonGhost @ligongfu @Se7enMuting

**Comment by cppla** [comment]
不过服务端最好不要重启吧，因为重启就没办法统计到总流量了，vnstat借用了SQLite所以才能统计到历史数据，然而对于一个探针来说，写数据库SQLite实在太重了。


服务器一般在线：
```
15:18:24 up 911 days
15:19:30 up 949 days,
......
```
