### ISSUE TITLE
建议显示机器离线前的最后显示数据

### ISSUE THREAD

**Issue by ligongfu** [cppla/ServerStatus#115]
既然新版写了SQLite，是否考虑将机器数据定时保存，好在离线后在面板查看机器离线前最后的状态？

**Comment by cppla** [comment]
一、没写SQLite ，  只是借鉴了vnstat的统计方法。

二、离线前肯定要把最后的状态保存的，保存为了“stats.json~”非"stats.json"， 只不过离线后现在没有展示。 

三、展示的话就成静态页面了，不会刷新也不会跳动，只有下边更新时间可以看到是否更新。

**Comment by ligongfu** [comment]
就是说展示的话，在线节点数据也成静态页面了是吧？
能不能让离线的展示出来，同时不影响在线的实时数据

**Comment by cppla** [comment]
不是，只是离线成静态的了，在线的依旧实时展示。。

这么整的话，会造成不知道哪一台下线了 @ligongfu

**Comment by ligongfu** [comment]
加一列专门显示在线状态呢？就之前MH370那样

**Comment by cppla** [comment]
这个属于定制需求了 @ligongfu
