### ISSUE TITLE
config.json里演示数据，最后节点monthstart的值是5，代表啥意思

### ISSUE THREAD

**Issue by ligongfu** [cppla/ServerStatus#116]
请问config.json里演示数据，最后节点monthstart的值是5，代表啥意思

**Comment by usufu** [comment]
同问，是开始月份，还是月的开始日期？

**Comment by cppla** [comment]
每个月的 流量开始计算 开始日期   @ligongfu @usufu

**Comment by cppla** [comment]
一般VPS都是从每个月1号开始计算，  一些小厂商的VPS是按照账单日计算的。

**Comment by usufu** [comment]
> 一般VPS都是从每个月1号开始计算， 一些小厂商的VPS是按照账单日计算的。

知道了，多谢，另外还有个问题，这个页面为啥在手机浏览器里面看不到3网的丢包率那几列？PC端是可以的。

**Comment by cppla** [comment]
手机浏览器宽度不够，如果都显示的话

一、压缩字体，非常小～。
二、展示较少的列。

目前根据宽度动态调整的，宽度足够就能显示出来。 通过控制css 可以自己更改 @usufu

**Comment by usufu** [comment]
ok,xiexie

**Comment by NetFly-VPN** [comment]
> 手机浏览器宽度不够，如果都显示的话
> 
> 一、压缩字体，非常小～。 二、展示较少的列。
> 
> 目前根据宽度动态调整的，宽度足够就能显示出来。 通过控制css 可以自己更改 @usufu

新版的每月流量很赞, 这种算法是什么样的呀, 每台vps单独计算,还是在服务器计算?

另外, 新版的样式能不能调整一下呢, 在黑色模式下现在看的特别难受, 最右边的小地球, 能不能换回原来的.

还有每月流量的颜色统一为绿色的呗,

**Comment by cppla** [comment]
在服务端计算  @NetFly-VPN  。
