### ISSUE TITLE
archlinux上应该怎么运行客户端？

### ISSUE THREAD

**Issue by SCGabriel** [cppla/ServerStatus#12]
有软件需求必须用archlinux

现在运行客户端就报错

[root@archlinux alice]# /usr/bin/python "/usr/local/ServerStatus/client-linux.py"
Connecting...
Caught Exception: argument should be integer or bytes-like object, not 'str'
Connecting...
Caught Exception: argument should be integer or bytes-like object, not 'str'
Connecting...
Caught Exception: argument should be integer or bytes-like object, not 'str'
Connecting...
Caught Exception: argument should be integer or bytes-like object, not 'str'
Connecting...
Caught Exception: argument should be integer or bytes-like object, not 'str'
Connecting...
Caught Exception: argument should be integer or bytes-like object, not 'str'
^CTraceback (most recent call last):
  File "/usr/local/ServerStatus/client-linux.py", line 243, in <module>
    if data.find("Authentication required") > -1:
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/ServerStatus/client-linux.py", line 317, in <module>
    time.sleep(3)
KeyboardInterrupt

求助下大佬是什么原因？

**Comment by cppla** [comment]
@SCGabriel 大佬应该没仔细看说明，兼容问题请下载psutil通用版本！
已帮测试：
pacman -Sy gcc    
pip2 install psutil    
python2 client-psutil.py
示例：
[https://s1.ax1x.com/2018/09/11/ik90at.png](url)

**Comment by SCGabriel** [comment]
前阵子archlinux把python更新到了3.7去了，咱并不知道，昨天晚上用py2就解决了，谢谢大佬了
