### ISSUE TITLE
新版没有以前好看....

### ISSUE THREAD

**Issue by NetFly-VPN** [cppla/ServerStatus#120]

**Comment by NetFly-VPN** [comment]
![image](https://user-images.githubusercontent.com/34091329/142900319-232b76ff-5448-40bd-878d-c8085ee90359.png)
黑色主题下, 看的五颜六色的, 能不能换回原来的样式呢

**Comment by cppla** [comment]
release 1.0.1 老版 dark style css，替换现有版本 css即可。

**Comment by NetFly-VPN** [comment]
> 

我现在用的是docker 运行的, 如果要自行替换的话, 是不是得用源码编译才行呀

**Comment by cppla** [comment]
> > 
> 
> 我现在用的是docker 运行的, 如果要自行替换的话, 是不是得用源码编译才行呀

无需编译，docker cp  拷贝css替换容器内的css即可。

**Comment by NetFly-VPN** [comment]
> > > 
> > 
> > 
> > 我现在用的是docker 运行的, 如果要自行替换的话, 是不是得用源码编译才行呀
> 
> 无需编译，docker cp 拷贝css替换容器内的css即可。

按照你说的方式做了, 没有效果

**Comment by fanmli** [comment]
支持老版本好看。

**Comment by cppla** [comment]
> 

清空浏览器缓存

**Comment by NetFly-VPN** [comment]
没用

**Comment by cppla** [comment]
好了 @NetFly-VPN @fanmli
