### ISSUE TITLE
web错位的问题

### ISSUE THREAD

**Issue by cxxycc** [cppla/ServerStatus#121]
最新的源码好像解决了一直存在的web错位问题，
但我不需要月流量统计，也不想加个SQLite，所以不想升级啊
请问作者旧版的怎么解决错位问题呢，需要替换掉那些文件？

再次感谢作者！

**Comment by Se7enMuting** [comment]
借这个issue我也贴个图
我是ping丢包测试 移动 那个位置一直会有不显示的情况发生
![image](https://user-images.githubusercontent.com/889925/143720538-cd194218-c0e4-4f5e-85c6-3a785985f5f7.png)
回复前刚刚更新的docker镜像还是这样

**Comment by cppla** [comment]
用新版本的css替换掉老版本的css就行了。。
