### ISSUE TITLE
建议merge

### ISSUE THREAD

**Issue by joyoner** [cppla/ServerStatus#122]
https://github.com/lidalao/ServerStatus

**Comment by joyoner** [comment]
更方便的节点管理, 支持增删改查
上下线通知（telegram）
Agent机器安装脚本改为systemd， 支持开机自启

**Comment by cppla** [comment]
没收到push啊，大佬。 一会儿我测试一下

**Comment by joyoner** [comment]
> 

只是看到了，推荐一下。

**Comment by Duan-rax** [comment]
看了一下 可以作为插件使用

**Comment by cppla** [comment]
目前已经整合了telegram bot 和 dockerfile  @joyoner @Duan-rax
