### ISSUE TITLE
Safari 浏览器最后一列显示不完

### ISSUE THREAD

**Issue by yanhao98** [cppla/ServerStatus#126]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37316281/146916814-3d7af2cd-7df7-4fd2-9fca-1edcb5e7c753.png">

**Comment by cppla** [comment]
你这个是pad pro？ 13 寸mac显示如下:
<img width="1429" alt="截屏2021-12-21 下午6 53 10" src="https://user-images.githubusercontent.com/10623809/146918514-7b73f15f-2154-4fd3-a219-c21e73891635.png">

**Comment by yanhao98** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/37316281/146918353-3a559d89-b8f6-4dd2-be75-39d534bfa1ec.png">

**Comment by yanhao98** [comment]
在其他浏览器是正常的。不影响我使用。就觉得很奇葩。
刚看了iPad Pro也是那样。

**Comment by cppla** [comment]
哦哦，css原因吧，这段代码很老了， 兼容性写的不好。

你第四台机器 虚拟化名字写的太长了太长了，然后就挤破了， 可以减少点 @yanhao98

**Comment by yanhao98** [comment]
> 哦哦，css原因吧，这段代码很老了， 兼容性写的不好
> 
> 你第四台机器 虚拟化写的太长了太长了，然后就挤破了 @yanhao98

好像是的。主要其他浏览器正常我以为不是那个原因。感谢
