### ISSUE TITLE
探针总量

### ISSUE THREAD

**Issue by radowitz** [cppla/ServerStatus#127]
目前测下来探针总量好像是128个，能否放开这个限制？

**Comment by chobitsos** [comment]
卧槽你这么多机器吗？搞肉鸡的么？

**Comment by AndersonGhost** [comment]
经过测试，docker版本的也是这个限制，期待开放这个限制~

**Comment by cppla** [comment]
小鸡太多，这个探针有点鸡肋了吧？ @AndersonGhost @radowitz

**Comment by AndersonGhost** [comment]
还是您的探针好用呀

**Comment by AndersonGhost** [comment]
> 小鸡太多，这个探针有点鸡肋了吧？ @AndersonGhost @radowitz

还是您的探针好用呀

**Comment by cppla** [comment]
不知道大佬测试没有，小鸡多的情况下，展示是否方便？ 网页刷新是否缓慢？@AndersonGhost

**Comment by AndersonGhost** [comment]
够自己监控小鸡就行了，说实话还是挺方便的。后面还会陆续增加小鸡，受128个的限制，后面的小鸡就看不见了。

网页刷新都很正常，很流畅。

**Comment by AndersonGhost** [comment]
> 不知道大佬测试没有，小鸡多的情况下，展示是否方便？ 网页刷新是否缓慢？@AndersonGhost

够自己监控小鸡就行了，说实话还是挺方便的。后面还会陆续增加小鸡，受128个的限制，后面的小鸡就看不见了。

网页刷新都很正常，很流畅。

**Comment by AndersonGhost** [comment]
> 不知道大佬测试没有，小鸡多的情况下，展示是否方便？ 网页刷新是否缓慢？@AndersonGhost

感觉比哪吒探针好用多了！  简约，不简单~  哪吒探针太花里胡哨了，一点都不好用

**Comment by cppla** [comment]
改为了256 ，如果还不够，去这里修改就行了ServerStatus/server/src/network.h第13行处，定义了最大客户端数量NET_MAX_CLIENTS  @AndersonGhost @radowitz

**Comment by AndersonGhost** [comment]
谢谢大佬~   docker版本服务器需要重新安装吗？

**Comment by AndersonGhost** [comment]
> 改为了256 ，如果还不够，去这里修改就行了ServerStatus/server/src/network.h第13行处，定义了最大客户端数量NET_MAX_CLIENTS @AndersonGhost @radowitz

谢谢大佬~ docker版本服务器需要重新安装吗？

**Comment by cppla** [comment]
重新拉一下然后运行。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："AndersonGhost ***@***.***&gt;;
发送时间：2022年1月7日(星期五) 晚上8:05
收件人："cppla/ServerStatus" ***@***.***&gt;;
抄送："cppla ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [cppla/ServerStatus] 探针总量 (Issue #127)
-----------------------------------

 

 
谢谢大佬~   docker版本服务器需要重新安装吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
