### ISSUE TITLE
月流量超过100GB时，显示异常

### ISSUE THREAD

**Issue by AndersonGhost** [cppla/ServerStatus#128]
如题所述，当月流量超过100GB时，显示异常。注：浏览器已经最大化，安装最新的docker版本。
![image](https://user-images.githubusercontent.com/33820659/148625469-a4bec4d4-986a-4af6-85da-34e5c3e0dbd0.png)
![image](https://user-images.githubusercontent.com/33820659/148625502-0e6f3f1f-7721-4734-b91e-9983fa6d7324.png)

**Comment by chobitsos** [comment]
<img width="104" alt="屏幕截图 2022-01-08 161104" src="https://user-images.githubusercontent.com/18194327/148637089-8d30bf4e-8abe-4592-88db-faa1c8ab9ed2.png">
没这种情况，清一下缓存看看，我的把显示IPV4的DIV改成显示流量了哈哈

**Comment by AndersonGhost** [comment]
可能是我浏览器的问题。浏览器版本：Chrome 86   可能是太老了吧
