### ISSUE TITLE
建议:服务端提供http上报接口

### ISSUE THREAD

**Issue by zdz** [cppla/ServerStatus#129]
原因：在 vercel, heroku, okteto 等免费容器服务部署ServerStatus server时会有所限制，无法同时expose 80，35601端口，导致client 数据无法上报。
server 提供 http api 上报后，client使用http上报，可将 server 部署在上述服务商中
eg:
```
[POST] /api/report
{
	// payload
}
```

**Comment by zdz** [comment]
撸了一个rust版轮子，欢迎使用 [ServerStatus-Rust](https://github.com/zdz/ServerStatus-Rust)

**Comment by cppla** [comment]
good idea
