### ISSUE TITLE
部署docker带tg通知版报错麻烦看一下！

### ISSUE THREAD

**Issue by fanmli** [cppla/ServerStatus#130]
已经安装好docker和docker-compose，在使用docker-compose -f docker-compose-telegram.yml up `-d安装到最后报错，docker-compose-telegram.yml这个文件也在机子里下载修改号了，
报错图如下：
![20220122092306](https://user-images.githubusercontent.com/13824498/150619653-cf9e077d-5ec0-4672-8a4c-ef01ed77f9f8.png)

配置如下：
version: "3"
services:
  serverstatus:
    image: cppla/serverstatus:latest
    container_name: serverstatus
    restart: unless-stopped
    volumes:
      - ./server/config.json:/ServerStatus/server/config.json 
      - ./web/json:/usr/share/nginx/html/json
    ports:
      - 35601:35601
      - 8080:80
  bot:
    build:
      context: ./plugin
      dockerfile: Dockerfile-telegram
    container_name: bot4sss
    restart: unless-stopped
    environment:
      - TG_CHAT_ID=xxxxxx
      - TG_BOT_TOKEN=xxxxxxxxxxx`

**Comment by cppla** [comment]
经测试没问题，看报错你这个是找不到ServerStatus/plugin/Dockerfile-telegram文件，看下文件是否存在。 @fanmli 

git clone 后，cd ServerStatus，build 即可


`cd ServerStatus/     

  vim docker-compose-telegram.yml       

  docker-compose -f docker-compose-telegram.yml up -d `

**Comment by fanmli** [comment]
> git clone 后ServerStatus文件夹没有创建，./plugin文件夹也没有任何文件。

**Comment by cppla** [comment]
> 

那你根本没有clone 成功吧！
git clone https://github.com/cppla/ServerStatus && ls ServerStatus

**Comment by fanmli** [comment]
> > 
> 
> 那你根本没有clone 成功吧！ git clone https://github.com/cppla/ServerStatus && ls ServerStatus
telegram通知在arm机子上不起作用，在AMD或者Intel机子就没问题。

**Comment by cppla** [comment]
@fanmli 

已修复。

**Comment by cppla** [comment]
还是有问题吗？@fanmli
