### ISSUE TITLE
通过crontab跟随系统启动方式不能用了吗

### ISSUE THREAD

**Issue by ligongfu** [cppla/ServerStatus#136]
在crontab添加下面代码不能用了吗？有什么办法可以跟随系统启动
`@reboot root /root/client-linux.py SERVER=$server USER=$user`

**Comment by cppla** [comment]
上述方式只适用于Debian，Centos自行Google。 

如果懒得折腾，可以用systemctl管理。
service的文件：https://github.com/cppla/ServerStatus/tree/master/service
```
systemctl enable status-client
```
或者用这个
```
bash status.sh
```
