### ISSUE TITLE
网页如何分割多个table？

### ISSUE THREAD

**Issue by wajika** [cppla/ServerStatus#137]
我用来监控公司内部主机，想把 table 按类型或是位置分类，不放在一个表里面，应该怎么修改？ 另外我不需要 ipv4 和移动联通电信那个字段，直接在 index.html 中去掉这两个字段 就可以了吗？
![image](https://user-images.githubusercontent.com/17058349/155934247-85791e45-b370-4d5c-a2d6-d8eaf71fef8e.png)

**Comment by cppla** [comment]
一、可以按节点名或者类型控制，更改js分别插入不同的Table1 和 Table2即可。
```
if 类型 == vmware {
 insert Table1
} else if 类型 == kvm{
 insert Table2
}
```
二、对，直接修改html即可，

**Comment by wajika** [comment]
> 一、可以按节点名或者类型控制，更改js分别插入不同的Table1 和 Table2即可。
> 
> ```
> if 类型 == vmware {
>  insert Table1
> } else if 类型 == kvm{
>  insert Table2
> }
> ```
> 
> 二、对，直接修改html即可，

好的，我试试。
顺便再提个需求，config.json 可以支持热加载吗？ 就是几秒或是几分自动重新加载，每次修改config.json 就要重启 sergate，太麻烦了。

**Comment by cppla** [comment]
> 

实际生产中增删服务器时间间隔较久，config.json文件一般不会经常性更新。

建议用docker 部署，或者注册服务【ServerStatus/service/status-server.service】
```
docker restart serverstatus
systemctl restart status-server
```

**Comment by wajika** [comment]
> > 
> 
> 实际生产中增删服务器时间间隔较久，config.json文件一般不会经常性更新。
> 
> 建议用docker 部署，或者注册服务【ServerStatus/service/status-server.service】
> 
> ```
> docker restart serverstatus
> systemctl restart status-server
> ```

好的，谢谢
