### ISSUE TITLE
超过一定监控数量，后续的节点报账号密码错误

### ISSUE THREAD

**Issue by realmeneogt** [cppla/ServerStatus#138]
是这样，要监控的节点有点多，估计有上百个，服务端运行启动正常，但是后面几个客户端连上后直接报 username/password 错误，删除掉几个又可以正常连上了。

**Comment by cppla** [comment]
机器数量超过256了吗？之前的版本限制是128个。 @realmeneogt

**Comment by realmeneogt** [comment]
是呀，可以自己调整限制吗？怎么调呀 @cppla

**Comment by cppla** [comment]
去这里修改就行了ServerStatus/server/src/network.h第13行处，定义了最大客户端数量NET_MAX_CLIENTS

我很好奇256个客户端，web页面刷新的时候不卡吗？？？@realmeneogt
