### ISSUE TITLE
初次安装启动服务的时候出现Segmentation fault

### ISSUE THREAD

**Issue by SCGabriel** [cppla/ServerStatus#14]
不明白这个错误是什么意思，也不知道怎么解决orz
![segmentation fault](https://user-images.githubusercontent.com/36832672/37238799-0434b996-2469-11e8-8480-facdee495287.png)

**Comment by SCGabriel** [comment]
好吧，发现错误了。启动服务前，千万千万要注意，不要写错配置文件orz

**Comment by cppla** [comment]
后期会简化部署： 服务端和客户端整合，无需复杂部署， @SCGabriel
