### ISSUE TITLE
不支持dock的主机可以安装吗

### ISSUE THREAD

**Issue by webfury** [cppla/ServerStatus#14]
谢谢..

**Comment by webfury** [comment]
> docker只是为了方便部署,不装docker也没影响

python client-linux.py
Connecting...
Disconnected...
Connecting...
Disconnected...
Connecting...
Disconnected...
Connecting...
Disconnected...
是怎么回事？页面"如果出现此消息，请确保您已启用Javascript! 
否则云监控主服务没启动或已关闭."
不知道是客户端还是服务器端的问题，客户端和服务器端可以在一起吗，一个主机上同时运行吗

**Comment by cppla** [comment]
@webfury  可以在一起 。检查你的ip和端口  是否正确

**Comment by siriusfinex** [comment]
@webfury 
client-linux.py这个文件里面的SERVER=服务器端公网IP地址，
不要填成服务器端的内网地址或者客户端的IP地址。
