### ISSUE TITLE
菜鸟不会用

### ISSUE THREAD

**Issue by huaAhua** [cppla/ServerStatus#140]
`ServerStatus`: docker-compose up -d    

`ServerStatus with tgbot`: TG_CHAT_ID=你的电报ID TG_BOT_TOKEN=你的电报密钥 docker-compose -f docker-compose-telegram.yml up -d 

Google搜不到什么意思，想添加电报也没成功

 可不可以把电报也做成  config.json 里面 搞个配置文件。

**Comment by cppla** [comment]
```
TG_CHAT_ID=yourid TG_BOT_TOKEN=yourtoken docker-compose -f docker-compose-telegram.yml up -d
```
