### ISSUE TITLE
这个显示准吗

### ISSUE THREAD

**Issue by huaAhua** [cppla/ServerStatus#141]
![image](https://user-images.githubusercontent.com/37369520/156383726-1f343f24-9d2b-4cd3-bdbf-a3f387a0489f.png)
看着差距很大啊

**Comment by cppla** [comment]
web刷新有1-2s的定时器。

**Comment by huaAhua** [comment]
一个持续500mbps  一个 132 mbps   500 是持续不是突发

**Comment by cppla** [comment]
> 

自己看什么原因，包括网卡 nload
