### ISSUE TITLE
提议：可否增加磁盘 IO 监控？

### ISSUE THREAD

**Issue by wajika** [cppla/ServerStatus#143]
感觉影响主机的因素 IO 也占了很大一块

**Comment by cppla** [comment]
好主意！

**Comment by cppla** [comment]
这个磁盘IO指标WEB页面显示再哪里好呢？ 有没有好的建议 ？@wajika

**Comment by wajika** [comment]
> 这个磁盘IO指标WEB页面显示再哪里好呢？ 有没有好的建议 ？@wajika

加一列不可行吗？

**Comment by cppla** [comment]
> > 这个磁盘IO指标WEB页面显示再哪里好呢？ 有没有好的建议 ？@wajika
> 
> 加一列不可行吗？

估计会非常拥挤，先试试吧。

**Comment by cppla** [comment]
SSD和HDD、包括RAID卡，ZFS。 因为iops原因，实际值差异较大。 暂未发现有效监控磁盘性能的方案。😅

想了几天也只能读出总体读取/写入磁盘的字节数，貌似没什么用。。。。

希望有大佬能指点迷津

**Comment by wajika** [comment]
不一定要搞出一个统一标准，加个判断 能读到就显示？ 不知道楼下有没有大佬有更好的思路

**Comment by cppla** [comment]
好像没什么用？？？？只能显示成： 读 ｜ 写
```
20.2 KB | 112.1 MB
10.21 MB | 10.1 B
10.21 B | 10.1 MB
```

**Comment by wajika** [comment]
> 好像没什么用？？？？只能显示成： 读 ｜ 写
> 
> ```
> 20.2 KB | 112.1 MB
> 10.21 MB | 10.1 B
> 10.21 B | 10.1 MB
> ```

可以

**Comment by cppla** [comment]
已经增加，可以先行测试 @wajika   样式： tz.cloudcpp.com

**Comment by wajika** [comment]
> tz.cloudcpp.com

好的，谢谢
