### ISSUE TITLE
月流量统计不准

### ISSUE THREAD

**Issue by sqzxcv** [cppla/ServerStatus#144]
经常遇到 节点服务器重启后, 月流量就重置为0了. 这个是什么原因呢. 这个月流量记录位置在什么地方, 是否可以存redis, 或者别的什么地方

**Comment by joyoner** [comment]
有一样的问题，重启docker部分节点流量清零。

**Comment by cppla** [comment]
> 

新增和删除节点导致的 。 或者重命名节点名 @joyoner

很快会修复这个问题 。

**Comment by sqzxcv** [comment]
> 新增和删除节点导致的 。 或者重命名节点名 @joyoner
> 
> 很快会修复这个问题 。

是否可以绑定ip

**Comment by cppla** [comment]
> > 新增和删除节点导致的 。 或者重命名节点名 @joyoner
> > 很快会修复这个问题 。
> 
> 是否可以绑定ip 

可以是可以。 
现在遇到了一个DD的情况，DD之前装了探针客户端，DD之后重新安装 。。。没办法判断是否DD，流量还是会lost 或者 error。

**Comment by sqzxcv** [comment]
> > > 新增和删除节点导致的 。 或者重命名节点名 @joyoner
> > > 很快会修复这个问题 。
> > 
> > 
> > 是否可以绑定ip
> 
> 可以是可以。 现在遇到了一个DD的情况，DD之前装了探针客户端，DD之后重新安装 。。。没办法判断是否DD，流量还是会lost 或者 error。

现在这个问题, 有没有解决方案呢?

**Comment by cppla** [comment]
> 

无，没想清楚。

**Comment by sqzxcv** [comment]
> 无，没想清楚。

有没有这种可能, 比如用户在使用的时候, 为每个服务器指定一个唯一的key, 我现在就是每个服务网的用户名密码都是固定不一样的. 用这种作为key 保存数据. 无论服务器是否dd, 应该都不会受影响吧

**Comment by cppla** [comment]
已修复新增删除节点月流量无法精准匹配的问题 @sqzxcv
