### ISSUE TITLE
Docker 版本下背景如何更换成黑色？

### ISSUE THREAD

**Issue by AndersonGhost** [cppla/ServerStatus#145]
大佬您好！

如题所述，Docker 版本下背景如何更换成黑色？感谢~

**Comment by cppla** [comment]
最近版本默认跟随系统，白天显示浅色，晚上显示深色。

直至访客手动选择浅色或者深色，打断跟随，只显示手动选择的配色【cookie】。

**Comment by AndersonGhost** [comment]
深色不够深啊，想显示纯黑色 ，就如您最开始的那个颜色。

**Comment by cppla** [comment]
有人说之前的黑色不好看就给换了😂， 可以找找之前的release 版本，把css替换到新版本的css。 或者自己自定义个自己的css比较好

**Comment by AndersonGhost** [comment]
还是更深点好看些 :smiley:
