### ISSUE TITLE
数据无法动态显示

### ISSUE THREAD

**Issue by pkuplus** [cppla/ServerStatus#15]
按教程成功部署好了，但我发现您给出的 DEMO 上服务器的数据是动态展示的，而我自己部署的却是静态的，要手动刷新页面后，`网络`等数据才变化。
<img width="99" alt="screen shot 2018-03-13 at 10 53 44" src="https://user-images.githubusercontent.com/26180112/37320117-2b694ab8-26ad-11e8-9744-5bfe0c7de930.png">

**Comment by cppla** [comment]
查看nginx是否做了缓存~ @pkuplus

**Comment by pkuplus** [comment]
@cppla 

查看了 PHP 确实启用了 Zend Opcache，关闭后可以了。就是刷新频率比较慢，您的刷新间格设置是多久？

**Comment by cppla** [comment]
默认是1秒，可以自己调。 @pkuplus ，查看演示：https://tz.cloudcpp.com

**Comment by pkuplus** [comment]
@cppla  我默认也是1秒，但差不多几十秒才自动刷新一次，而您的演示站刷新频率几乎是时时的。

**Comment by cppla** [comment]
检查是否开启缓存，反代，正代等。 我这边刷新频率是1s，同时我nginx缓存是1s，其实间隔2s刷新 @pkuplus

**Comment by pkuplus** [comment]
@cppla 好的。

我刚用秒表看了下，大概30秒刷一次，我再检查下再回复。

**Comment by pkuplus** [comment]
```
  location ~ [^/]\.php(/|$) {
    #fastcgi_pass remote_php_ip:9000;
    fastcgi_pass unix:/dev/shm/php-cgi.sock;
    fastcgi_index index.php;
    include fastcgi.conf;
  }

  location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
    #expires 30d;
    #access_log off;
    add_header Cache-Control no-cache;
  }
  location ~ .*\.(js|css)?$ {
    #expires 7d;
    #access_log off;
    add_header Cache-Control no-cache;
  }
  location ~ /\.ht {
    deny all;
  }
```

nginx 中的静态缓存我已经注释掉了，但观察发现刷新是30秒一次，请问我还需要检查哪里？

**Comment by cppla** [comment]
肯定是你nginx或者apache、tomcat等后端server 的问题， 你这是部分配置把 ？ 检查你的主nginx配置和 ServerStatus 所绑定的nginx配置文件。 和php缓存无关，这个不依赖php。你可以自行检查，f12 chrome调试。[https://s1.ax1x.com/2018/03/13/9fbksU.gif](url)

**Comment by cppla** [comment]
@pkuplus ，其实你可以针对这个Server Status 网站的目录，重写覆盖下nginx配置，既不会影响原有缓存配置，同时该ServerStatus也会是实时更新。nginx 配置本身就是模块化的，可以绑定某virtual host做重载。

**Comment by pkuplus** [comment]
```  
#If you have a lot of static files to serve through Nginx then caching of the files' metadata (not the actual files' contents) can save some latency.
  open_file_cache max=1000 inactive=20s;
  open_file_cache_valid 30s;
  open_file_cache_min_uses 2;
  open_file_cache_errors on;
```

找到原因了，是 `nginx.conf` 配置中的 `open_file_cache_valid 30s;` 的原因。谢谢帮助！@cppla
