### ISSUE TITLE
兼容性改善问题

### ISSUE THREAD

**Issue by zhuba9** [cppla/ServerStatus#151]
在ipad横屏上，丢包率显示不完整，只能显示联通和电信，可能宽度设置的不合适，希望能小改一下，感谢了
[https://wkphoto.cdn.bcebos.com/377adab44aed2e73d0e416489701a18b87d6fa41.jpg](url)

**Comment by zhuba9** [comment]
@media (min-width: 992px)
.container {
    width: 970px;
}
width: 970px; 改成 1170px 可解决

**Comment by cppla** [comment]
你是不是请求桌面版了？ 我用ipad试了试没问题呀。
