### ISSUE TITLE
增加io后, 界面非常拥挤, 是否可以自定义界面最大宽度

### ISSUE THREAD

**Issue by sqzxcv** [cppla/ServerStatus#152]
我主要是在电脑上观看, 新版增加io后, 显的非常拥挤, 是否可以自定义宽度.
现在屏幕进程变成两行.
如果自己修改css, 该修改哪个字段比较合适, 求帮忙指点下~~

**Comment by cppla** [comment]
/css/light.css 和 /css/light.css 其实就表格而已比较简单

**Comment by sqzxcv** [comment]
> /css/light.css 和 /css/light.css 其实就表格而已比较简单

我上次的建议是否可以参考:
[用ip 作为key计算当月流量使用情况](https://github.com/cppla/ServerStatus/issues/144#issuecomment-1086502797)

**Comment by cppla** [comment]
1、改成tips提示io信息了。

2、目前已经修复。 有更好的建议欢迎加入开源贡献代码。
