### ISSUE TITLE
是不是没有历史记录统计?

### ISSUE THREAD

**Issue by tanpengsccd** [cppla/ServerStatus#153]
是不是没有历史记录统计?

**Comment by cppla** [comment]
历史统计得入数据库， 还要绘图，会让探针变重。
如果有需要可以实时访问 https://domain/json/stats.json 入库即可。

**Comment by tanpengsccd** [comment]
了解.

**Comment by eightsheep67** [comment]
有没有在服务端统计的，想知道我几只鸡，一天，一周，一个月的丢包率。

**Comment by cppla** [comment]
长时间丢包率意义不大，路由是动态的，小厂商经常会更改线路。 @eightsheep67

晚高峰一般会长时间丢包，白天则不会。
