### ISSUE TITLE
Docker版本只能安装最新版本吗？

### ISSUE THREAD

**Issue by AndersonGhost** [cppla/ServerStatus#155]
大佬您好~  Docker版本只能安装最新版本吗？可否安装历史版本？

**Comment by cppla** [comment]
好主意，下午我编译一下以前的版本推上去

**Comment by AndersonGhost** [comment]
感谢大佬，辛苦了~~

**Comment by cppla** [comment]
```
最新版本：docker pull cppla/serverstatus:latest
月流量：docker pull cppla/serverstatus:1.0.7
无月流量：docker pull cppla/serverstatus:1.0.1
最老版本：docker pull cppla/serverstatus:1.0.0
```

**Comment by AndersonGhost** [comment]
> ```
> 最新版本：docker pull cppla/serverstatus:latest
> 月流量：docker pull cppla/serverstatus:1.0.7
> 无月流量：docker pull cppla/serverstatus:1.0.1
> 最老版本：docker pull cppla/serverstatus:1.0.0
> ```

感谢！！
