### ISSUE TITLE
怎么删除或者修改客户端？

### ISSUE THREAD

**Issue by wssfxtx** [cppla/ServerStatus#158]
客户端部署的时候不小心两台机器执行了同样username的命令，重新执行命令没用，导致服务端显示的是同一个信息，怎么删除或者修改客户端呢

**Comment by ligongfu** [comment]
停止运行[#93](https://github.com/cppla/ServerStatus/issues/93)后重新运行就行了

**Comment by cppla** [comment]
```
kill -15 `ps -ef | grep client-linux.py | grep -v "grep" | awk '{print $2}'`
```
