### ISSUE TITLE
能否添加统计服务器下线次数

### ISSUE THREAD

**Issue by eightsheep67** [cppla/ServerStatus#159]
能否添加统计服务器下线次数呢，统计每天/每月，最近甲骨文VPS总掉线……
这个是否只需要修改服务端的配置呢？
我这个服务端是装在自家群晖上的docker，如何能把配置文件映射出来

**Comment by cppla** [comment]
1、暂时没有该想法，第三方开发的提醒监控脚本目前不太好使，未来版本很快会加入更加可靠的监控告警。 

2、docker不论在哪里运行，都是可以自定义环境变量和外部参数的、包括挂载宿主机文件的。
