### ISSUE TITLE
希望大佬添加支持vnStat ，这样就完美了！

### ISSUE THREAD

**Issue by chobitsos** [cppla/ServerStatus#16]
我自己尝试添加这个模块，无奈本人对C#不熟悉，折腾了几个晚上均以失败告终

https://github.com/P3terChan/ServerStatus-V
这个项目里面有现成的，但是他没有三网监控，91yun的也是如此
如果大佬添加支持vnStat，那就相当的完美了
而且他这个项目的轮子过于老旧，客户端也问题多多，基本不太能用！

还有一个功能建议
其实目前那个“负载”功能基本上没什么用，因为后面已经有CPU 内存等信息
而且这个“负载”功能又占栏位，大佬大可将这个负载变成
https://github.com/ToyoDAdoubi/ServerStatus-Toyo
的在线数统计功能，逗比这个功能非常实用，配合SS V2 什么之类的，超级实用，

结合vnStat ，在线统计，这两个功能加入，这个项目将会是目前最强大的探针！
望大佬有时间抽空出来写写BUG！
仰望！

**Comment by chobitsos** [comment]
大佬，这个很难吗？

**Comment by cppla** [comment]
@chobitsos 不难，这个是独立的第三方软件。            sudo apt-get install vnstat

**Comment by chobitsos** [comment]
> @chobitsos 不难，这个是独立的第三方软件。 sudo apt-get install vnstat

已经安装，但是需要集成到你的探针里面啊
