### ISSUE TITLE
dc安装报错

### ISSUE THREAD

**Issue by ligongfu** [cppla/ServerStatus#160]
git clone 后 cd ServerStatus
运行docker-compose up -d
提示出错信息
`ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.serverstatus-network value Additional properties are not allowed ('name' was unexpected)
`

**Comment by cppla** [comment]
docker-compose版本太低，建议跟官方保持一致，debian/centos发行版默认docker-compose太旧


```
#  latest version you can install
pip3 install docker-compose
```

**Comment by DocWho22** [comment]
同样的问题
```bash
curl -L https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
chmod -x /usr/bin/docker-compose
```

**Comment by cppla** [comment]
> 同样的问题
> 
> ```shell
> curl -L https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
> chmod -x /usr/bin/docker-compose
> ```

docker-compose版本太旧，无法支持网络命名
pip3 install docker-compose

**Comment by ligongfu** [comment]
[DocWho22](https://github.com/DocWho22) 发的v2.5.0是最新版本了吧

**Comment by DocWho22** [comment]
> [DocWho22](https://github.com/DocWho22) 发的v2.5.0是最新版本了吧

谢谢回复，我意思是我也遇到了一模一样的问题，但是我用下面这个解决了。就是Debian默认的版本太低。我没说清楚引起误会了。
