### ISSUE TITLE
客户端传输的数据结构是什么样的呀

### ISSUE THREAD

**Issue by sqzxcv** [cppla/ServerStatus#162]
你好, 请教一下 client 向server上报数据结构是什么样的呀, 有没有文档, 我想一起帮忙完善一些功能

**Comment by ligongfu** [comment]
面板地址下访问路径：/json/stats.json

**Comment by sqzxcv** [comment]
> 面板地址下访问路径：/json/stats.json

客户端向服务器上报的json数据结构?

**Comment by sqzxcv** [comment]
"name":"eeww",
            "type":"cn.center1",
            "host":"cn.center1",
            "location":"[1]",
            "online4":true,
            "online6":false,
            "uptime":"15 天",
            "load_1":0.43,
            "load_5":0.46,
            "load_15":0.5,
            "ping_10010":0,
            "ping_189":0,
            "ping_10086":0,
            "time_10010":43,
            "time_189":5,
            "time_10086":14,
            "tcp_count":2903,
            "udp_count":32,
            "process_count":90,
            "thread_count":116,
            "network_rx":12145861,
            "network_tx":13793585,
            "network_in":9316695493905,
            "network_out":9256360790347,
            "cpu":19,
            "memory_total":2032600,
            "memory_used":740136,
            "swap_total":262140,
            "swap_used":0,
            "hdd_total":9794,
            "hdd_used":2854,
            "last_network_in":7567220486240,
            "last_network_out":7521576738856,
            "io_read":0,
            "io_write":0,
            "custom":""
}

是上面这样的吗?

**Comment by cppla** [comment]
是的，tcpdump 可以抓包 @sqzxcv

**Comment by sqzxcv** [comment]
> 是的，tcpdump 可以抓包 @sqzxcv

老板, 如果用golang重写现在的服务端, 难度大不大呀, 主要想解决流量统计的问题

**Comment by cppla** [comment]
> 

不难是不难，问题是你想解决什么问题呢？

**Comment by sqzxcv** [comment]
> 

主要是服务器流量统计的问题, 现在每月统计的信息很容易就出现错误. 每次更换顺序, 或者新增服务器, 都会导致其他服务器数据清零.

**Comment by sqzxcv** [comment]
> 不难是不难，问题是你想解决什么问题呢？

主要是服务器流量统计的问题, 现在每月统计的信息很容易就出现错误. 每次更换顺序, 或者新增服务器, 都会导致其他服务器数据清零.

**Comment by cppla** [comment]
> 

已经修复了，这些最基础的bug ，修复修复就好没必要造轮子。倒是前端展示可以写个优秀的皮，现在这个皮太老了。

**Comment by sqzxcv** [comment]
> 已经修复了，这些最基础的bug ，修复修复就好没必要造轮子。倒是前端展示可以写个优秀的皮，现在这个皮太老了。

万分感谢, 说实话, 我就喜欢现在这样的风格, 实用

**Comment by sqzxcv** [comment]
请问最新版本, 能自定义面板的宽度吗?, 我主要是在电脑上使用. 所以屏幕会比较宽, 现在ui两边留白太多了, 中间字段信息有点挤

**Comment by cppla** [comment]
> 请问最新版本, 能自定义面板的宽度吗?, 我主要是在电脑上使用. 所以屏幕会比较宽, 现在ui两边留白太多了, 中间字段信息有点挤

自定义 dark.css 和 light.css
