### ISSUE TITLE
pc端ping值栏无法完整显示

### ISSUE THREAD

**Issue by adobj** [cppla/ServerStatus#165]
源码部署效果为：
[显示不完整](https://www.z4a.net/images/2022/05/09/156b45a4f6d31f5c0.png)
建议将样式文件dark.css第24行、light.css第21行：
`#ping { max-width: 95px; }`
修改为：
`#ping { max-width: 120px; }`
显示效果：
[显示完整](https://www.z4a.net/images/2022/05/09/22a5a2349e306bab1.png)

**Comment by cppla** [comment]
最新版本把io 换成tips显示了。 不知道怎么显示较好

**Comment by adobj** [comment]
个人感觉单io列tips显示破坏一致性，可以把tips内容放到硬盘和TCP/UDP/进/线中间。

**Comment by cppla** [comment]
已经更新 ，谢谢 @adobj
