### ISSUE TITLE
核心占用显示不正确

### ISSUE THREAD

**Issue by ligongfu** [cppla/ServerStatus#167]
用FinalShell连接上查看CPU占用，宝塔面板显示CPU使用率，都在50%以上
云监控只显示20%不到

**Comment by cppla** [comment]
你是多核吧？我这边测试没问题呀。 有没有截图

```
一、
输入top【云监控这里取的这个值】

二、
输入top
按m
按1
```

**Comment by ligongfu** [comment]
> 你是多核吧？我这边测试没问题呀。 有没有截图
> 
> ```
> 一、
> 输入top【云监控这里取的这个值】
> 
> 二、
> 输入top
> 按m
> 按1
> ```

是单核心的

截图：
top - 18:33:23 up 28 days,  6:35,  2 users,  load average: 2.40, 2.31, 2.24
Tasks:  81 total,   2 running,  79 sleeping,   0 stopped,   0 zombie
%Cpu0  : 61.4 us,  6.4 sy,  0.0 ni, 31.2 id,  0.0 wa,  0.0 hi,  0.7 si,  0.3 st
KiB Mem : 53.3/1014668  [|||||||||||||||||||||||||||||||||||||||||||||||||||||                                               ]
KiB Swap: 16.5/1048572  [||||||||||||||||                                                                                    ]

**Comment by cppla** [comment]
> > 你是多核吧？我这边测试没问题呀。 有没有截图
> > ```
> > 一、
> > 输入top【云监控这里取的这个值】
> > 
> > 二、
> > 输入top
> > 按m
> > 按1
> > ```
> 
> 是单核心的
> 
> 截图： top - 18:33:23 up 28 days, 6:35, 2 users, load average: 2.40, 2.31, 2.24 Tasks: 81 total, 2 running, 79 sleeping, 0 stopped, 0 zombie %Cpu0 : 61.4 us, 6.4 sy, 0.0 ni, 31.2 id, 0.0 wa, 0.0 hi, 0.7 si, 0.3 st KiB Mem : 53.3/1014668 [||||||||||||||||||||||||||||||||||||||||||||||||||||| ] KiB Swap: 16.5/1048572 [|||||||||||||||| ]

然后云监控显示CPU 20%？？？？？

**Comment by ligongfu** [comment]
> > > 你是多核吧？我这边测试没问题呀。 有没有截图
> > > ```
> > > 一、
> > > 输入top【云监控这里取的这个值】
> > > 
> > > 二、
> > > 输入top
> > > 按m
> > > 按1
> > > ```
> > 
> > 
> > 是单核心的
> > 截图： top - 18:33:23 up 28 days, 6:35, 2 users, load average: 2.40, 2.31, 2.24 Tasks: 81 total, 2 running, 79 sleeping, 0 stopped, 0 zombie %Cpu0 : 61.4 us, 6.4 sy, 0.0 ni, 31.2 id, 0.0 wa, 0.0 hi, 0.7 si, 0.3 st KiB Mem : 53.3/1014668 [||||||||||||||||||||||||||||||||||||||||||||||||||||| ] KiB Swap: 16.5/1048572 [|||||||||||||||| ]
> 
> 然后云监控显示CPU 20%？？？？？

是的

**Comment by cppla** [comment]
能否贴上 ServerStatus 和 FinaShell的 对比截图

**Comment by ligongfu** [comment]
> 能否贴上 ServerStatus 和 FinaShell的 对比截图

[点此查看](https://g.cn/20220510191506.mp4)
(地址已处理)
第二行显示的是对应的数据

**Comment by cppla** [comment]
> 

空白视频

**Comment by ligongfu** [comment]
> > 
> 
> 空白视频

是用QQ录屏的，测试用PotPlayer、QQ影音、WMP，均可正常播放

**Comment by ligongfu** [comment]
> > 
> 
> 空白视频

换了下载地址，麻烦再尝试下

**Comment by cppla** [comment]
> > > 
> > 
> > 
> > 空白视频
> 
> 换了下载地址，麻烦再尝试下


@ligongfu 
采样频率不太一样吧，linux自带命令top采集的也不是秒级，所以计算起来稍微有那么点的误差。
如果觉得不一样可以换成client-psutil.py版本。cpu使用率获取方式就一句话：psutil.cpu_percent(interval=INTERVAL)
这个psutil库呢Google有大量项目用到了此库，采样准确性毋庸置疑：https://github.com/giampaolo/psutil

你看这张图片
<img width="796" alt="截屏2022-05-10 下午10 11 12" src="https://user-images.githubusercontent.com/10623809/167649184-a8239b8e-9c19-469e-9a5c-db72084ed0b9.png">

这是甲骨文4核的虚拟机，其中一个进程100%占用一个CPU核心，CPU使用率无论如何也是%25以上的。
psutil和client-linux.py均报告为25%, 可是呢Linux自身命令top呢报告使用率2%

该相信谁？再讲下去就要讲CPU的调度了。😄

**Comment by cppla** [comment]
如果感兴趣可以加我tg聊聊：cppla。 另外提醒一句老哥你的虚拟机有点超售了【ST】了。 @ligongfu 

压测CPU跑分观察不同客户端CPU使用率：
```
git clone https://github.com/cppla/Docker
docker build -f unixbench/Dockerfile -t unixbench .
docker run -ti --name=unixbench unixbench ./Run
```

top
client-linux.py
client-psutil.py
FinaShell
Xshell
Putty
甚至于xtop, htop等。
