### ISSUE TITLE
删除服务器, 其他节点流量重置了

### ISSUE THREAD

**Issue by sqzxcv** [cppla/ServerStatus#168]
刚测试了一下最新版本, 删除一个服务器后, 后面的服务器月流量自动变成0了

**Comment by cppla** [comment]
“节点流量重置” 的节点 你改动信息了吧。

**Comment by sqzxcv** [comment]
> 

没有任何改动, 只是数组的index 变了, 删除了一个服务器

**Comment by sqzxcv** [comment]
> 没有任何改动, 只是数组的index 变了, 删除了一个服务器

现在还是没办法手动设置 key, 或者用ip作为 key吗?

**Comment by cppla** [comment]
> 

数组index变了，所以会清零。。

username， name， type，host，location均不能改变。   实际部署中你们总不会保持config.json的默认用s01这种索引做用户名吧？？

默认配置文件用s01，s02，s03容易引发歧义，一会儿我去改下。。。。。

**Comment by cppla** [comment]
> > 没有任何改动, 只是数组的index 变了, 删除了一个服务器
> 
> 现在还是没办法手动设置 key, 或者用ip作为 key吗?

实现逻辑比较复杂，要不写库，要不只能写入一个新的文件。

**Comment by sqzxcv** [comment]
> 数组index变了，所以会清零。。
> 
> username， name， type，host，location均不能改变。 实际部署中你们总不会保持config.json的默认用s01这种索引做用户名吧？？

我是用节点ip作为用户名的

**Comment by cppla** [comment]
> > 数组index变了，所以会清零。。
> > username， name， type，host，location均不能改变。 实际部署中你们总不会保持config.json的默认用s01这种索引做用户名吧？？
> 
> 我是用节点ip作为用户名的

嗯呢，username， name， type，host，location均不能改变。你再增删服务器试试看是否清零。

**Comment by sqzxcv** [comment]
> 数组index变了，所以会清零。。
> 
> username， name， type，host，location均不能改变。 实际部署中你们总不会保持config.json的默认用s01这种索引做用户名吧？？

index改变, 流量就会清零, 所以这种情况下是不能删除列表中的服务器的是吗?
我这边的使用方法, ip作为用户名, 对单个节点来说,配置信息时没有变的

**Comment by sqzxcv** [comment]
哦, 我找到原因了.........location我写的是数组index, 所有location变了

**Comment by cppla** [comment]
> 哦, 我找到原因了.........location我写的是数组index, 所有location变了

嗯呢

**Comment by sqzxcv** [comment]
现在服务器的逻辑: 客户端上报的username， name， type，host，location, 必须和服务器配置的信息一致, 才算作同一个服务器, 对吗

**Comment by sqzxcv** [comment]
> > > 数组index变了，所以会清零。。
> > > username， name， type，host，location均不能改变。 实际部署中你们总不会保持config.json的默认用s01这种索引做用户名吧？？
> > 
> > 
> > 我是用节点ip作为用户名的
> 
> 嗯呢，username， name， type，host，location均不能改变。你再增删服务器试试看是否清零。

如果在配置config.json中增加一个新字段key, 来表示服务器的唯一性. 我现在是用usename 表示client的唯一性的. 不同client对应各自的username

**Comment by cppla** [comment]
> 

不是这样的，不要在服务端修改username， name， type，host，location这几个参数的值就可以了。

**Comment by sqzxcv** [comment]
> 不是这样的，不要在服务端修改username， name， type，host，location这几个参数的值就可以了。

这几个值, 表示要提前写死在服务端的config.json中的吗?

**Comment by cppla** [comment]
> 

更改会导致流量清零，其他倒是没啥。
个人主观觉得这些节点信息从上线就没修改的必要。

```
{
                        "username": "cdn-aws-1",
                        "name": "🦁️",
                        "type": "aws",
                        "host": "cdn-aws1",
                        "location": "🇸🇬",
                        "password": "USER_DEFAULT_PASSWORD",
                        "monthstart": 1
                },
{
                        "username": "oracle-kr-arm",
                        "name": "🐢",
                        "type": "arm",
                        "host": "kr-arm",
                        "location": "🇰🇷",
                        "password": "USER_DEFAULT_PASSWORD",
                        "monthstart": 1
                }
```

**Comment by balala2oo8** [comment]
节点信息确实不会经常改动，但是一个月总会改那么一两次，改一次就全完了，因为有时候会换服务器。能否将stats.json改成这种格式：
`{
    "username": {
        "name": "web",
        "type": "kvm",
        ...
    },
    "username": {
        "name": "web",
        "type": "kvm",
        ...
    },
    ...
}
`
用username或name做key都行，前台js也很好处理

**Comment by cppla** [comment]
> `{ "username": { "name": "web", "type": "kvm", ... }, "username": { "name": "web", "type": "kvm", ... }, ... } `

回头我再看下如何优化下这个

**Comment by sqzxcv** [comment]
> > `{ "username": { "name": "web", "type": "kvm", ... }, "username": { "name": "web", "type": "kvm", ... }, ... } `
> 
> 回头我再看下如何优化下这个

老板能不能请教一下,

**Comment by sqzxcv** [comment]
> > > 数组index变了，所以会清零。。
> > > username， name， type，host，location均不能改变。 实际部署中你们总不会保持config.json的默认用s01这种索引做用户名吧？？
> > 
> > 
> > 我是用节点ip作为用户名的
> 
> 嗯呢，username， name， type，host，location均不能改变。你再增删服务器试试看是否清零。

对照您的文档, 我理解服务器区分具体客户端, 是根据username进行区分的, 所以基本上username是唯一的. 这个流量能不能只绑定到username上, 在日常运维中, 除了username, 其他几个 name, type, host, location 都是在页面上展示的, 这些都可能发生变化, 只有username是用来区分不同客户端的, 所以感觉只比较username,  使用场景是不是更合理一些

**Comment by cppla** [comment]
已经做合并，分支： [usernameAsMonthTrafficKey](https://github.com/cppla/ServerStatus/tree/usernameAsMonthTrafficKey)

**Comment by sqzxcv** [comment]
> 已经做合并，分支： [usernameAsMonthTrafficKey](https://github.com/cppla/ServerStatus/tree/usernameAsMonthTrafficKey)

老板, 当客户端重启后, 月流量也会被清零, 这个是什么原因, 有遇到过吗, 我这里稳定重现

**Comment by cppla** [comment]
> 

正常现象，非bug 。。 客户端重启，服务端没做数据保存。。

**Comment by balala2oo8** [comment]
> > 
> 
> 正常现象，非bug 。。 客户端重启，服务端没做数据保存。。

不知道这个数据能否保存起来？

**Comment by cppla** [comment]
> > > 
> > 
> > 
> > 正常现象，非bug 。。 客户端重启，服务端没做数据保存。。
> 
> 不知道这个数据能否保存起来？

这个没有太大的意义吧。
