### ISSUE TITLE
命令行工具

### ISSUE THREAD

**Issue by kchen0x** [cppla/ServerStatus#17]
如果有命令行工具可以快速查看就好了，因为不是任何时候都想打开网页去看的。

**Comment by chobitsos** [comment]
问题是命令行你要查看什么？-a 查看节点 -b 查看虚拟化 -c 查看负载吗，太麻烦了吧

**Comment by kchen0x** [comment]
就像 htop 一样啊（未必需要实时刷新）。
返回一张 table，和网页显示的内容一样就行了。

**Comment by cppla** [comment]
@kchen0x 命令行工具，python web/ssview.py 即可。scroll=True，在gui shell 下可滚动。
效果： [https://i.loli.net/2018/12/04/5c063fc435445.png](url)
