### ISSUE TITLE
NAT机器的客户端连接问题

### ISSUE THREAD

**Issue by DawnLiExp** [cppla/ServerStatus#171]
困扰一段时间了，手头的机器大部分运行ServerStatus正常，唯独两台NAT机器经常显示处于关闭状态，偶尔又能连上，几分钟后又断开。

客户机出是全开放的，只是限制了入的端口，不知道是不是这个影响呢？想不出还有什么原因。

两个clients版本都试过，看不到任何报错，一直是这个状态：

Connecting...
Authentication successful. Access granted.

You are connecting via: IPv4

**Comment by cppla** [comment]
和服务端之间网络不稳定？

用的老版本client?

**Comment by DawnLiExp** [comment]
> 和服务端之间网络不稳定？
> 
> 用的老版本client?

可能是前者吧，ping一直在250左右，偶尔跳3 400，虽然没断
