### ISSUE TITLE
能否配置触发？

### ISSUE THREAD

**Issue by hudingwen** [cppla/ServerStatus#172]
当服务器不在线了，可以触发shell脚本？

**Comment by cppla** [comment]
下一版本会更新 微信通知和 tg通知。   shell触发是用于报警？

**Comment by hudingwen** [comment]
> l触发是用于报警

shell里面就可以触发各种触发 比如shell里面预置了变量,这个我触发微信或者tg时候可自由配置

**Comment by hudingwen** [comment]
> 下一版本会更新 微信通知和 tg通知。 shell触发是用于报警？

其实你提供一个访问接口,这样实现微信还是tg方便自己实现即可

**Comment by cppla** [comment]
你指的是服务端在客户端宕机的时候 发起http通知回调吧？

**Comment by hudingwen** [comment]
> 你指的是服务端在客户端宕机的时候 发起http通知回调吧？

可以这样子理解 但是我觉得不限于这个

**Comment by cppla** [comment]
好主意

**Comment by hudingwen** [comment]
> 好主意

老板计划何时开动？做一个接口，其他就交给我们吧🌝🌝

**Comment by cppla** [comment]
> 

能不能简单描述一下这个接口是什么样子？

类似这种？
```
{
			"username": "s01",
			"name": "node1",
			"type": "xen",
			"host": "host1",
			"location": "🇨🇳",
			"password": "USER_DEFAULT_PASSWORD",
			"monthstart": 1,
                        "callback": "your custom callback send warning URL"
}
```

**Comment by hudingwen** [comment]
> > 
> 
> 能不能简单描述一下这个接口是什么样子？
> 
> 类似这种？
> 
> ```
> {
> 			"username": "s01",
> 			"name": "node1",
> 			"type": "xen",
> 			"host": "host1",
> 			"location": "🇨🇳",
> 			"password": "USER_DEFAULT_PASSWORD",
> 			"monthstart": 1,
>                         "callback": "your custom callback send warning URL"
> }
> ```

#调用接口
#!/bin/bash
# 给到预设变量
# $username 
# $name
# $host
# $remark

上面的接口给到的 
下面的操作就给我们,例如:
$isOK =  curl  https://get.xxx.com?name=$username 
if $isOK
exit 0 
else
exit 1
#当状态为1时,说明脚本触发失败,可以配置是否再次触发或者触发频率等

**Comment by hudingwen** [comment]
这样子抛出的接口就能满足各种接入 微信推送,钉钉推送,还是tg推送 用户自己整即可  你这边也不用再考虑各种情况了

**Comment by cppla** [comment]
> 这样子抛出的接口就能满足各种接入 微信推送,钉钉推送,还是tg推送 用户自己整即可 你这边也不用再考虑各种情况了

现在接口已经有了呀:   https://tz.cloudcpp.com/json/stats.json

**Comment by hudingwen** [comment]
你的意思是我自己解析stats.json文件 然后找到宕机主机 然后自己触发是吧?

**Comment by cppla** [comment]
> 你的意思是我自己解析stats.json文件 然后找到宕机主机 然后自己触发是吧?

我看你发的那个shell脚本 ，应该是想实现这种吧？ 我没理解你指的接口触发是什么意思。
```
$isOK = curl [https://get.xxx.com?name=$username](https://get.xxx.com/?name=%24username)
```

**Comment by hudingwen** [comment]
探针能在主机宕机时触发执行这个shell脚本，而这个shell脚本是我们指定的一个shell

**Comment by hudingwen** [comment]
大佬 这个功能期待完善啦

**Comment by cppla** [comment]
> 大佬 这个功能期待完善啦

嗯呢，最近在家办公比较忙，预计七月份commit。

**Comment by cppla** [comment]
触发的是一个url 。可以自行结合自己的url告警  ，bash 还是算了需求比较少。@hudingwen

**Comment by cppla** [comment]
eval表达式已经非常丰富，可以试下。

**Comment by hudingwen** [comment]
感谢感谢 我待会儿升级服务器试试

**Comment by hudingwen** [comment]
更新服务端提示错误
src/json.c: In function ‘new_value’:
src/json.c:140:45: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             value->_reserved.object_mem = (*(char **) &value->u.object.values) + values_size;
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/json.c: In function ‘json_parse_ex’:
src/json.c:364:27: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
                         (*(json_char **) &top->u.object.values) += string_length + 1;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -c -Iinclude -Wall -O2 src/argparse.c -o obj/argparse.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/network.cpp -o obj/network.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/server.cpp -o obj/server.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/network_client.cpp -o obj/network_client.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/netban.cpp -o obj/netban.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/main.cpp -o obj/main.o
src/main.cpp:11:10: fatal error: curl/curl.h: No such file or directory
 #include "curl/curl.h"
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:26: obj/main.o] Error 1
[错误] ServerStatus 服务端编译失败 !

**Comment by cppla** [comment]
看下手动安装说明

apt install libcurl4-openssl-dev

yum install libcurl-devel

**Comment by hudingwen** [comment]
OK，刚查了一下和你一样的解决办法。
试了一下微信公众号推送没啥问题，就是配置不太灵活。只能把异常信息放在url最后面进行拼接，不过也满足使用了。

**Comment by cppla** [comment]
少即是多， 配置越多越复杂反而不太好上手搞。

**Comment by hudingwen** [comment]
这倒是。

**Comment by hudingwen** [comment]
反馈了个提示，就是当服务器宕机后，推送了消息完成，在间隔时间内当服务器恢复正常后再次出现宕机就不会马上推送消息。

**Comment by cppla** [comment]
> 反馈了个提示，就是当服务器宕机后，推送了消息完成，在间隔时间内当服务器恢复正常后再次出现宕机就不会马上推送消息。

是这样的，间隔时间内用来解决频繁报警问题。运维频繁收到这种报警也是头疼。

如果不怕被骚扰的话，间隔可以配置成1s，满足报警条件随即触发，因为这个watchdog是触发式的
