### ISSUE TITLE
客户端重启后, 月流量清零

### ISSUE THREAD

**Issue by sqzxcv** [cppla/ServerStatus#173]
客户端重启后, 月流量和总流量都会被清零, ip, host, username, 等都未发生变化, 只是重启客户端

**Comment by cppla** [comment]
总流量： 从Linux自身逻辑上讲， 重启机器总流量是该清零的。
月流量： 月流量，从VPS的角度，不应该清零。

然而月流量不清零，总流量清零又会让人觉得疑惑，所以重启都清零了。

**Comment by sqzxcv** [comment]
> 总流量： 从Linux自身逻辑上讲， 重启机器总流量是该清零的。 月流量： 月流量，从VPS的角度，不应该清零。
> 
> 然而月流量不清零，总流量清零又会让人觉得疑惑，所以重启都清零了。

有办法做到都不清零吗? 或者有没有可以设置的地方.  技术层面清零没有什么问题, 可是业务角度, 清零不太好, 最好都能保留下来

**Comment by cppla** [comment]
可以做，意义不大。

如果个人有需求可以用vnstat替换client-client即可。 

https://github.com/cppla/ServerStatus/issues/66

https://github.com/cppla/ServerStatus/pull/131

**Comment by sqzxcv** [comment]
> 可以做，意义不大。
> 
> 如果个人有需求可以用vnstat替换client-client即可。
> 
> #66
> 
> #131

这种需求最好是在服务端统计, 客户端做的话有点重
