### ISSUE TITLE
关于服务器硬盘寿命检测

### ISSUE THREAD

**Issue by yimingriyue** [cppla/ServerStatus#174]
毕竟硬盘如果频繁读写，寿命短，没及时更换影响比较大。如调用smartmontools工具检查硬盘寿命，并发送邮件预警

**Comment by cppla** [comment]
服务器一般都有蜂鸣器吧？？？？？

**Comment by yimingriyue** [comment]
> 一般服务器有蜂鸣器吧？？？？
常用Windows服务器，公司每天数据双备份，软件加一份系统备份，每天疯狂读写，坏的时候容易两块一起坏，而且有坏扇区时，服务器的硬盘状态显示是正常的。
