### ISSUE TITLE
哪位大佬知道 server/config.json 里 location后面的国家是怎么修改的?

### ISSUE THREAD

**Issue by kissyouhunter** [cppla/ServerStatus#178]
google的半天也没找到应该具体怎么修改。
想加上us uk tw 啥的
但是无论是大写还是小写都不显示国旗

**Comment by cppla** [comment]
emoji 表情， 🇨🇳，🇺🇸，🇯🇵，🇨🇦，🗽

注：windows由于政治原因不显示国旗，只显示字母。

**Comment by kissyouhunter** [comment]
> emoji 表情， 🇨🇳，🇺🇸，🇯🇵，🇨🇦，🗽
> 
> 注：windows由于政治原因不显示国旗，只显示字母。

感谢大佬
ღ( ´･ᴗ･` )比心
