### ISSUE TITLE
关于ping与丢包率的监控

### ISSUE THREAD

**Issue by xifeng0** [cppla/ServerStatus#179]
电信的检测服务器是在香港吧，并不是国内的电信网，请问可以更改下吗？谢谢，因为我用的是电信网，所以对于电信的网络状况比较关注~谢谢

**Comment by chobitsos** [comment]
你自己在客户端里面把IP改成你本地的DNS即可

**Comment by xifeng0** [comment]
> 你自己在客户端里面把IP改成你本地的DNS即可

我CT那一行改成的我们当地的电信DNS的IP，好像不行
![image](https://user-images.githubusercontent.com/76558682/179380976-7842f585-58f8-41f4-83e7-09994a2c0711.png)
![image](https://user-images.githubusercontent.com/76558682/179380984-fcdc9dff-49af-4eb3-bfe4-1cec885c7b5f.png)

**Comment by chobitsos** [comment]
可能这个ip禁ping，你换成114.114.114.114试试

**Comment by xifeng0** [comment]
> 



> 可能这个ip禁ping，你换成114.114.114.114试试

我看了下，这个延迟和丢包率是测的tcp，测的80端口，所以光ping的通没用，得IP开放80端口。。所以还是不行。我找到了能ping通的IP，可惜80端口tcping不通。

**Comment by cppla** [comment]
百度的dns服务器是中国电信，且比较稳定所以用了这个，可能在香港有peer节点。

你可以试下这个：www.chinatelecom.com.cn 方向是：北京电信

**Comment by cppla** [comment]
可用备选，你当地运营商也有本地电信网站的， 开了80端口即可替换。： @xifeng0 

sh.189.cn 上海电信方向
www.chinatelecom.com.cn 北京电信方向
public-dns-a.baidu.com  北京电信方向

其他自测。
