### ISSUE TITLE
页面显示存在问题

### ISSUE THREAD

**Issue by BFDZ** [cppla/ServerStatus#18]
流量超过1000G，显示的数字会换行。建议换算成 TB
![snipaste_20180314_133905.jpg](https://i.loli.net/2018/03/14/5aa8b654e595e.jpg)

**Comment by cppla** [comment]
你这是老的版本吧 ？ @BFDZ

**Comment by BFDZ** [comment]
@cppla 是的，这个版本：20170807

**Comment by cppla** [comment]
20170807之后的版本换行问题 already fixed， 下次加上TB换算 @BFDZ
