### ISSUE TITLE
多个客户端使用同一个用户名

### ISSUE THREAD

**Issue by kchen0x** [cppla/ServerStatus#18]
多个客户端不能使用同一个用户名来连接服务端，这样我就要为每一个客户端新增一个用户名，非常不方便。

**Comment by chobitsos** [comment]
这个很难做到吧，原作者就没有这个想法，轮子框架就已经做好了，我觉得基本无法实现同一用户名，就像你玩SS，也无法同一个账户实现多个端口吧

**Comment by kchen0x** [comment]
原作者没有这样设计那就算了，没有必要重复劳动。
但这样的实现是可以的，用户名和密码只是用来鉴权的，只需要一个 hostid 就能区别是那台客户端发来的数据了。这样服务端不用维护太多的用户，因为实际上用户也就一个。

**Comment by nicky1605** [comment]
楼上说的对啊。不用新增系统账户啊，只需要把那个配置文件的账户对应关系维护好了就可以了。

**Comment by chobitsos** [comment]
> 楼上说的对啊。不用新增系统账户啊，只需要把那个配置文件的账户对应关系维护好了就可以了。

建议你去看看源码，这样搞的话改动不小，二进制文件得重新编译，我自己目前做法，复制粘贴，用户名和名字一样就行
{
			"username": "host1",
			"name": "host1",
			"type": "xen",
			"host": "host1",
			"location": "cn",
			"password": "USER_DEFAULT_PASSWORD"
		},
其实就算弄成一个用户名，我觉得好像也没多大作用，你还是得填名字，顶多少填一项用户名，然后就为了少填一项这玩意还得去编译二进制。脱着裤子放屁感觉！

**Comment by nicky1605** [comment]
> > 楼上说的对啊。不用新增系统账户啊，只需要把那个配置文件的账户对应关系维护好了就可以了。
> 
> 建议你去看看源码，这样搞的话改动不小，二进制文件得重新编译，我自己目前做法，复制粘贴，用户名和名字一样就行
> {
> "username": "host1",
> "name": "host1",
> "type": "xen",
> "host": "host1",
> "location": "cn",
> "password": "USER_DEFAULT_PASSWORD"
> },
> 其实就算弄成一个用户名，我觉得好像也没多大作用，你还是得填名字，顶多少填一项用户名，然后就为了少填一项这玩意还得去编译二进制。脱着裤子放屁感觉！

不太清楚我回答的这一版。我用的是BotoX[原版](https://github.com/BotoX/ServerStatus)的。只需要修改config.json就可以了啊，然后重启下serverstatus的服务。第一个机器用a01，第二个机器用a02。客户端不用新增系统用户，只需要在那个client文件中把用户名改成a01，不能改成同一个用户名。

**Comment by wssfxtx** [comment]
其实我觉得服务端只起监测功能，客户端连接的时候服务端能自动添加客户端信息就好了！

**Comment by cppla** [comment]
@wssfxtx @nicky1605 @kchen0x @chobitsos ，改是比较好改，直接回传机器信息（hostname，ip）就可以了，  问题是改了之后分辨客户端机器没现在直观呀。

毕竟现在有【节点名，主机名，虚拟化，位置】可以自定义。。。。。改了就只有【hostname 和 ip地址了】

**Comment by ponycloud235** [comment]
我这有70几台机器啊。。。

**Comment by cppla** [comment]
这么多，那你现在是如何部署客户端的，一个一个ssh 部署？？？。。。。 @yihuiluo235

**Comment by ponycloud235** [comment]
> 这么多，那你现在是如何部署客户端的，一个一个ssh 部署？？？。。。。 @yihuiluo235

还在考虑用什么法子 。 一个个ssh会死人 执行条ls 都会吐

**Comment by cppla** [comment]
ansible 或者 expect @yihuiluo235
