### ISSUE TITLE
容器化后无法使用用35601端口问题

### ISSUE THREAD

**Issue by hudingwen** [cppla/ServerStatus#181]
之前都是在宿主机上进行安装可以使用35601这个端口对他进行暴露外网
但是上了容器化后 我想独立使用一个server,但是这个server端在容器中只能使用80端口 没法暴露其他端口 
因此我猜想如果使用35601 端口就没法实现这个探针了
所以35601和80端口能否合成一个 都是用http模式呢?

**Comment by cppla** [comment]
容器化后跟端口什么关系 ?你把容器端口全映射出来也是可以的，不太清楚你要表达什么

```
-p 35601:35601
-p 8080:80
-p 100-65535:100-65535
```

**Comment by hudingwen** [comment]
部署的容器只能使用80端口，我就想着探针能不能后期合成一个服务，相当于监控服务器自带一个web服务

**Comment by cppla** [comment]
> 合成一个服务，相当于监控服

运维只给容器开80？？？

**Comment by cppla** [comment]
左转 ，端口复用 ：https://github.com/cppla/moto

**Comment by hudingwen** [comment]
我这么说吧 35601这个端口服务支持http服务么?

**Comment by cppla** [comment]
> 我这么说吧 35601这个端口服务支持http服务么?

不支持

**Comment by hudingwen** [comment]
如果要改造应该还是比较麻烦的吧，我只是想到服务都基于web服务来交互应该都比较通用一点吧，之前玩k8s也是遇到这类问题还好解决了

**Comment by cppla** [comment]
> 

是的，改造还是相当麻烦的。 web上报数据 /包括websocket 不是特别好。

**Comment by cppla** [comment]
那些大厂，http restful 最后都演进成了 rpc / grpc；  websocket 最后也都进行了演进，因为它只能靠消息确认才能保证消息被安全送达 真正的大规模实时消息传输演进到最后基本还是走了socket / epoll的路子 。
