### ISSUE TITLE
centos 客户端能正常连接服务器, 但是发送数据一致失败

### ISSUE THREAD

**Issue by sqzxcv** [cppla/ServerStatus#183]
客户端的日志如下:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/3991441/181689759-bf0111c3-3fd8-4d1b-8eb8-a8fed1e9ed47.png">

目前两台国内centos机器都有这种情况, 客户端机器重启后, 能恢复正常, 但是运行最多一个小时候后, 就有开始出现上面的错误. 这种一般是什么情况呀.
客户端本地ping 服务器网络都正常.

**Comment by sqzxcv** [comment]
两台centos 机器在国内, 好像Debian没有这个问题

**Comment by cppla** [comment]
> 两台centos 机器在国内, 好像Debian没有这个问题

和网络有关，socket 抛出了异常。 用iperf3拉一下两台机器的连通性。

**Comment by sqzxcv** [comment]
> > 两台centos 机器在国内, 好像Debian没有这个问题
> 
> 和网络有关，socket 抛出了异常。 用iperf3拉一下两台机器的连通性。

iperf3 ping 都正常的, 我打印日志报的的确是网络错误.
但是 客户端重启后, 就能短暂恢复正常, 过一段时间后, 还是会出现上面的错误, 稳定重现

**Comment by cppla** [comment]
> 

python 版本，centos版本多少？

**Comment by sqzxcv** [comment]
> python 版本，centos版本多少？

python2, python3 都试过了, centos 7

**Comment by cppla** [comment]
> > python 版本，centos版本多少？
> 
> python2, python3 都试过了, centos 7

可以抓下包看看发生了 什么。

**Comment by sqzxcv** [comment]
> > > python 版本，centos版本多少？
> > 
> > 
> > python2, python3 都试过了, centos 7
> 
> 可以抓下包看看发生了 什么。

centos 怎么抓包呢

**Comment by cppla** [comment]
tcpdump，猜测跟你这边的小鸡网络还是有直接关系 。
