### ISSUE TITLE
客户端占用cpu达到70%，导致整体机器卡顿

### ISSUE THREAD

**Issue by Daoker01** [cppla/ServerStatus#185]
![image](https://user-images.githubusercontent.com/41233817/188292846-b1da25b9-0a74-4876-8f54-eb16d13ec509.png)

**Comment by cppla** [comment]
你这是windows环境？ 环境是什么？是否是从此库下载的脚本cppla/ServerStatus/client？

**Comment by tanglu1323123** [comment]
似乎这个程序是通过python执行的
确实会消耗比较多的CPU 用gb5来判断的话 大概会消耗200~300分的CPU

**Comment by cppla** [comment]
> @tanglu1323123 

没这说法，CPU占用率不到1%， 演示：tz.cloudcpp.com

请检查你的客户端是否从cppla/ServerStatus下载的，另外python是慢了一点但并不是骡子拉车。
