### ISSUE TITLE
1.0.9 编译失败

### ISSUE THREAD

**Issue by LiJinChang** [cppla/ServerStatus#186]
gcc -c -Iinclude -Wall -O2 src/system.c -o obj/system.o
gcc -c -Iinclude -Wall -O2 src/json.c -o obj/json.o
src/json.c: In function ‘new_value’:
src/json.c:140:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             value->_reserved.object_mem = (*(char **) &value->u.object.values) + values_size;
             ^~~~~
src/json.c: In function ‘json_parse_ex’:
src/json.c:364:25: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
                         (*(json_char **) &top->u.object.values) += string_length + 1;
                         ^
gcc -c -Iinclude -Wall -O2 src/argparse.c -o obj/argparse.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/network.cpp -o obj/network.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/server.cpp -o obj/server.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/network_client.cpp -o obj/network_client.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/netban.cpp -o obj/netban.o
g++ -c -Iinclude -Wall -O2 -std=c++11 src/main.cpp -o obj/main.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Makefile:26: recipe for target 'obj/main.o' failed
make: *** [obj/main.o] Error 4

**Comment by cppla** [comment]
小鸡内存不足，换大鸡编译。是不是机器可用内存小于512M？

加入EVAL表达后编译比较费劲。 @LiJinChang

**Comment by LiJinChang** [comment]
> 小鸡内存不足，换大鸡编译。是不是机器可用内存小于512M？
> 
> 加入EVAL表达后编译比较费劲。 @LiJinChang

谢谢，弄好了
