### ISSUE TITLE
页面显示问题，最后一例有时显示不全

### ISSUE THREAD

**Issue by szwwwxxx** [cppla/ServerStatus#187]
监控8台VPS，最后一例CM处，时而显示，时而不显示
安装环境：
uname -a
Linux s1-20220917-1925 5.15.0-1018-oracle #23-Ubuntu SMP Wed Sep 7 10:43:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED       STATUS        PORTS                                                     NAMES
eb2e4f0d12f9   cppla/serverstatus:latest   "/docker-entrypoint.…"   2 weeks ago   Up 15 hours   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:35601->35601/tcp, :::35601->35601/tcp   serverstatus

浏览环境
系统：windows11pro
浏览器:chrom、Edge
现象：最后一例CU|CT|CM的CM处，时而有显示，时而无显示，尝试改变网页缩放比例也一样问题存在。
[现像截图](https://pan.baidu.com/s/1L398NFfEinyWmP8TO47U1Q?pwd=uprs)
https://pan.baidu.com/s/1L398NFfEinyWmP8TO47U1Q?pwd=uprs

**Comment by szwwwxxx** [comment]
另外问一个问题，服务端VPS有IPV4和IPV6的地址，客户端只有IPV6地址，目前ServerStatus服务端正在监控多台IPV4客户端，那现在还能再监控IPV6的客户端吗？如何设置？

**Comment by cppla** [comment]
> 

支持双栈。默认设置就可以。

**Comment by szwwwxxx** [comment]
> > 
> 
> 支持双栈。默认设置就可以。

测试不成功！
服务端和客户端都是双栈，在客户端ping服务端的IPv6地址成功，将它填进client-linux.py里的SERVER地址，两个都重启动也不行。但，改成IPv4就可以。

**Comment by cppla** [comment]
确认下你的服务端是否支持单IPV6 数据报文接入?  如果是用docker拉起的ServerStatus看下你的docker 版本是否支持IPV6拨入。

```
telnet  ipv6地址 35601
```

**Comment by szwwwxxx** [comment]
测试成功，谢谢！
ipv6防火墙放行端口35601就可以了，只是IPV4没有放行35601时IPV4也正常，不管了，能用就好了，谢谢！

**Comment by cppla** [comment]
> 

已经微调，这个皮有点旧，回头等大佬贡献新皮吧。
