### ISSUE TITLE
客户端在NAS之类的设备上面网络显示经常不准

### ISSUE THREAD

**Issue by itgoyo** [cppla/ServerStatus#188]
<img width="1830" alt="image" src="https://user-images.githubusercontent.com/23348551/195004540-c5d17e57-cd23-4960-82e0-c7db3ac4fa99.png">

这个是平时不工作的时候，上传基本上传，但是探针已经有数据

平时tiptop查看的是上传10m/s，在探针上面看到的上传却是30~40m/s左右

客户端`python3 client-psutil.py &`,是用这个跑的

**Comment by cppla** [comment]
单位不一样吧，Mb 和 Mbps的区别

nload看下真实比特流。
```
yum install nload -y
apt install nload -y

nload eth0(你的实际网卡名)
```
