### ISSUE TITLE
请问下如何把服务端加入开机启动orz

### ISSUE THREAD

**Issue by SCGabriel** [cppla/ServerStatus#19]
不知道为啥把/root/ServerStatus/server/sergate  --config=config.json --web-dir=/home/wwwroot/ServerStatus/ 加入  /etc/rc.local并不会开机启动，也给了chmod +x权限的

**Comment by cppla** [comment]
@SCGabriel 编辑/etc/crontab，尾部加入：@reboot root /root/rules.sh即可，/root/rules.sh为脚本路径，好多种写法呢， 具体出门左转Google
