### ISSUE TITLE
手机端网页显示无适配

### ISSUE THREAD

**Issue by kchen0x** [cppla/ServerStatus#19]
不管是竖屏、横屏，还是请求桌面站点，都没有适配，信息看不全，也无法点击。

with iPhone8 Plus, iOS 12, Safari

**Comment by chobitsos** [comment]
这个没办法，原作者就没有适配，再说不管怎么适配也无法显示全部的信息的，只能显示部分，要不然你就自己改下CSS，附上一个改好的CSS
https://github.com/91yun/ServerStatus/commit/d73cb71b8e95ff8ddf6f7f6f22350bed07f089f5
源码出自91yun

**Comment by DawnLiExp** [comment]
其实手机显示界面稍微调整下。比如把负载隐藏，最重要的节点名能显示出来就好多了，不然非得横过来才知道哪台是哪台，😄️

iOS11.3.1 Safari

**Comment by cppla** [comment]
fixed
