### ISSUE TITLE
客户端启动的时候出现user_not_login:用户未登录

### ISSUE THREAD

**Issue by itgoyo** [cppla/ServerStatus#192]
```
etc/init.d/status-client: line 1: msg:{user_not_login:用户未登录}: command not found
```
<img width="727" alt="image" src="https://user-images.githubusercontent.com/23348551/198973441-15c6c78b-fcae-4dcf-a2ee-752ff4ed8e2a.png">

**Comment by cppla** [comment]
这是第三方脚本，不属于这个github project profile ， 谁写的找谁。

**Comment by cppla** [comment]
可以试试这个：https://github.com/cppla/ServerStatus/blob/master/status.sh
