### ISSUE TITLE
docker-compose 后SSH丢失，重连后也非常缓慢

### ISSUE THREAD

**Issue by luckiestone** [cppla/ServerStatus#196]
同一个机子，原本用的CentOS 7, docker-compose正常，重装为`Ubuntu 11.2.0-19`后运行docker-compose到固定地方，到哪里我忘了会卡住，好像是5/6不是很确定，整个SSH卡住，然后丢失，尝试重连很困难，就算重新连上还是非常慢。1G的内存也几乎占满，和这个非常相似：https://stackoverflow.com/questions/41736187/docker-compose-network-creation-kicks-me-out-of-ssh
不知道如何解决，以及还有几个问题:
 - 这种情况SSH重连后compose会在后台继续运行至完成，还是说就不能成功了，必须强制关机？
 - 如果不能成功是否需要进行何种清理释放占用空间？
 - 直接docker run和这个compose具体有何区别，为何更推荐后者？
非常感谢！

**Comment by cppla** [comment]
1、centos源万年不更，ubuntu源更新较快。
2、docker-compose版本有差异或者太旧导致旧的docker-compose.yml无法使用。可以查看docker version, docker-compose version
3、run无编排，compose相当于编排了，其他可以参考docker教程。

你这个问题推测是docker创建默认的网络桥接的时候和宿主机网卡IP冲突，或其他虚拟网卡IP段冲突

**Comment by luckiestone** [comment]
> 1、centos源万年不更，ubuntu源更新较快。 2、docker-compose版本有差异或者太旧导致旧的docker-compose.yml无法使用。可以查看docker version, docker-compose version 3、run无编排，compose相当于编排了，其他可以参考docker教程。
> 
> 你这个问题推测是docker创建默认的网络桥接的时候和宿主机网卡IP冲突，或其他虚拟网卡IP段冲突

好的谢谢，直接通过run搭建了，没有问题。这个版本似乎是不能方便搭建带tg通知的？不过直接丢个单独的通知文件也一样。

**Comment by cppla** [comment]
> > 1、centos源万年不更，ubuntu源更新较快。 2、docker-compose版本有差异或者太旧导致旧的docker-compose.yml无法使用。可以查看docker version, docker-compose version 3、run无编排，compose相当于编排了，其他可以参考docker教程。
> > 你这个问题推测是docker创建默认的网络桥接的时候和宿主机网卡IP冲突，或其他虚拟网卡IP段冲突
> 
> 好的谢谢，直接通过run搭建了，没有问题。这个版本似乎是不能方便搭建带tg通知的？不过直接丢个单独的通知文件也一样。

latest version 1.0.9 ， docker-run 和 docker-compose均支持tg通知，Server酱，PushDeer通知。
