### ISSUE TITLE
手机版怎么看那个三网情况

### ISSUE THREAD

**Issue by tiewtouwa** [cppla/ServerStatus#199]
![IMG_20230213_171138](https://user-images.githubusercontent.com/78060945/218417203-18dab3bc-2266-4364-af39-11c6b529730f.jpg)

**Comment by tiewtouwa** [comment]
![Uploading IMG_20230213_173808.jpg…]()

**Comment by tiewtouwa** [comment]
![IMG_20230213_173808](https://user-images.githubusercontent.com/78060945/218423033-f128cf22-94a1-4f7b-a04e-1064de97ca7d.jpg)原来可以点开

**Comment by cppla** [comment]
是的
