### ISSUE TITLE
时延显示

### ISSUE THREAD

**Issue by kchen0x** [cppla/ServerStatus#20]
已经有了丢包率，如果还有时延显示就更好了。

**Comment by chobitsos** [comment]
这个可以有！增加难度不大！@cppla

**Comment by cppla** [comment]
不确定是否有，这个有什么用吗？？ @kchen0x @chobitsos

**Comment by kchen0x** [comment]
监控主机到三网的时延或者是指定主机的时延，可以辅助判断当前主机的网络质量。

**Comment by cppla** [comment]
@kchen0x @chobitsos 
已添加，鼠标停留tips显示
效果图：https://s1.ax1x.com/2018/12/21/Fs2VSJ.png
演示：https://tz.cloudcpp.com,  3ks
