### ISSUE TITLE
为什么g++编译长时间没反应？

### ISSUE THREAD

**Issue by zstdadi** [cppla/ServerStatus#200]
在vps上编译的，试了或几台机器，都是这样，太慢了，有的机器一直也编译不出来

**Comment by cppla** [comment]
因为触发式告警需要断言所有表达式，所以编译比较慢。@zstdadi

“有的机器编译不出来这个问题” 机器直接扔了吧，超售严重，实测甲骨文的1/8CPU算力， 免费AMD机几分钟也能编译出来了。

**Comment by zstdadi** [comment]
嗯嗯。就甲骨文快，请问怎么去掉触发式告警，在第一次编译成功后，方便以后编译，源代码在哪儿？

**Comment by cppla** [comment]
什么叫甲骨文快，阿里云 / 腾讯云 /aws / 甲骨文 单核CPU这些都很快就能出来了


编译不出来你是买的oneman的超售小鸡吧？


1、git clone 历史版本
2、server/obj

**Comment by cppla** [comment]
编译不出来的小鸡直接扔掉，还不如树莓派跑得快。。。。。。

**Comment by zstdadi** [comment]
请问怎么去掉触发式告警，在第一次编译成功后，方便以后编译，源代码在哪儿？或者对应Makefile里的参数是什么呢？

**Comment by cppla** [comment]
> 请问怎么去掉触发式告警，在第一次编译成功后，方便以后编译，源代码在哪儿？或者对应Makefile里的参数是什么呢？

1、git clone 历史版本即可去掉触发式告警 ，自己看Makefile

2、或者去大鸡上编译后去小鸡上运行即可。

**Comment by zstdadi** [comment]
我把 WatchdogMessage() 注释掉 就正常了，和Makefile没关系，都是
g++ -c -Iinclude -Wall -O2 src/main.cpp -o obj/main.o

那么请问WatchdogMessage() 里哪些内容导致编译慢呢？

**Comment by zstdadi** [comment]
找到了是 
        parser_t parser;
        parser.compile(expression_string,expression);
如果注释掉，就正常编译，否则就特别慢。请问有没有解决办法？

**Comment by cppla** [comment]
> 找到了是
> parser_t parser;
> parser.compile(expression_string,expression);
> 如果注释掉，就正常编译，否则就特别慢。请问有没有解决办法？

编译慢又不是运行慢，不知道你在纠结什么。放弃c++吧，你不太适合搞这个……
