### ISSUE TITLE
更新新版本后折叠页怎么没了？也看不了延时了和其他信息了

### ISSUE THREAD

**Issue by kangshs** [cppla/ServerStatus#204]

**Comment by cppla** [comment]
已经修复，jquery 3.5.0的bug  。 
重新拉下镜像。

**Comment by ANewPassword** [comment]
> 已经修复，jquery 3.5.0的bug 。 重新拉下镜像。

~~似乎没有push到dockerhub？~~
我的问题，旧js被缓存了

**Comment by cppla** [comment]
清空浏览器缓存
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："墨茶 ***@***.***&gt;;
发送时间：2023年4月5日(星期三) 下午5:17
收件人："cppla/ServerStatus" ***@***.***&gt;;
抄送："cppla ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [cppla/ServerStatus] 更新新版本后折叠页怎么没了？也看不了延时了和其他信息了 (Issue #204)
-----------------------------------

 

  
已经修复，jquery 3.5.0的bug 。 重新拉下镜像。
  
似乎没有push到dockerhub？
