### ISSUE TITLE
callback通知多用户

### ISSUE THREAD

**Issue by tanglu1323123** [cppla/ServerStatus#206]
作者你好
我想某条规则同时通知多个telegram_bot
我现在的做法是这样（将规则复制多份，依次填入bot的API）

```
		{
			"name": "内存超过80%",
			"rule": "(memory_used/memory_total)*100>90",
			"interval": 300,
			"callback": "https://yourSMSurl1"
		},
		{
			"name": "内存超过80%",
			"rule": "(memory_used/memory_total)*100>90",
			"interval": 300,
			"callback": "https://yourSMSurl2"
		},
```

但是这样行数太多了，请问有更简短的方法吗？

**Comment by cppla** [comment]
> 作者你好 我想某条规则同时通知多个telegram_bot 我现在的做法是这样（将规则复制多份，依次填入bot的API）
> 
> ```
> 		{
> 			"name": "内存超过80%",
> 			"rule": "(memory_used/memory_total)*100>90",
> 			"interval": 300,
> 			"callback": "https://yourSMSurl1"
> 		},
> 		{
> 			"name": "内存超过80%",
> 			"rule": "(memory_used/memory_total)*100>90",
> 			"interval": 300,
> 			"callback": "https://yourSMSurl2"
> 		},
> ```
> 
> 但是这样行数太多了，请问有更简短的方法吗？

没有，为什么要这么发啊？ 为什么要给多个telegram_bot发送消息？
如果合理从源码上倒是可以改造一下。

**Comment by tanglu1323123** [comment]
比如一个朋友也需要收到通知 😄 ，上午他负责，下午和晚上我负责
需要让我们都接收到 CPU/负载过高的通知

不过相比于通知多用户，我更需要这个功能 #198  因为我的CPU可能某一瞬间达到100% 但这只是某一瞬间，并不会造成机器负载上升 ，这时候我需要设置一个持续时间

**Comment by cppla** [comment]
> 比如一个朋友也需要收到通知 😄 ，上午他负责，下午和晚上我负责 需要让我们都接收到 CPU/负载过高的通知
> 
> 不过相比于通知多用户，我更需要这个功能 #198 因为我的CPU可能某一瞬间达到100% 但这只是某一瞬间，并不会造成机器负载上升 ，这时候我需要设置一个持续时间

1、多通知你可以发到一个channel里面，然后订阅这个channel就可以了。
2、一般CPU 100% 需要配合load 一起使用，才能真正监测到机器负载高且CPU已经满载

例如：

cpu>90&load_5>3 

cpu>90&load_1>10

**Comment by tanglu1323123** [comment]
> > 比如一个朋友也需要收到通知 😄 ，上午他负责，下午和晚上我负责 需要让我们都接收到 CPU/负载过高的通知
> > 不过相比于通知多用户，我更需要这个功能 #198 因为我的CPU可能某一瞬间达到100% 但这只是某一瞬间，并不会造成机器负载上升 ，这时候我需要设置一个持续时间
> 
> 1、多通知你可以发到一个channel里面，然后订阅这个channel就可以了。 2、一般CPU 100% 需要配合load 一起使用，才能真正监测到机器负载高且CPU已经满载
> 
> 例如：
> 
> cpu>90&load_5>3
> 
> cpu>90&load_1>10

1、原来还可以发到channel里面，感谢
2、我感觉CPU配合load是无意义的，因为我可以直接 load_1>3
