### ISSUE TITLE
显示错位是哪里的问题呢?

### ISSUE THREAD

**Issue by SuperMax-Z** [cppla/ServerStatus#207]
config.json 是官网下载的 只改了user和password, 客户端用的是群晖docker版本  求大佬指点下 谢谢
![iShot_2023-04-21_14 40 01](https://user-images.githubusercontent.com/48038881/233560472-67dd3c88-2818-4e12-a582-f2652f0db814.png)

**Comment by cppla** [comment]
清空浏览器缓存，serverstatus.js不是最新版本吧。

**Comment by SuperMax-Z** [comment]
我是用群晖做的 服务端, 用的docker, 如果配置文件删除后, 显示是空页面没问题, 把配置文件填写好 启动就错位, 我用stilleshan/serverstatus 这个镜像就不错位,  用的是client-psutil.py 连接的, 我想问下 协议   月流量这些 需要再设置吗? 还是只配置  ip  user password 就可以了?

**Comment by cppla** [comment]
> 我是用群晖做的 服务端, 用的docker, 如果配置文件删除后, 显示是空页面没问题, 把配置文件填写好 启动就错位, 我用stilleshan/serverstatus 这个镜像就不错位, 用的是client-psutil.py 连接的, 我想问下 协议 月流量这些 需要再设置吗? 还是只配置 ip user password 就可以了?

看你讲了这么多，好像你用的不是cppla这个版本。。😄

**Comment by SuperMax-Z** [comment]
用的是 这个镜像.  cppla/serverstatus:latest

**Comment by cppla** [comment]
client用的是不是这个呢： https://github.com/cppla/ServerStatus/tree/master/clients

如果是，清空浏览器缓存就可以正常了。

**Comment by SuperMax-Z** [comment]
我之前用 stilleshan/serverstatus  能连接显示,但因为功能没有 cppla 显示的信息多, 我就想换个,  目前用cppla/serverstatus:latest  按client-psutil.py 配置好参数能连接上, 但没有 ipv4 ipv6, 月流量, 和 cu ct cm 的ping值, 同时显示错位, 确实很奇怪,  我自己在研究下吧. 谢谢了

**Comment by cppla** [comment]
> 

stilleshan的JS需要清空，或者用浏览器隐身模式再试。

**Comment by SuperMax-Z** [comment]
谢谢大佬, 确实是浏览器缓存的事  已经可以了
