### ISSUE TITLE
emoji如何显示的

### ISSUE THREAD

**Issue by ezreal130** [cppla/ServerStatus#208]
界面里的位置等信息内容中怎么显示emoji国旗的，我配置了国旗代码，好像没起作用？请指教

**Comment by cppla** [comment]
windows 由于政治原因，默认不显示emoji国旗 。

**Comment by tiewtouwa** [comment]
谷歌插件 Country Flag Fixer

**Comment by louis26wq** [comment]
输入法直接敲国家名字,会显示出emoji,,,选择图标,,,选择图标后在文档编辑器是看不到图标的,,,引号内什么都没有.但是,网页会有哦.
