### ISSUE TITLE
client-psutil在阿里云的windows2008 SP2标准版里有BUG

### ISSUE THREAD

**Issue by 7sep** [cppla/ServerStatus#21]
之前用着没问题，自从python升级？之后就提示
psutil-debug> GetActiveProcessorCount<> not available ;useing GetNativeSystemInfo<>

一直不断重复这句话，并不能用了。。。
求解，谢谢

**Comment by cppla** [comment]
这函数意思是获取不到cpu信息，应该是升级缺少运行库【VS 2008 lib for python 2.6 or python 2.7； VS 2010 lib for python 3.4 ; VS 2015+ lib for python 3.5】导致的，或试下 reinstall psutil package for your windows

**Comment by cppla** [comment]
@7sep https://www.cr173.com/soft/3797.html 如果还不行，留下Q，我帮你看下。

**Comment by 7sep** [comment]
@cppla 还不行。。。。QQ：409505228，谢谢

**Comment by cppla** [comment]
已解决
