### ISSUE TITLE
这个冗余能否去掉呢,重复太多遍了

### ISSUE THREAD

**Issue by hudingwen** [cppla/ServerStatus#211]
![image](https://github.com/cppla/ServerStatus/assets/36782822/25b326bf-d058-4aeb-b881-ed44646b320e)

**Comment by cppla** [comment]
当时出发点是，不同人要负责不同的规则。。。。。。

**Comment by hudingwen** [comment]
可以设置一个总地址  然后每次推送优先取监控规则中的没有就取总地址,这样就两者就兼得了
还有就是结尾拼接的推送内容是html内容么?我做微信推送不太方便推送 能把里面的内容分拆一下就好了

**Comment by cppla** [comment]
出发点不一样，可以自己定制一下。

**Comment by hudingwen** [comment]
没有用了  我已经用了Prometheus+Grafana+Alertmanager

**Comment by cppla** [comment]
> 没有用了 我已经用了Prometheus+Grafana+Alertmanager

嗯呢，商用还是推荐用这些，复杂但功能多，类似的还有zabbix等。

这个探针只是适用于个人用户或者追求简单的探针以及告警。
