### ISSUE TITLE
在浏览器隐身模式和不隐身模式显示不同

### ISSUE THREAD

**Issue by jorgeli2022** [cppla/ServerStatus#212]
我加了SSL，在不隐身模式下，www开头能正常显示，不加www则显示“若長時間出現此消息，請確保您已啟用Javascript！
否則雲監控主服務（服務端）未啟動或已關閉。”
但是在隐身模式下，使用www开头和不加www都能正常显示。

**Comment by cppla** [comment]
清空cookie
