### ISSUE TITLE
大家的联通延迟测试是不是掉了呀

### ISSUE THREAD

**Issue by ghost** [cppla/ServerStatus#213]
![](https://i.imgur.com/FjI3OyL.jpg)

**Comment by harveyhuangw** [comment]
![image](https://github.com/cppla/ServerStatus/assets/41227106/a9799de8-c562-4e04-a2cd-2c2431710414)
确实，好像昨天晚上开始的，大佬的演示站也是一样

**Comment by cppla** [comment]
已经切换IP。
目前逻辑有个bug，解析IP只解析一次，所以一直是100% ，修复中......

**Comment by cppla** [comment]
最好更新下客户端，可以了。

**Comment by ghost** [comment]
> 最好更新下客户端，可以了。

重启客户端，问题解决。👍

**Comment by harveyhuangw** [comment]
> 最好更新下客户端，可以了。

可以了👍

**Comment by harveyhuangw** [comment]
> 最好更新下客户端，可以了。

大佬，有个问题想问一下，就是更改了之后 `CU` IP地址，用机器直接 `ping` ，`mtr` 命令测试都没有显示丢包，客户端返回的数据确一直有丢包，感觉有点奇怪。

**Comment by ligongfu** [comment]
联通又100%了

**Comment by ghost** [comment]
还是100%lost
![](https://z1.ax1x.com/2023/09/27/pPHjbdS.jpg)

**Comment by ligongfu** [comment]
> 还是100%lost ![](https://camo.githubusercontent.com/398072ec3c45b364f2b8ebbe4ef94d9996b9bc9839cbc540f147aa445f909fb0/68747470733a2f2f7a312e617831782e636f6d2f323032332f30392f32372f7050486a6264532e6a7067)

你更新了吗？我这是正常的。

**Comment by ghost** [comment]
> > 还是100%lost ![](https://camo.githubusercontent.com/398072ec3c45b364f2b8ebbe4ef94d9996b9bc9839cbc540f147aa445f909fb0/68747470733a2f2f7a312e617831782e636f6d2f323032332f30392f32372f7050486a6264532e6a7067)
> 
> 你更新了吗？我这是正常的。

更新了，已经好了👌
