### ISSUE TITLE
丢包似乎显示不太正常

### ISSUE THREAD

**Issue by Garbo1229** [cppla/ServerStatus#216]
![image](https://github.com/cppla/ServerStatus/assets/102719303/b098b7fa-7696-4835-a7b0-6b9ad4874d96)
有人和我一样么？

**Comment by paulzzh** [comment]
同样问题 默认监测地址的话 海外机器到联通为100%丢包 大陆机器正常

**Comment by cppla** [comment]
已经更换。

**Comment by cppla** [comment]
建议更新一下client-linux, 老版本读了dns缓存，不会刷新。

**Comment by Garbo1229** [comment]
> 建议更新一下client-linux, 老版本读了dns缓存，不会刷新。

我只需将客户端的脚本更新后即可？服务端的需要做点什么么？ 还有一个问题 我看多数人的问题是联通问题 我的移动的数值有些直接不显示了 是我哪里出错了么

**Comment by cppla** [comment]
> > 建议更新一下client-linux, 老版本读了dns缓存，不会刷新。
> 
> 我只需将客户端的脚本更新后即可？服务端的需要做点什么么？ 还有一个问题 我看多数人的问题是联通问题 我的移动的数值有些直接不显示了 是我哪里出错了么

客户端更新下，重启客户端就好了

**Comment by Garbo1229** [comment]
> > > 建议更新一下client-linux, 老版本读了dns缓存，不会刷新。
> > 
> > 
> > 我只需将客户端的脚本更新后即可？服务端的需要做点什么么？ 还有一个问题 我看多数人的问题是联通问题 我的移动的数值有些直接不显示了 是我哪里出错了么
> 
> 客户端更新下，重启客户端就好了

移动节点对欧洲的vps一直100%正常么

**Comment by cppla** [comment]
> > > > 建议更新一下client-linux, 老版本读了dns缓存，不会刷新。
> > > 
> > > 
> > > 我只需将客户端的脚本更新后即可？服务端的需要做点什么么？ 还有一个问题 我看多数人的问题是联通问题 我的移动的数值有些直接不显示了 是我哪里出错了么
> > 
> > 
> > 客户端更新下，重启客户端就好了
> 
> 移动节点对欧洲的vps一直100%正常么

没看到有问题呀，可以自定义下线路试试看呢。

**Comment by Garbo1229** [comment]
> > > > > 建议更新一下client-linux, 老版本读了dns缓存，不会刷新。
> > > > 
> > > > 
> > > > 我只需将客户端的脚本更新后即可？服务端的需要做点什么么？ 还有一个问题 我看多数人的问题是联通问题 我的移动的数值有些直接不显示了 是我哪里出错了么
> > > 
> > > 
> > > 客户端更新下，重启客户端就好了
> > 
> > 
> > 移动节点对欧洲的vps一直100%正常么
> 
> 没看到有问题呀，可以自定义下线路试试看呢。

不太清楚啥情况 好像其他比较正常了 请教下如何自定义线路

**Comment by cppla** [comment]
> > > > > > 建议更新一下client-linux, 老版本读了dns缓存，不会刷新。
> > > > > 
> > > > > 
> > > > > 我只需将客户端的脚本更新后即可？服务端的需要做点什么么？ 还有一个问题 我看多数人的问题是联通问题 我的移动的数值有些直接不显示了 是我哪里出错了么
> > > > 
> > > > 
> > > > 客户端更新下，重启客户端就好了
> > > 
> > > 
> > > 移动节点对欧洲的vps一直100%正常么
> > 
> > 
> > 没看到有问题呀，可以自定义下线路试试看呢。
> 
> 不太清楚啥情况 好像其他比较正常了 请教下如何自定义线路

CM = "cm.tz.cloudcpp.com"

**Comment by yorunning** [comment]
23/9/19,这个联通的丢包率又坏了

**Comment by c9cuu** [comment]
```bash
sudo su
curl -o /opt/sss/agent/client-linux.py https://raw.githubusercontent.com/cppla/ServerStatus/master/clients/client-linux.py
systemctl restart sss-agent
```
这样应该可以了

**Comment by c9cuu** [comment]
更新最新的 python 脚本后好像还是不行
