### ISSUE TITLE
Watchdog VPS上线的规则？

### ISSUE THREAD

**Issue by jackiehj** [cppla/ServerStatus#217]
宕机是ipv4=0 请问上线的规则是什么呀？还有这个字段能不能设置的短一些？就哪个主机宕机了,哪个主机上线了

**Comment by jackiehj** [comment]
![image](https://github.com/cppla/ServerStatus/assets/32741134/38244b10-93b8-47ef-a060-2ae729c1df98)

**Comment by cppla** [comment]
上线不是必要项。 机器出了故障大多需要软重启或者硬重启等。

**Comment by jackiehj** [comment]
>  上线不是必要项。 机器出了故障大多需要软重启或者硬重启等。

那提醒的字段可以缩短吗？向上面图片那样？现在的提醒，好长一段...
