### ISSUE TITLE
服务端的web访问端口

### ISSUE THREAD

**Issue by LeooooooooonChin** [cppla/ServerStatus#22]
服务端的web访问端口是多少，如何修改呢

**Comment by LeooooooooonChin** [comment]
通过手动安装的服务器端，启动的时候命令后加上  --port
比如：nohup ./sergate --config=config.json --web-dir=/xxx/ServerStatus/web --port=1234 > /dev/null 2>&1 &
启动成功了，还是不能通过这个端口访问

**Comment by cppla** [comment]
@LeooooooooonChin 服务端的默认端口是35601， web端口不关程序的事儿， 修改nginx /apache httpd的监听端口即可。

**Comment by LeooooooooonChin** [comment]
我没有安装nginx，如果要访问web控制台，就需要装一个nginx来监听吗？

**Comment by cppla** [comment]
随便啊，没有web环境也是可以的。比如说 python ssview.py {$json url}【位于web/ssview.py】在控制台下监控，演示效果： https://i.loli.net/2018/12/07/5c0a32a9d5dba.gif
