### ISSUE TITLE
月流量重置功能

### ISSUE THREAD

**Issue by jackiehj** [cppla/ServerStatus#221]
请问，将monthstart值设置成这样 "monthstart": "10 22:30" 可以实现每个月10号22:30重置流量吗？

"servers": [
    {
        "username": "s01",
        "name": "vps-1",
        "type": "kvm",
        "host": "chengdu",
        "location": "🇨🇳",
        "password": "USER_DEFAULT_PASSWORD",
        "monthstart": "10 22:30"
    }
]

**Comment by cppla** [comment]
单位是数字 1-30非字符串，凌晨清零。


"monthstart":  10

**Comment by jackiehj** [comment]
> 单位是数字 1-30非字符串，凌晨清零。
> 
> "monthstart": 10

我想精确到小时和分钟，可以实现吗？还是就是不行？不好意思

**Comment by cppla** [comment]
> > 单位是数字 1-30非字符串，凌晨清零。
> > "monthstart": 10
> 
> 我想精确到小时和分钟，可以实现吗？还是就是不行？不好意思

只能到天。 如果精确到时分秒，需要自行修改源码。

**Comment by jackiehj** [comment]
> > > 单位是数字 1-30非字符串，凌晨清零。
> > > "monthstart": 10
> > 
> > 
> > 我想精确到小时和分钟，可以实现吗？还是就是不行？不好意思
> 
> 只能到天。 如果精确到时分秒，需要自行修改源码。

好的 我知道啦 辛苦你叻 已经做的很好了
