### ISSUE TITLE
能否指定 推送/不推送 特定机器的watchdog消息呢？

### ISSUE THREAD

**Issue by cz32483490** [cppla/ServerStatus#223]
如题，某几台机器是自己的Win，会经常开关机，没必要提醒。

根据[issue180](https://github.com/cppla/ServerStatus/issues/180#issuecomment-1190974379)里面提及的[表达式规则](https://github.com/ArashPartow/exprtk)

设置了`watchdog`里面的`offline warning rule`，添加了` & username!=username_of_win`，变成：

```
{
	"name": "offline warning",
	"rule": "online4=0 & online6=0 & username!=username_of_win",
	"interval": 600,
	"callback": "https://xxx"
},
```

但是发现规则直接失效了，非Win机器的宕机也不提醒了。

请问正确的表达式要怎么写呢？谢谢！

**Comment by cppla** [comment]
自己再试试，是可以的.

**Comment by ztdz** [comment]
> 自己再试试，是可以的.

亲测不行，好几种方式
"rule": "ping_10010>1&name=xxx",
"rule": "ping_10010>1&name==xxx",
"rule": "ping_10010>1&name!=xxx",
"rule": "ping_10010>1&username=xxx",
"rule": "ping_10010>1&username==xxx",
"rule": "ping_10010>1&username!=xxx",
全都不行
只有这个  "rule": "ping_10010>1",  可以

**Comment by cppla** [comment]
你的url callback 没有做& 特殊字符的处理。。无法正常的拼接回掉。。


下个版本我看看怎么优化替换掉这个&特殊字符。

**Comment by ztdz** [comment]
> 你的url callback 没有做& 特殊字符的处理。。无法正常的拼接回掉。。
> 
> 下个版本我看看怎么优化替换掉这个&特殊字符。

这不是rule里面的吗，和url callback没关系吧，而且像你示例里面的哪些rule里都有&，都是可以正常收到告警的，只有在加上机器名过滤的时候就失效了

**Comment by cppla** [comment]
> > 你的url callback 没有做& 特殊字符的处理。。无法正常的拼接回掉。。
> > 下个版本我看看怎么优化替换掉这个&特殊字符。
> 
> 这不是rule里面的吗，和url callback没关系吧，而且像你示例里面的哪些rule里都有&，都是可以正常收到告警的，只有在加上机器名过滤的时候就失效了

tg是可以的，一些自定义的通知接口没处理特殊字符，被吞掉了。

修复了，试试新版本。
