### ISSUE TITLE
请问client-psutil.py, 的SERVER地址，username帐号， password密码到底是哪里的帐号密码？

### ISSUE THREAD

**Issue by frankiejun** [cppla/ServerStatus#224]
我意思是client-psutil.py运行本机的用户、密码，还是服务端所在服务器的用户、密码？ 还是其他？
看你的说明还是没搞懂怎么用。

**Comment by simin-in-tw** [comment]
服务端有个配置文件，在里面有用户和密码的配置，包括监控节点的基础信息也在那个配置文件进行定义。
配置文件：https://github.com/cppla/ServerStatus/blob/master/server/config.json

如果你根据官方教程通过 Docker 部署的服务端，那么这个文件在外部的路径默认是 ~/serverstatus-config.json

**Comment by teliso** [comment]
server-config.json（config.json）里面，你需要在config.json为每台要监控的服务器手动设置账户密码，然后在要监控的服务器的py文件里面填写手动配置的账号密码。

**Comment by teliso** [comment]
运行docker的时候，命令行指定了了路劲的，一般在root目录下
