### ISSUE TITLE
联通延迟测试是不是掉了呀

### ISSUE THREAD

**Issue by kangshs** [cppla/ServerStatus#227]
联通延迟测试是不是掉了呀
![image](https://github.com/cppla/ServerStatus/assets/78369489/1400f8ac-894d-4cfc-87c3-ec0d39d70cce)

**Comment by c9cuu** [comment]
我也遇到了这个问题，但是在机器上手动 ping cu.tz.cloudcpp.com 是正常可通的

**Comment by c9cuu** [comment]
[参考这个](https://github.com/cppla/ServerStatus/issues/216)

**Comment by teliso** [comment]
我探针也是联通丢包100%，怎么解决，兄弟们？

**Comment by cppla** [comment]
已经修改 ， 已经生效。

**Comment by tsrust** [comment]
> 已经修改 ， 已经生效。

![截屏2023-09-20 09.41.31.png](https://img.imgdd.com/f210f3.15f9c03a-cf8a-45bd-8ee1-0f5e78621511.png)

还是有问题

**Comment by tsrust** [comment]
电信，联通有问题

**Comment by yorunning** [comment]
> 已经修改 ， 已经生效。

感谢，重启客户端已恢复

**Comment by kangshs** [comment]
感谢
