### ISSUE TITLE
偶尔会显示错误

### ISSUE THREAD

**Issue by Jindom** [cppla/ServerStatus#23]
![tim 20181211063645](https://user-images.githubusercontent.com/26808448/49766415-2d882000-fd10-11e8-916e-13adcd3b0da5.png)
偶尔会如上图一样，每台服务器之间隔得特别开。
正常状态如下图。
![tim 20181211064355](https://user-images.githubusercontent.com/26808448/49766440-4b558500-fd10-11e8-8895-56405f546622.png)
请问有没有什么办法解决？

**Comment by cppla** [comment]
换成最新版本试试 @jinzizhe

**Comment by cppla** [comment]
最新版本已经修正流量显示和 丢包率显示。 @jinzizhe
