### ISSUE TITLE
显示OS和kernel

### ISSUE THREAD

**Issue by iefnuy** [cppla/ServerStatus#231]
能否加个显示系统类型和版本（https://status.nekoneko.cloud/ 里的platform），和kernel（https://status.nekoneko.cloud/ 里的内核版本）版本的信息，这些只需要在节点上线时获取一次就可以。

**Comment by cppla** [comment]
显示这个只是为了好看，没有任何实际生产意义。 

生产中没人关心到底是ubuntu/centos/debian 还是其他。
