### ISSUE TITLE
关于延时的逻辑判断

### ISSUE THREAD

**Issue by lianyis** [cppla/ServerStatus#234]
目前想监测服务器异常关机，并报警。请问一下，watchdog中能否实现，offline=0保持几秒，或几个检测周期再报警。因为目前会出现因为网络波动或其它状况导致中断个几秒，但服务器并没有真正异常，也会导致报警。

**Comment by cppla** [comment]
下次闲了会更新这块逻辑，暂时先用username!='' 或 name!='' 屏蔽掉经常闪断掉线的告警。

**Comment by xulinbao** [comment]
> 下次闲了会更新这块逻辑，暂时先用username!='' 或 name!='' 屏蔽掉经常闪断掉线的告警。

老大，这个逻辑是修改哪个位置的代码，我也遇到这个问题，服务器数量比较多，用username!='' 或 name!='' 这个方法，有点不大适合

**Comment by cppla** [comment]
1.1.3已经解决该关键bug，@lianyis @xulinbao 

**docker pull /cppla/serverstatus:latest**

**Comment by escher248** [comment]
> 1.1.3已经解决该关键bug，@lianyis @xulinbao
> 
> **docker pull /cppla/serverstatus:latest**

这个延时5s判断能不能自定义设置

**Comment by cppla** [comment]
> > 1.1.3已经解决该关键bug，@lianyis @xulinbao
> > **docker pull /cppla/serverstatus:latest**
> 
> 这个延时5s判断能不能自定义设置

自定义这个时间意义不是特别大吧？

**Comment by escher248** [comment]
> > > 1.1.3已经解决该关键bug，@lianyis @xulinbao
> > > **docker pull /cppla/serverstatus:latest**
> > 
> > 
> > 这个延时5s判断能不能自定义设置
> 
> 自定义这个时间意义不是特别大吧？
我发现更新到latest版本后，因为网络波动还是会经常报警，我看把这个时间调大点会不会正常些

**Comment by cppla** [comment]
> > > > 1.1.3已经解决该关键bug，@lianyis @xulinbao
> > > > **docker pull /cppla/serverstatus:latest**
> > > 
> > > 
> > > 这个延时5s判断能不能自定义设置
> > 
> > 
> > 自定义这个时间意义不是特别大吧？
> > 我发现更新到latest版本后，因为网络波动还是会经常报警，我看把这个时间调大点会不会正常些

编译docker image中，半个小时后再拉取一下：docker pull /cppla/serverstatus:latest。默认值已经改为15秒了，你再看下是否会误报。

**Comment by escher248** [comment]
> > > > > 1.1.3已经解决该关键bug，@lianyis @xulinbao
> > > > > **docker pull /cppla/serverstatus:latest**
> > > > 
> > > > 
> > > > 这个延时5s判断能不能自定义设置
> > > 
> > > 
> > > 自定义这个时间意义不是特别大吧？
> > > 我发现更新到latest版本后，因为网络波动还是会经常报警，我看把这个时间调大点会不会正常些
> 
> 编译docker image中，半个小时后再拉取一下：docker pull /cppla/serverstatus:latest。默认值已经改为15秒了，你再看下是否会误报。

好的，多谢大佬~

**Comment by escher248** [comment]
> > > > > 1.1.3已经解决该关键bug，@lianyis @xulinbao
> > > > > **docker pull /cppla/serverstatus:latest**
> > > > 
> > > > 
> > > > 这个延时5s判断能不能自定义设置
> > > 
> > > 
> > > 自定义这个时间意义不是特别大吧？
> > > 我发现更新到latest版本后，因为网络波动还是会经常报警，我看把这个时间调大点会不会正常些
> 
> 编译docker image中，半个小时后再拉取一下：docker pull /cppla/serverstatus:latest。默认值已经改为15秒了，你再看下是否会误报。

我更新之后，手动停掉client进程，等待几分钟后也没有报警，但是我用1.1.2的版本立马可以收到报警
配置如下：
 {
                        "name": "服务器离线",
                        "rule": "online4=0&online6=0",
                        "interval": 1000,
                        "callback": "https://api2.pushdeer.com/message/push?pushkey=${key}&text="
                }

**Comment by cppla** [comment]
阈值限制了，1000s是16分钟。。 16分钟内只报告一次。 

为了方便测试可以先把阈值修改为1s  @lianyis 

另外 docker logs serverstatus -f 能看到日志的输出。

**Comment by cppla** [comment]
```
（不发）网络波动，No alarm information is sent due to network fluctuations
（不发）客户端下线但未超过阈值，No alarm if the threshold is not exceeded
（发送）客户端下线且超过阈值, Client disconnects and sends alert information
```
@lianyis

**Comment by xulinbao** [comment]
辛苦大佬了，谢谢 ：）
