### ISSUE TITLE
流量重置的日期异常

### ISSUE THREAD

**Issue by jackiehj** [cppla/ServerStatus#235]
在更新1.1.1之前，流量重置是正常的。可更新了1.1.1之后,流量的重置和设定的完全无关

**Comment by jackiehj** [comment]
我明明设置了正确的日期。可是刚刚1号0点过后，就全清零了。。。

**Comment by cppla** [comment]
检查你自己的服务器时间 @jackiehj

**Comment by jackiehj** [comment]
你的意思是客户端和服务端，时间时区都需要一致对吧

**Comment by cppla** [comment]
> 你的意思是客户端和服务端，时间时区都需要一致对吧

服务器日期北京时间即可，另外1.1.1版本也没有动这块的代码大概率是你服务器时间不是北京时间。

**Comment by jackiehj** [comment]
好的，我回去试试看。因为这次升级我就先 docker stop serverstatus 然后再docker pull cppla/serverstatus:1.1.1 接着再docker start serverstatus ，然后日期重置就出问题了…

**Comment by cppla** [comment]
docker 可以映射一下物理机时间

**Comment by jackiehj** [comment]
好的 我去试试看

**Comment by jackiehj** [comment]
好了。时区改好啦，也映射物理机啦。设置了2，就等看看0点的效果啦…

**Comment by jackiehj** [comment]
改了1个客户端为2，成功了。但是有个不是2的也重置了… 我就纳闷了。

**Comment by jackiehj** [comment]
哎,还是不行 刚刚0点重置之后 1点又重置了 看来我要把服务端重新安装试试看了

**Comment by jackiehj** [comment]
我服务器重新安装了，时区也映射了。好了差不多3天，今天莫名其妙又全都重置了。哎😑

**Comment by jackiehj** [comment]
https://chjina.com/archives/69/ 可以用这个来代替原来的流量重置吗？

**Comment by cppla** [comment]
可以，另外建议先排查一下自己服务器的原因。

**Comment by jackiehj** [comment]
服务器是装在软路由本地Docker里，都没有问题啊。还有就是我重新装1.1.0版本

**Comment by jackiehj** [comment]
vnstat会和json的流量重置冲突嘛？需要删除那段monthstart吗？如果使用vnstat的话？

**Comment by cppla** [comment]
> vnstat会和json的流量重置冲突嘛？需要删除那段monthstart吗？如果使用vnstat的话？

你试试。
