### ISSUE TITLE
关于测速和丢包

### ISSUE THREAD

**Issue by jackiehj** [cppla/ServerStatus#239]
老大，我基本Base在上海。怎么让测速点全都设置成上海联通、上海电信、上海移动？

**Comment by cz32483490** [comment]
自己找个测速脚本，里面会有上海三网的测试IP，直接抄过去就行了

**Comment by jackiehj** [comment]
> 自己找个测速脚本，里面会有上海三网的测试IP，直接抄过去就行了

这个我知道。问题是我修改哪个文件里的代码？

**Comment by cz32483490** [comment]
> > 自己找个测速脚本，里面会有上海三网的测试IP，直接抄过去就行了
> 
> 这个我知道。问题是我修改哪个文件里的代码？

`/root/client-linux.py`, line14-16

**Comment by jackiehj** [comment]
> > > 自己找个测速脚本，里面会有上海三网的测试IP，直接抄过去就行了
> > 
> > 
> > 这个我知道。问题是我修改哪个文件里的代码？
> 
> `/root/client-linux.py`, line14-16

好的 谢谢您

**Comment by jackiehj** [comment]
> > > 自己找个测速脚本，里面会有上海三网的测试IP，直接抄过去就行了
> > 
> > 
> > 这个我知道。问题是我修改哪个文件里的代码？
> 
> `/root/client-linux.py`, line14-16

忘记问了，是修改每一个客户端里`/root/client-linux.py`, line14-16 对吧。
