### ISSUE TITLE
服务端和客户端一直连不上

### ISSUE THREAD

**Issue by kobe6013** [cppla/ServerStatus#245]
![image](https://github.com/cppla/ServerStatus/assets/42176881/983b8f0d-6492-4844-834d-eca51b6e22c3)
只有本地服务端ip才连上
远程服务器（无论ip还是域名）都连不上
试过客户端普通版和跨平台版都不行。

是不是哪里少配置了？
默认端口监听正常，防火墙也没开，安全组也没开。

**Comment by kobe6013** [comment]
解决了

**Comment by EvenCu** [comment]
> 解决了

请问如何解决的?

**Comment by kobe6013** [comment]
服务端没有开放端口
