### ISSUE TITLE
作者你好，感谢你的作品，想请教一下docker部署的话，怎么用自己的证书开启https访问呢

### ISSUE THREAD

**Issue by Shrungior** [cppla/ServerStatus#25]
docker文件自带了Ngnix，直接部署好了是http访问 ，没看到有自定义配置文件的说明，不知道如何用自己的crt证书文件开启https访问，如果可以的话，希望你能指点迷津，非常感谢！

**Comment by cppla** [comment]
@Shrungior  强烈建议用反向代理开启，例如：tz.cloudcpp.com。 第二种方法： 映射默认配置和证书 到 容器，nginx config path in container ： /etc/nginx/conf.d/default.conf
