### ISSUE TITLE
1.1.5版本测试有问题

### ISSUE THREAD

**Issue by jumploop** [cppla/ServerStatus#255]
![image](https://github.com/user-attachments/assets/9c4fca93-4fb2-4515-9d23-f315425d1f1b)
前端无法正常显示

**Comment by cppla** [comment]
清空浏览器缓存



----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："一叶知秋 ***@***.***&gt;;
发送时间：2024年8月18日(星期天) 晚上10:34
收件人："cppla/ServerStatus" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[cppla/ServerStatus] 1.1.5版本测试有问题 (Issue #255)
-----------------------------------

 

 
image.png (view on web)
 前端无法正常显示
