### ISSUE TITLE
请问服务器节点展开后的详细信息中是否能展示出服务器挂载的每个磁盘分区的单独的使用情况？

### ISSUE THREAD

**Issue by ccxuy** [cppla/ServerStatus#257]

**Comment by cppla** [comment]
可以， 建议自己补充下。

比较简单。

**Comment by ccxuy** [comment]
能指导下大概修改的文件位置吗？

**Comment by cppla** [comment]
> 能指导下大概修改的文件位置吗？

最简单的方法，你把client-linux.py 里的_monitor_thread函数换为读取分区信息，然后回传就好了。
这样会再服务页面展示出对应的分区信息。 

不用改动C++，改动C++难一些。
