### ISSUE TITLE
内存监测不准的问题反馈

### ISSUE THREAD

**Issue by noonecheck** [cppla/ServerStatus#259]
大佬，安装启动后，cpu监测很准，但是内存监测会错误，不正确。
使用docker搭建的，尝试了重装服务端，重启等均无效，是个例吗？

**Comment by cppla** [comment]
内存计算方式不一样，有些是1000MB为1GB，有些是1024MB为1GB。代码中可以修改为方式一或者方式二显示。 &nbsp; 另外如果是低版本linux ，对于buffer / cache的定义概念也不一样。free -m 能看到buffer和cache情况，高版本已经统一口径。
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："noonecheck ***@***.***&gt;;
发送时间：2024年10月19日(星期六) 下午3:02
收件人："cppla/ServerStatus" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[cppla/ServerStatus] 内存监测不准的问题反馈 (Issue #259)
-----------------------------------

 

 
大佬，安装启动后，cpu监测很准，但是内存监测会错误，不正确。
 使用docker搭建的，尝试了重装服务端，重启等均无效，是个例吗？

**Comment by noonecheck** [comment]
好的，谢谢，我去试试调一下

**Comment by noonecheck** [comment]
请问这个代码具体在哪个文件中。
我的系统是deban12更新过的
