### ISSUE TITLE
关于丢包率检测方向的咨询

### ISSUE THREAD

**Issue by wx2020** [cppla/ServerStatus#260]
开发者你好，关于 `client-linux.py` 文件, 有一个问题想进行咨询:

![image](https://github.com/user-attachments/assets/64b9be21-35d9-4775-bf66-3b1ce0d1cdc8)

请问 '丢包率检测方向' 是不是可以理解为 客户端 Ping 某地址并检测丢包率时，**指定的地址**？

**Comment by cppla** [comment]
是的，另注意配合修改一下监测端口PROBEPORT。

比如说TCP检测你自己的网站，你自己的虚拟机IP等

网站 80
虚拟机 22

**Comment by wx2020** [comment]
Ok, Thanks!
