### ISSUE TITLE
关于网络延迟的问题

### ISSUE THREAD

**Issue by Septrum101** [cppla/ServerStatus#28]
经过这几天的观察，发现除了移动的线路是固定IP获取信息外，电信和联通都加了cdn，获取的信息不准确。望加以修正。

**Comment by fl20002** [comment]
感谢

**Comment by cppla** [comment]
@thank243 
cdn节点基本上是服务器到china network line 回程 最优的路由吧。 默认监测的是服务器到三大运营商官网回程的较优线路。

如果更改成某个单点ip更不合适：

北京的网友想检测到北京的回程，
上海的网友想检测到上海的回程，
成都的网友想检测到成都的回程，

修改域名 可以自定义监测回程：
cu.tz.cloudcpp.com
ct.tz.cloudcpp.com
cm.tz.cloudcpp.com
