### ISSUE TITLE
网速有点不准

### ISSUE THREAD

**Issue by fl20002** [cppla/ServerStatus#29]
小鸡都限制在50M以内的速度 后台可以看到实际速度

但是监控速度 上下100M

是不是因为是开的LXC的虚拟机原因？  计算了2次？

**Comment by cppla** [comment]
@fl20002 自行把虚拟机网卡加入 屏蔽就行了，代码在client.py 95行左右

目前屏蔽了“io“,  “tun”,  "docker",   "veth",  "br-xxxxxx" 等虚拟桥接网卡

**Comment by fl20002** [comment]
确实如此   感谢
