### ISSUE TITLE
负载显示

### ISSUE THREAD

**Issue by wym3253** [cppla/ServerStatus#30]
Readme内显示在20170807修改了负载的显示方法，可是commit是从2018626开始的。请问是修改了那几个文件？

**Comment by cppla** [comment]
可从serverstatus.js 直接屏蔽 load 5 , load 15的展示， 直接显示load 1即可。   很简单，  或者自行审查代码。 @wym3253

**Comment by cppla** [comment]
client 端，查找Load_1, Load_5, Load_15即可，
Server端,，查找 m_Load_1, m_Load_5, m_Load_15
最简单的方法，serverstatus.js中直接屏蔽 load 5 , load 15字符串的拼接展示 @wym3253
