### ISSUE TITLE
banned ip

### ISSUE THREAD

**Issue by swordstudiox** [cppla/ServerStatus#31]
banned '****' for 1 minute (You're an idiot, go away.)
发现会自动ban ip，请问这是什么原因呢？

**Comment by cppla** [comment]
非法连接，核对ip, 链接密码是否正确。。或客户端多次怼单节点了。

**Comment by swordstudiox** [comment]
大佬，我客户端都没有启动，应该没有其他连接吧？
然后我在服务端机子上再启动了客户端也是一样情况

**Comment by swordstudiox** [comment]
换了台服务端还是一样，一台是virmach的，一台浪潮云
都是centos7

**Comment by cppla** [comment]
大佬应该没明白怎么用  @swordstudiox
