### ISSUE TITLE
尊敬的大佬您好，可以增加各个客户端实时流量统计统计么？

### ISSUE THREAD

**Issue by mengyalei** [cppla/ServerStatus#33]
尊敬的大佬您好，可以增加各个客户端实时流量统计么？
比如我有10台服务器，可以显示出10台服务器在某一时刻的总上传流量和下载流量。

**Comment by mengyalei** [comment]
类似于这样的统计：
<code>总下行速度： 1.1M 总上行速度： 1.0M 下行流量： 159.05G 上行流量： 155.15G </code>

**Comment by cppla** [comment]
这个主要是查看单台服务器状态用得。各个服务器用途不同，sum意义不大。
你可以sum一下json回传数据（https://xxx.com/json/stats.json）就可以实现.
