### ISSUE TITLE
大佬，建议增加一句代码修复在程序在非gui环境下目前有闪屏的bug

### ISSUE THREAD

**Issue by mengyalei** [cppla/ServerStatus#34]
大佬，建议增加一句代码修复在程序在非gui环境下目前有闪屏的bug
代码如下：<br>
<code> <meta name="viewport" content="width=device-width, initial-scale=1.0"  -webkit-backface-visibility: hidden;></code><br>
亲测在谷歌浏览器下不再出现闪屏的bug

**Comment by cppla** [comment]
大佬在吗？这个前端我还真不太懂。。非GUI环境，是如何打开GUI浏览器的？？

**Comment by cppla** [comment]
@mengyalei
