### ISSUE TITLE
Windows客户端频繁掉线

### ISSUE THREAD

**Issue by LexsionLee** [cppla/ServerStatus#37]
情况是这样的，我的服务端在洛杉矶，但是我有一台Windows Server 2012 VPS在重庆，在此机器上运行client-psutil版实现对其监测，但是它频繁掉线（几分钟掉一次）。服务端显示 OnDelClient，网页显示掉线二十多秒后能在客户端看到Disconnected...，然后显示Connecting...，然后看到服务端显示OnNewClient，最后网页重新出现数据。
我尝试使用tcping工具ping服务端对应端口，几乎没有丢包情况（小于1%）。个人感觉问题不应该出在网络传输上。
请问其他朋友有无遇到此问题，是否有解决方案？感谢！

**Comment by Hsury** [comment]
需要对这一行[代码](https://github.com/cppla/ServerStatus/blob/976b8b9c04038e3283b2f2821c89f86bf9c1d9d6/clients/client-psutil.py#L117)进行修正。
列表生成式中psutil.pids()返回的一个或多个PID有几率在执行到psutil.Process(pid).num_threads()前已被释放，即进程已结束，导致异常被抛出。

**Comment by LexsionLee** [comment]
感谢楼上大佬指导，虽然我还是不懂怎么改...

**Comment by cppla** [comment]
fixed. 占用cpu有点高，置default：0
