### ISSUE TITLE
宕机告警不知道要不要合并到master？

### ISSUE THREAD

**Issue by cppla** [cppla/ServerStatus#40]
增加了宕机告警功能，通过http callback 调用“server酱”，微信及时通知，不知道各位玩鸡大佬是否有这个需求？？？

1. 有此需求
2. 无此需求

**Comment by ccinoo** [comment]
我能说，我更喜欢邮件通知功能吗？^_^

**Comment by cppla** [comment]
> 我能说，我更喜欢邮件通知功能吗？^_^

。。。。。。本来这个是我用来轻量监控spider service的，一屏揽尽所有状态。更复杂的解决方案有 “渣逼可丝”。

**Comment by ccinoo** [comment]
> > 我能说，我更喜欢邮件通知功能吗？^_^
> 
> 。。。。。。本来这个是我用来轻量监控spider service的，一屏揽尽所有状态。更复杂的解决方案有 “渣逼可丝”。

嗯嗯，zabix还是算了。。。太重量级了。我的情况是，微信在无网络等情况下就收不到通知了。邮件的话，我都转成短信通知的。O(∩_∩)O

**Comment by stardock** [comment]
疯狂call 1  +1 +1 +1
(给你点赞，有邮件通知其实也挺好[主要担心国内服务隐私泄露])

**Comment by stardock** [comment]
1. 有此需求

**Comment by liaosanshi** [comment]
1111111111111111111111111

**Comment by lusalem** [comment]
1. 有此需求

**Comment by ZvonimirSun** [comment]
有需求+1，话说能不能给个参数允许指定http接口。这样通过tg通知会比较方便

**Comment by ghost** [comment]
有需求+1，话说能不能给个参数允许指定http接口。这样通过tg通知会比较方便

**Comment by ghost** [comment]
希望可以考虑到主被控之间偶尔通信不佳的情况，避免误通知

**Comment by ligongfu** [comment]
有此需求，但建议不要加该功能，原因如下：

1、误报率不好控制； 
2、新增该功能势必需要多种通知方式才能满足多数人需求，持项目变得臃肿后续维护成本过高；

建议有该需求的可通过其它办法替代，让本项目保持轻量状态

**Comment by radowitz** [comment]
可以的话不知是否可以加个分支，增加掉线tg推送，掉线检测1分钟之类的。因为管理的机子比较多，需要这个功能，谢谢

**Comment by galaxychuck** [comment]
> 可以的话不知是否可以加个分支，增加掉线tg推送，掉线检测1分钟之类的。因为管理的机子比较多，需要这个功能，谢谢

我也觉得TGbot推送比较好

**Comment by mjjrock** [comment]
server酱 +1

**Comment by cppla** [comment]
1.0.9 已经支持eval表达式告警，可先行测试，可通知到Server酱，telegram，pushdeer 。
