### ISSUE TITLE
能否在列表中加入空栏？

### ISSUE THREAD

**Issue by edmundzhong888** [cppla/ServerStatus#41]
首先非常感谢作者的无私奉献！
小弟已经部署成功，提出一个小要求，不知道是能自定义加入一些空栏，因为如果客户端太多需要分类时这样显示出来的列表更直观了！例如：在第四行加入一行空栏，如果空栏能写入内容更好了，例如：US-SSR   ； 这样多客户端时看得更舒服明白！ 谢谢

**Comment by ccinoo** [comment]
我是把“虚拟化”那一列，改成自己需要的。例如“说明”等。

**Comment by edmundzhong888** [comment]
请问是否有样式看看？谢谢
我现时在需要加空栏的位置使用 “pending” : true 来写一空行，但感觉还是不太好看。

**Comment by ccinoo** [comment]
> 请问是否有样式看看？谢谢
> 我现时在需要加空栏的位置使用 “pending” : true 来写一空行，但感觉还是不太好看。

web/index.html 文件中82行“虚拟化”三个字，按你需要改了就行。

![image](https://user-images.githubusercontent.com/30647119/61521634-3fb70300-aa43-11e9-9fd7-f31b13d88903.png)

**Comment by edmundzhong888** [comment]
非常感谢你的回复与帮助！

**Comment by ccinoo** [comment]
> 非常感谢你的回复与帮助！

客气
