### ISSUE TITLE
能否将docker做小一点？

### ISSUE THREAD

**Issue by ghost** [cppla/ServerStatus#47]
我用这个[Dockerfile](https://github.com/cppla/ServerStatus/blob/b61cdabd466a5ca1da3ff293e81b9a978c29d2ed/autodeploy/Dockerfile)构建出来的镜像大小高达387MB，已经很占我服务器的空间了。能否用caddy替代nginx？nginx本身就很大，用alpine镜像构建就更好了
```
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
serverstatus_server          latest              8ad86276b7a7        2 weeks ago         387MB
```

**Comment by cppla** [comment]
1、已经减小至127M，其实nginx并不大，大的是glibc环境。
2、最小的环境为alpine（musl）， debian，ubuntu，centos为gblic
3、musl做C++编译有些坑要踩，Go这种全静态编译、不牵扯到libc的话，区别倒是不大。

**Comment by cppla** [comment]
有时间会把二进制bin塞到alpine里去，体积大概十来兆。 @ClarkeCheng
