### ISSUE TITLE
某些情况下无法客户端无法获取信息

### ISSUE THREAD

**Issue by chobitsos** [cppla/ServerStatus#48]
Python 2.7.3
反复重启提示错误
`You are connecting via: IPv4
('Caught Exception:', AttributeError("'module' object has no attribute 'check_output'",))
Connecting...
Authentication successful. Access granted.`

**Comment by cppla** [comment]
@chobitsos 这个有问题吗？client-psutil.py

**Comment by chobitsos** [comment]
> @chobitsos 这个有问题吗？client-psutil.py

Traceback (most recent call last):
  File "client-linux.py", line 20, in <module>
    import psutil
ImportError: No module named psutil
client-psutil.py 根本跑不起来

**Comment by chobitsos** [comment]
> @chobitsos 这个有问题吗？client-psutil.py

已经解决，client-psutil.py没问题，安装了pip install psutil之后
