### ISSUE TITLE
服务端默认端口35601在哪改？

### ISSUE THREAD

**Issue by dovela** [cppla/ServerStatus#5]
能改的话我就加上，事有点多，脚本无限延期了...

**Comment by cppla** [comment]
search in project。  大佬别造轮子了，已经出简洁版

一键客户端。
wget --no-check-certificate -qO client-linux.py 'https://raw.githubusercontent.com/cppla/ServerStatus/master/clients/client-linux.py' && nohup python client-linux.py SERVER={$SERVER} USER={$USER} PASSWORD={$PASSWORD} >/dev/null 2>&1 &
