### ISSUE TITLE
服务器流量统计怎么清零

### ISSUE THREAD

**Issue by wei-zZZ** [cppla/ServerStatus#54]
服务器流量统计怎么清零，或者每月清零

**Comment by cppla** [comment]
可以借助vnstat来实现（yum install vnstat , apt install vnstat），然后修改vnstat配置即可。（MonthRotate 为每月流量结算日期，也就是每月流量重新计算的日期，默认为每月 1 日）

把client客户端liuliang函数替换为以下：
```
def liuliang():
	NET_IN = 0
	NET_OUT = 0
	vnstat=os.popen('vnstat --dumpdb').readlines()
	for line in vnstat:
		if line[0:4] == "m;0;":
			mdata=line.split(";")
			NET_IN=int(mdata[3])*1024*1024
			NET_OUT=int(mdata[4])*1024*1024
			break
	return NET_IN, NET_OUT
```

**Comment by wei-zZZ** [comment]
root@Sz:~# vnstat
 eth0: Not enough data available yet.
把客户客户端liuliang函数更改了就会没有流量总计是0

**Comment by cppla** [comment]
vnstat 没配置对 @wei-zZZ
