### ISSUE TITLE
大佬能否增加对某一站点 CDN 节点状态的监控支持呢？

### ISSUE THREAD

**Issue by littlegolden** [cppla/ServerStatus#56]
就比如说，a.com 这个网站，在全球有100个 CDN 节点。可以在监控面板呈现出这个网站所有节点的状态。就像 https://steamstat.us/ 这样，列出主要的节点状态。大佬您觉得呢？

**Comment by cppla** [comment]
没太明白，这个是用来监控自己服务器的。 如果处于第三方，如何获取cdn节点的状态 ？
