### ISSUE TITLE
流量统计重置

### ISSUE THREAD

**Issue by JJFLYCLOUD** [cppla/ServerStatus#57]
作者你好，我想问一下流量是如何统计出来的
我想统计机器的每个月的流量信息，但是又不想重启服务器
所以问问有没有重置流量统计的操作

**Comment by JJFLYCLOUD** [comment]
找到方法了，关了关了。。
https://www.jianshu.com/p/aa1cd84dd68d

**Comment by cppla** [comment]
另外一种方法可以使用vnstat，可以按月统计流量apt install vnstat，更方便一点 @GouGoGoal
