### ISSUE TITLE
bug : “网络”部分显示的值是实际网速的二倍

### ISSUE THREAD

**Issue by he-sb** [cppla/ServerStatus#58]
补充：
服务器系统 CentOS 7 ，使用 Docker 搭建的，监控本机和另外两台机器（系统均为 CentOS 7），都有此 bug 。

**Comment by cppla** [comment]
能提供一下网卡名吗。 ip addr @he-sb 
例如

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 00:16:3e:02:bd:d4 brd ff:ff:ff:ff:ff:ff
    inet 172.31.73.145/20 brd 172.31.79.255 scope global eth0
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:5a:d8:1f:56 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

**Comment by he-sb** [comment]
服务端：

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 00:16:11:b4:86:10 brd ff:ff:ff:ff:ff:ff
    inet /24 brd  scope global dynamic eth0
       valid_lft 2532320sec preferred_lft 2532320sec
    inet6 fe80::216:11ff:feb4:8610/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:16:32:aa:c3:ea brd ff:ff:ff:ff:ff:ff
4: br-0f04deff0e12: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:b9:61:d7:c3 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-0f04deff0e12
       valid_lft forever preferred_lft forever
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:c5:ac:0a:ab brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c5ff:feac:aab/64 scope link 
       valid_lft forever preferred_lft forever
9: vethfc62476@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether ba:fa:04:55:e6:25 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::b8fa:4ff:fe55:e625/64 scope link 
       valid_lft forever preferred_lft forever
13: veth2b7a30a@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 8e:3e:85:d3:ca:d8 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::8c3e:85ff:fed3:cad8/64 scope link 
       valid_lft forever preferred_lft forever
19: veth0d03d27@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether c6:11:ff:fb:4d:39 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::c411:ffff:fefb:4d39/64 scope link 
       valid_lft forever preferred_lft forever

客户端：

1. 同服务端;

2. 

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 10$
    link/ether 00:16:3e:b7:e0:ce brd ff:ff:ff:ff:ff:ff
    inet /24 brd  scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2607:fcd0:100:b100:216:3eff:feb7:e0ce/64 scope global deprecated mngtmpaddr dynamic
       valid_lft 1074045sec preferred_lft 0sec
    inet6 2400:30c0:2:0:216:3eff:feb7:e0ce/64 scope global deprecated mngtmpaddr dynamic
       valid_lft 1586807sec preferred_lft 0sec
    inet6 fe80::216:3eff:feb7:e0ce/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:5d:b6:31:a2 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: br-db56ac9b9b17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:93:f5:8e:ea brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-db56ac9b9b17
       valid_lft forever preferred_lft forever
    inet6 fe80::42:93ff:fef5:8eea/64 scope link
       valid_lft forever preferred_lft forever
16: veth571a715@if15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-db56ac9b9b$
    link/ether 56:a2:1d:bf:e4:53 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::54a2:1dff:febf:e453/64 scope link
       valid_lft forever preferred_lft forever
18: veth80520a6@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-db56ac9b9b$
    link/ether c6:5e:8a:d5:49:00 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::c45e:8aff:fed5:4900/64 scope link
       valid_lft forever preferred_lft forever

3. 

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether aa:aa:00:0e:94:6f brd ff:ff:ff:ff:ff:ff
    inet 21 brd  scope global dynamic eth0
       valid_lft 126363sec preferred_lft 126363sec
    inet6 fe80::a8aa:ff:fe0e:946f/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether ba:aa:00:0e:94:6f brd ff:ff:ff:ff:ff:ff
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:2e:46:1e:83 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
5: br-d056504c5c76: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:4e:02:dc:f1 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-d056504c5c76
       valid_lft forever preferred_lft forever
    inet6 fe80::42:4eff:fe02:dcf1/64 scope link
       valid_lft forever preferred_lft forever
9: vethc448c46@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-d056504c5c76$
    link/ether 56:41:a7:ae:5e:7a brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::5441:a7ff:feae:5e7a/64 scope link
       valid_lft forever preferred_lft forever
11: veth865e162@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-d056504c5c$
    link/ether da:29:49:ad:a8:e9 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::d829:49ff:fead:a8e9/64 scope link
       valid_lft forever preferred_lft forever

**Comment by cppla** [comment]
已修复，原先的时钟间隔计算方式有问题。 @he-sb

**Comment by he-sb** [comment]
> 已修复，原先的时钟间隔计算方式有问题。 @he-sb 

给劲，早点回去更新，感谢大佬！
