### ISSUE TITLE
丢包率会莫名其妙全部变成100%

### ISSUE THREAD

**Issue by a2955254088** [cppla/ServerStatus#60]
服务器上线后，过一段时间，丢包率会全部变成100%，不知道是什么原因，网址是：status.jingqingg.com

**Comment by cppla** [comment]
默认监测方向，你可以ping一下, @a2955254088 
电信： ct.tz.cloudcpp.com
联通：cu.tz.cloudcpp.com
移动:   cm.tz.cloudcpp.com

**Comment by cppla** [comment]
被qiang了？ @a2955254088

**Comment by a2955254088** [comment]
全部都没丢包哇。。然后云检测上显示丢包率全都是100%，cdn那边设置的流量是回源的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cppla"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午2:22
收件人:&nbsp;"cppla/ServerStatus"<ServerStatus@noreply.github.com&gt;;
抄送:&nbsp;"丶"<2955254088@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cppla/ServerStatus] 丢包率会莫名其妙全部变成100% (#60)





 
默认监测方向，你可以ping一下, @a2955254088
 电信： ct.tz.cloudcpp.com
 联通：cu.tz.cloudcpp.com
 移动:   cm.tz.cloudcpp.com

**Comment by tsui603** [comment]
我也是这样啊，局域网内部署，联通电信移动服务器都改成局域网内ip，一开始丢包0%，几分钟后就变成100%了

**Comment by a2955254088** [comment]
这么恐怖的吗...我默认的检测线路几分钟后会变成100%，然后我尝试改成我的域名做检测，几分钟后也是100%丢包....博客源机是阿里云的云机，不知道是不是跟这个有关系




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tsui603"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午2:26
收件人:&nbsp;"cppla/ServerStatus"<ServerStatus@noreply.github.com&gt;;
抄送:&nbsp;"丶"<2955254088@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cppla/ServerStatus] 丢包率会莫名其妙全部变成100% (#60)





 
我也是这样啊，局域网内部署，联通电信移动服务器都改成局域网内ip，一开始丢包0%，几分钟后就变成100%了

**Comment by cppla** [comment]
我明白了，因为失联是去做的tcp握手探测。你改成局域网地址，探测也端口需要改下。PORBEPORT = 80 ，修改下这个你所监控的端口 @a2955254088 @tsui603

**Comment by tsui603** [comment]
> 这么恐怖的吗...我默认的检测线路几分钟后会变成100%，然后我尝试改成我的域名做检测，几分钟后也是100%丢包....博客源机是阿里云的云机，不知道是不是跟这个有关系
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"tsui603"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月13日(星期一) 下午2:26 收件人:&nbsp;"cppla/ServerStatus"<ServerStatus@noreply.github.com&gt;; 抄送:&nbsp;"丶"<2955254088@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [cppla/ServerStatus] 丢包率会莫名其妙全部变成100% (#60) 我也是这样啊，局域网内部署，联通电信移动服务器都改成局域网内ip，一开始丢包0%，几分钟后就变成100%了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
我的情况是这样，有互联网访问权限的主机是正常的，在没有互联网访问权限的主机上部署（改了局域网ip）会出现刚刚我说的情况

**Comment by a2955254088** [comment]
不是吧.....我国内机器喔....





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cppla"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午2:23
收件人:&nbsp;"cppla/ServerStatus"<ServerStatus@noreply.github.com&gt;;
抄送:&nbsp;"丶"<2955254088@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cppla/ServerStatus] 丢包率会莫名其妙全部变成100% (#60)





 
被qiang了？ @a2955254088

**Comment by cppla** [comment]
一般情况下都是监测公网，所以失联走的是tcp握手监测。更准确一点。。
比如说境外服务器
监测：
端口80
www.facebook.com
www.twitter.com
www.google.com

锅内监测：
端口80
www.baidu.com
www.sina.com.cn
www.163.com

**Comment by tsui603** [comment]
> 我明白了，因为失联是去做的tcp握手探测。你改成局域网地址，探测也端口需要改下。PORBEPORT = 80 ，修改下这个你所监控的端口 @a2955254088 @tsui603
就是改成任何一个开通的tcp端口就可以了吗，比如22？

**Comment by cppla** [comment]
> > 我明白了，因为失联是去做的tcp握手探测。你改成局域网地址，探测也端口需要改下。PORBEPORT = 80 ，修改下这个你所监控的端口 @a2955254088 @tsui603
> > 就是改成任何一个开通的tcp端口就可以了吗，比如22？

是的 @tsui603

**Comment by tsui603** [comment]
> > > 我明白了，因为失联是去做的tcp握手探测。你改成局域网地址，探测也端口需要改下。PORBEPORT = 80 ，修改下这个你所监控的端口 @a2955254088 @tsui603
> > > 就是改成任何一个开通的tcp端口就可以了吗，比如22？
> 
> 是的 @tsui603

清楚了 谢谢！

**Comment by a2955254088** [comment]
这边正常显示MH361了，我等几分钟看看这个丢包率还会不会变成100%......





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cppla"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午2:36
收件人:&nbsp;"cppla/ServerStatus"<ServerStatus@noreply.github.com&gt;;
抄送:&nbsp;"丶"<2955254088@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cppla/ServerStatus] 丢包率会莫名其妙全部变成100% (#60)





   
我明白了，因为失联是去做的tcp握手探测。你改成局域网地址，探测也端口需要改下。PORBEPORT = 80 ，修改下这个你所监控的端口 @a2955254088 @tsui603
 就是改成任何一个开通的tcp端口就可以了吗，比如22？
   
是的 @tsui603

**Comment by a2955254088** [comment]
感谢大佬，我这边好像恢复正常了，等了一会也没看到他变成100%了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tsui603"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午2:36
收件人:&nbsp;"cppla/ServerStatus"<ServerStatus@noreply.github.com&gt;;
抄送:&nbsp;"丶"<2955254088@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cppla/ServerStatus] 丢包率会莫名其妙全部变成100% (#60)





    
我明白了，因为失联是去做的tcp握手探测。你改成局域网地址，探测也端口需要改下。PORBEPORT = 80 ，修改下这个你所监控的端口 @a2955254088 @tsui603
 就是改成任何一个开通的tcp端口就可以了吗，比如22？
   
是的 @tsui603
  
清楚了 谢谢！

**Comment by cppla** [comment]
客气， 探测方向和端口可以随便自定义，TCP握手的方式监测更为精准。 。 @a2955254088 @tsui603

**Comment by a2955254088** [comment]
好的，谢谢大佬





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cppla"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午2:46
收件人:&nbsp;"cppla/ServerStatus"<ServerStatus@noreply.github.com&gt;;
抄送:&nbsp;"丶"<2955254088@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cppla/ServerStatus] 丢包率会莫名其妙全部变成100% (#60)





 
客气， 探测方向和端口可以随便自定义，TCP握手的方式监测更为精准。 。 @a2955254088 @tsui603
