### ISSUE TITLE
大佬你好，更新后无法显示Windows网速

### ISSUE THREAD

**Issue by ferreie9128** [cppla/ServerStatus#61]
用老版本只是不太准，Linux更新后没有问题，Windows的更新后依旧是运行client-psutil.py，但是网速一直是0B，再次感谢您的辛勤付出

**Comment by cppla** [comment]
可以了，试下，上次更新忘记了psutil是windows版本。 @ferreie9128

**Comment by ferreie9128** [comment]
> 可以了，试下，上次更新忘记了psutil是windows版本。 @ferreie9128

测试了下网速显示正常了，但是流量统计飘了，实际跑了4T多，更新完过会儿看成了13T，刚刚看又变成18T了

**Comment by cppla** [comment]
window 10 测试无误，你的什么版本？ @ferreie9128

**Comment by cppla** [comment]
流量模块没动，应该不会关流量什么事儿 @ferreie9128

**Comment by ferreie9128** [comment]
> window 10 测试无误，你的什么版本？ @ferreie9128

Windows Server 2019 Standard Evaluation，那我再测试一段时间看看，谢谢大佬

**Comment by cppla** [comment]
可以在看一下，server 2019 跟win 10 一个内核，有问题在过来。

**Comment by ferreie9128** [comment]
今天直接变成54.79T | 51.69T了，差距有点大，我又下载了个14.3GB的文件测试了下，变成59.39T | 56.86T，看TrafficMonitor的统计是正常的

**Comment by cppla** [comment]
是不是装虚拟网卡了？ @ferreie9128

**Comment by ferreie9128** [comment]
> 是不是装虚拟网卡了？ @ferreie9128

机器是KVM的，用的Red Hat VirtIO Ethernet Adapter，只有这一个网卡

**Comment by cppla** [comment]
扎心了，我这没windows 小鸡， 有时间虚拟一个测试。 todo @ferreie9128

**Comment by ferreie9128** [comment]
> 扎心了，我这没windows 小鸡， 有时间虚拟一个测试。 todo @ferreie9128

好，谢谢大佬，我先退回老版本用，哈哈

**Comment by cppla** [comment]
vultr jp kvm,  windows server 2016, 下载了1GB，2GB，10GB，测试流量无误。 @ferreie9128

**Comment by ferreie9128** [comment]
> vultr jp kvm, windows server 2016, 下载了1GB，2GB，10GB，测试流量无误。 @ferreie9128

我把服务器重启了一下，又测试到现在，没再出现统计不准的问题，可能是上次没整个机器重启的问题，再次感谢大佬
