### ISSUE TITLE
如何实现对服务端自身的状态监控？

### ISSUE THREAD

**Issue by cshenxi** [cppla/ServerStatus#64]
非常好的项目，部署起来极其方便。
但是遇到了一个问题，除了客户端外，我想实现服务端的状态也一并监控了。
如果我将客户端脚本放在服务端运行，会遇到连接错误，不停的连接断开。
请问有办法实现服务端同时监控自身吗？

**Comment by he-sb** [comment]
客户端脚本放在服务端没问题啊，脚本内的 `server_ip` 写成 `127.0.0.1` 或者【服务端本机的公网 IP】都可以。

**Comment by cshenxi** [comment]
> 客户端脚本放在服务端没问题啊，脚本内的 `server_ip` 写成 `127.0.0.1` 或者【服务端本机的公网 IP】都可以。

服务端运行python脚本后，不断报错，连上断开连上断开
```
root@ruvds-ia9gz:~# /usr/bin/python /root/scripts/client-linux.py SERVER=127.0.0.1 USER=c05
Connecting...
Authentication successful. Access granted.
You are connecting via: IPv4

Timeout.

Timeout.

Disconnected...
Connecting...
Authentication successful. Access granted.
You are connecting via: IPv4

Timeout.

Timeout.

Disconnected...
Connecting...
Authentication successful. Access granted.
You are connecting via: IPv4

Timeout.

Timeout.

Disconnected...
Connecting...
Authentication successful. Access granted.
You are connecting via: IPv4

Timeout.

Timeout.

Disconnected...
```

**Comment by dellhp369** [comment]
确实有这个问题

**Comment by dellhp369** [comment]
已解决, 注释掉第297行的recv可解决.

**Comment by cppla** [comment]
再看看吧，我这边测试的，无法复现这个问题...... @dellhp369 ，能否说下你的是什么环境？？？

**Comment by cshenxi** [comment]
> 已解决, 注释掉第297行的recv可解决.

感谢啊！！成功了！太神了！我把297和298都注释了，立刻服务端的数据就显示出来了！

**Comment by cshenxi** [comment]
> 再看看吧，我这边测试的，无法复现这个问题...... @dellhp369 ，能否说下你的是什么环境？？？

我这里的服务端是ruvds的vps
```
root@ruvds-ia9gz:~# uname -a
Linux ruvds-ia9gz 5.5.5 #1 SMP Wed Feb 19 22:21:02 EST 2020 x86_64 GNU/Linux
root@ruvds-ia9gz:~# which python
/usr/bin/python
root@ruvds-ia9gz:~# ls -l /usr/bin/python
lrwxrwxrwx 1 root root 9 Jan 24  2017 /usr/bin/python -> python2.7
```
系统是Debian9，还需要其他什么环境信息吗

**Comment by dellhp369** [comment]
> 
> 
> 再看看吧，我这边测试的，无法复现这个问题...... @dellhp369 ，能否说下你的是什么环境？？？

我这里是瓦工的DC9, 另外, 另一个美化版的探针也有这个问题, 我没有细调试, 盲猜应该和粘包有关, 所以注释掉试了下, 果然如此, 配置如下:
 CPU Model            : QEMU Virtual CPU version (cpu64-rhel6)
 CPU Cores            : 1 Cores 2599.998 MHz x86_64
 CPU Cache            : 16384 KB
 OS                   : CentOS 7.8.2003 (64 Bit) KVM
 Kernel               : 5.6.11-1.el7.elrepo.x86_64
 Total Space          : 5.4 GB / 9.8 GB
 Total RAM            : 351 MB / 495 MB (130 MB Buff)
 Total SWAP           : 177 MB / 899 MB
 Uptime               : 0 days 17 hour 44 min
 Load Average         : 0.20, 0.30, 0.25
 TCP CC               : bbr
 ASN & ISP            : AS25820, IT7 Networks Inc
 Organization         : Cluster Logic Inc
 Location             : Los Angeles, United States / US
 Region               : California

**Comment by cppla** [comment]
确实是粘包了。。以下代码应该由两次返回。但是我在linode 和 vultr 下kvm centos 7.8    重新编译了下，无法复现。。。。。。无搬瓦工机器。。。。。。 @cshenxi @dellhp369
```
Authentication successful. Access granted.
You are connecting via: IPv4

**Comment by cppla** [comment]
代码逻辑上问题不大 @cshenxi @dellhp369 
```
m_Network.Send(ClientID, "Authentication successful. Access granted.");
if(m_Network.ClientAddr(ClientID)->type == NETTYPE_IPV4)
    m_Network.Send(ClientID, "You are connecting via: IPv4");
else if(m_Network.ClientAddr(ClientID)->type == NETTYPE_IPV6)
    m_Network.Send(ClientID, "You are connecting via: IPv6");

**Comment by cshenxi** [comment]
> 确实是粘包了。。以下代码应该由两次返回。但是我在linode 和 vultr 下kvm centos 7.8 重新编译了下，无法复现。。。。。。无搬瓦工机器。。。。。。 @cshenxi @dellhp369
> 
> ```
> Authentication successful. Access granted.
> You are connecting via: IPv4
> ```

代码的我就不太懂了，大佬辛苦了，我按前面的方法已经解决了，有可能只是个案，以后再有人提出的话再去深究吧

**Comment by dellhp369** [comment]
> 
> 
> 代码逻辑上问题不大 @cshenxi @dellhp369
> 
> ```
> m_Network.Send(ClientID, "Authentication successful. Access granted.");
> if(m_Network.ClientAddr(ClientID)->type == NETTYPE_IPV4)
>     m_Network.Send(ClientID, "You are connecting via: IPv4");
> else if(m_Network.ClientAddr(ClientID)->type == NETTYPE_IPV6)
>     m_Network.Send(ClientID, "You are connecting via: IPv6");
> ```

建议修改通讯协议, 制定通讯格式, 有包头包体后, 一切粘包问题不复存在.

**Comment by dellhp369** [comment]
> 
> 
> 确实是粘包了。。以下代码应该由两次返回。但是我在linode 和 vultr 下kvm centos 7.8 重新编译了下，无法复现。。。。。。无搬瓦工机器。。。。。。 @cshenxi @dellhp369
> 
> ```
> Authentication successful. Access granted.
> You are connecting via: IPv4
> ```

装bbr试试, 粘包问题可能和内核有关.

**Comment by stsdust** [comment]
> > 确实是粘包了。。以下代码应该由两次返回。但是我在linode 和 vultr 下kvm centos 7.8 重新编译了下，无法复现。。。。。。无搬瓦工机器。。。。。。 @cshenxi @dellhp369
> > ```
> > Authentication successful. Access granted.
> > You are connecting via: IPv4
> > ```
> 
> 装bbr试试, 粘包问题可能和内核有关.

我用的是5.5.5内核的bbr

**Comment by dellhp369** [comment]
> > > 确实是粘包了。。以下代码应该由两次返回。但是我在linode 和 vultr 下kvm centos 7.8 重新编译了下，无法复现。。。。。。无搬瓦工机器。。。。。。 @cshenxi @dellhp369
> > > ```
> > > Authentication successful. Access granted.
> > > You are connecting via: IPv4
> > > ```
> > 
> > 
> > 装bbr试试, 粘包问题可能和内核有关.
> 
> 我用的是5.5.5内核的bbr

不好复现就直接改通讯协议吧 反正肯定是这里的问题 封装好格式后再压个gzip 还能省流量

**Comment by cppla** [comment]
修改协议还是比较麻烦的，开源的项目能跑就行。。。（“懒”）。。。。已经从客户端判断了是否粘包，可以试试新客户端是否还有这个问题。 @dellhp369 @cshenxi

**Comment by cshenxi** [comment]
> 修改协议还是比较麻烦的，开源的项目能跑就行。。。（“懒”）。。。。已经从客户端判断了是否粘包，可以试试新客户端是否还有这个问题。 @dellhp369 @cshenxi
  
感谢大佬，在前面出现粘包问题的机子上实测有效，直接连接成功没有再出现反复disconnect的问题了。  
另外，我在这个issue（虽然已经关闭），补充了一个很小的问题，不知道大佬能否方便看一下  
[https://github.com/cppla/ServerStatus/issues/66](url)
