### ISSUE TITLE
客户端按照模版那样运行了那条代码，重启之后不能自动运行，等于说一重启客户端就失联了

### ISSUE THREAD

**Issue by inpowerchiu** [cppla/ServerStatus#65]
wget --no-check-certificate -qO client-linux.py 'https://raw.githubusercontent.com/cppla/ServerStatus/master/clients/client-linux.py' && nohup python client-linux.py SERVER=45.79.67.132 USER=s04  >/dev/null 2>&1 &

应该如何加入开机自启呢？求分享，谢谢。

**Comment by he-sb** [comment]
参考这篇，我自己水的搭建教程😂

https://tech.he-sb.top/posts/usage-of-serverstatus/

**Comment by inpowerchiu** [comment]
> 参考这篇，我自己水的搭建教程
> 
> https://tech.he-sb.top/posts/usage-of-serverstatus/

你这个图文教程最后这个
vi /etc/supervisord.d/ServerStatus.conf
我看了我客户端vps目录下没有这个目录啊？
安装过程没装这个吧？该怎么安装？没法做到一键安装吗？

**Comment by he-sb** [comment]
> 
> 
> > 参考这篇，我自己水的搭建教程
> > https://tech.he-sb.top/posts/usage-of-serverstatus/
> 
> 你这个图文教程最后这个
> vi /etc/supervisord.d/ServerStatus.conf
> 我看了我客户端vps目录下没有这个目录啊？
> 安装过程没装这个吧？该怎么安装？没法做到一键安装吗？

因为你之前没装过 supervisor 吧，参考这个先安装一下：

![图片](https://user-images.githubusercontent.com/26474615/81661845-4a79d300-946f-11ea-802e-ddfdf4b373e3.png)

**Comment by inpowerchiu** [comment]
> > > 参考这篇，我自己水的搭建教程
> > > https://tech.he-sb.top/posts/usage-of-serverstatus/
> > 
> > 
> > 你这个图文教程最后这个
> > vi /etc/supervisord.d/ServerStatus.conf
> > 我看了我客户端vps目录下没有这个目录啊？
> > 安装过程没装这个吧？该怎么安装？没法做到一键安装吗？
> 
> 因为你之前没装过 supervisor 吧，参考这个先安装一下：
> 
> ![图片](https://user-images.githubusercontent.com/26474615/81661845-4a79d300-946f-11ea-802e-ddfdf4b373e3.png)

折腾这个supervisor好久，没弄成功。不知道是不是supervisor开机没自启，客服端执行nohup python client-linux.py SERVER=ip USER=name >/dev/null 2>&1 &就能联系上服务端，我在想能不能开机延时自动执行这段代码来达到目的，搜索了一个答案，但是不太懂，大概是：

在 /etc/rc.local 文件的 exit 0 这一行百前面填度
(
sleep 300 #等待300秒，即5分钟
echo startrun # 这一行写你的命令
)& # 加括号知， 后面的 & 表示后台执行，道不让 /etc/rc.local 等待

这里echo startrun是不是不能删除？假如我想它后台自动延时输入nohup python client-linux.py SERVER=ip USER=name >/dev/null 2>&1 并且回车执行该修改成咋样，还有这样的方法是否可行呢？求解惑。

**Comment by cshenxi** [comment]
给你一个方便的方案吧，直接用systemd挂守护进程。。至于supervisor是啥我不知道。。只会用这种普通的systemd
```
cat > /etc/systemd/system/serverstatus.service <<EOF
[Unit]
Description=serverstatus service
After=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python $PATH/TO/client-linux.py SERVER=$SERVER_IP USER=$CLIENT_NAME >/dev/null 2>&1
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl start serverstatus.service
systemctl enable serverstatus.service
```

就可以了。上述内容中`ExecStart=/usr/bin/python $PATH/TO/client-linux.py SERVER=$SERVER_IP USER=$CLIENT_NAME >/dev/null 2>&1`这部分是要你自己手动改的，主要是client-linux.py的路径，对应的ip配置的user等信息

**Comment by he-sb** [comment]
> 
> 
> > > > 参考这篇，我自己水的搭建教程
> > > > https://tech.he-sb.top/posts/usage-of-serverstatus/
> > > 
> > > 
> > > 你这个图文教程最后这个
> > > vi /etc/supervisord.d/ServerStatus.conf
> > > 我看了我客户端vps目录下没有这个目录啊？
> > > 安装过程没装这个吧？该怎么安装？没法做到一键安装吗？
> > 
> > 
> > 因为你之前没装过 supervisor 吧，参考这个先安装一下：
> > ![图片](https://user-images.githubusercontent.com/26474615/81661845-4a79d300-946f-11ea-802e-ddfdf4b373e3.png)
> 
> 折腾这个supervisor好久，没弄成功。不知道是不是supervisor开机没自启，客服端执行nohup python client-linux.py SERVER=ip USER=name >/dev/null 2>&1 &就能联系上服务端，我在想能不能开机延时自动执行这段代码来达到目的，搜索了一个答案，但是不太懂，大概是：
> 
> 在 /etc/rc.local 文件的 exit 0 这一行百前面填度
> (
> sleep 300 #等待300秒，即5分钟
> echo startrun # 这一行写你的命令
> )& # 加括号知， 后面的 & 表示后台执行，道不让 /etc/rc.local 等待
> 
> 这里echo startrun是不是不能删除？假如我想它后台自动延时输入nohup python client-linux.py SERVER=ip USER=name >/dev/null 2>&1 并且回车执行该修改成咋样，还有这样的方法是否可行呢？求解惑。

supervisor 是一键安装的啊，截图的那句话是个链接，点进去有很详细的 supervisor 安装配置过程的，哪里没写明白的话可以在下面留言，不是很懂你这个“没弄成功”是指什么……

**Comment by cppla** [comment]
很多种方案，可以参考 @he-sb @inpowerchiu ，也可直接放到/etc/rc.local，服务器一般不出问题无需重启吧。
```
# uptime
16:42:49 up 950 days,  1:04,  8 users,  load average: 1.83, 1.99, 2.04
