### ISSUE TITLE
有无办法实现客户端重启后，统计数据不清0？

### ISSUE THREAD

**Issue by cshenxi** [cppla/ServerStatus#66]
有时候遇到不得不重启客户端的情况，但重启后，服务端统计到的数据就会清0了  
在此前的一个issue中看到可以实现每月清0一次  

[https://github.com/cppla/ServerStatus/issues/54#issuecomment-569884058](url)  

如果能和我的需求配合起来，就能实现客户端流量持续记录，只有月初才清0，而不用担心重启导致流量清0  

想问一下如何实现呢？

**Comment by cppla** [comment]
vnstat

**Comment by cppla** [comment]
vnstat 可以统计每月数据，apt-get install vnstat ， vnstat -m 即为统计月流量，自己修改一下流量统计代码

```
def liuliang():
	NET_IN = 0
	NET_OUT = 0
	vnstat=os.popen('vnstat --dumpdb').readlines()
	for line in vnstat:
		if line[0:4] == "m;0;":
			mdata=line.split(";")
			NET_IN=int(mdata[3])*1024*1024
			NET_OUT=int(mdata[4])*1024*1024
			break
	return NET_IN, NET_OUT

**Comment by cshenxi** [comment]
> vnstat 可以统计每月数据，apt-get install vnstat ， vnstat -m 即为统计月流量，自己修改一下流量统计代码
> 
> ```
> def liuliang():
> 	NET_IN = 0
> 	NET_OUT = 0
> 	vnstat=os.popen('vnstat --dumpdb').readlines()
> 	for line in vnstat:
> 		if line[0:4] == "m;0;":
> 			mdata=line.split(";")
> 			NET_IN=int(mdata[3])*1024*1024
> 			NET_OUT=int(mdata[4])*1024*1024
> 			break
> 	return NET_IN, NET_OUT
> ```

突然想起来个事情，想再来求问一下大佬，有办法定义“月”是从哪天开始的吗。。。我感觉这个应该是从当月第一天开始计算流量，然后下个月第一天重新计算。。那有办法从第5天或第8天开始算吗。。

**Comment by cppla** [comment]
@cshenxi 可以。如下所示，从15号开始计算月份。
参考 :  https://www.systutorials.com/docs/linux/man/5-vnstat.conf/
```
MonthRotate 15

**Comment by sxx1314** [comment]
> vnstat

vnstat 在1.x时代就没有了--dumpdb，不过可以用--json。
