### ISSUE TITLE
windows版报错

### ISSUE THREAD

**Issue by tsui603** [cppla/ServerStatus#67]
![image](https://user-images.githubusercontent.com/25866452/81779992-57a6c880-9528-11ea-8352-3a4a3cce00e5.png)

**Comment by cppla** [comment]
哪个python？ @tsui603

**Comment by tsui603** [comment]
> 哪个python？ @tsui603

2.7啊

**Comment by tsui603** [comment]
> 哪个python？ @tsui603

对了 因为本身没有python环境 我是封装exe后运行的

**Comment by cppla** [comment]
那就是了，版本不一致吧， 你可以用python3 +psutil 封装成exe。 @tsui603

**Comment by cppla** [comment]
另外可以使用管理员运行试试，这个int()强转的变量，获取貌似为空 @tsui603

**Comment by tsui603** [comment]
> 另外可以使用管理员运行试试，这个int()强转的变量，获取貌似为空 @tsui603



> 那就是了，版本不一致吧， 你可以用python3 +psutil 封装成exe。 @tsui603

两种方案都是了还是一样的情况，windows server 2008的系统，和系统有关系吗

**Comment by cppla** [comment]
报的错是int强转的时候变量为空，像是python打包exe的问题 
最好在windows server 2008 下用pyinstall 打包适合 windows 2008的exe程序。 @tsui603
