### ISSUE TITLE
server放在国内服务器,无法测延迟和丢包

### ISSUE THREAD

**Issue by Raytow** [cppla/ServerStatus#68]
cu.tz.cloudcpp.com
原因应该是这几个网址都没有备案,在国内无法访问

**Comment by cppla** [comment]
@Raytow 跟这个没关系，本来项目就是放在国内用的，放心用。
查看这个： https://github.com/cppla/ServerStatus/issues/60

**Comment by Raytow** [comment]
那可能是什么原因,测速没有,丢包为100%



在 2020年5月16日 13:38，cppla <notifications@github.com>写道：

@Raytow 跟这个没关系，本来项目就是放在国内用的，放心用。

#60



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/cppla/ServerStatus/issues/68#issuecomment-629592265",

"url": "https://github.com/cppla/ServerStatus/issues/68#issuecomment-629592265",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by cppla** [comment]
@Raytow  如果不通，可能是网络有问题。跟备案不备案没任何关系，只是tcp握手监测端口，仅此而已。
```
telnet cu.tz.cloudcpp.com 80

**Comment by Raytow** [comment]
我监测六七台机器都有这个问题,内存和cpu占用都显示正常.我在脚本里修改了那两个端口号,和这个有关系吗?



发自我的小米手机在 cppla <notifications@github.com>，2020年5月16日 14:10写道：

@Raytow  如果不通，可能是网络有问题。跟备案不备案没任何关系，只是tcp握手监测端口，仅此而已。

telnet cu.tz.cloudcpp.com 80 





—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/cppla/ServerStatus/issues/68#issuecomment-629594956",

"url": "https://github.com/cppla/ServerStatus/issues/68#issuecomment-629594956",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by cppla** [comment]
@Raytow 是的，刚才就给你发了。 refer：https://github.com/cppla/ServerStatus/issues/60
