### ISSUE TITLE
INTERVAL较高导致服务器显示失联

### ISSUE THREAD

**Issue by Chandler-Lu** [cppla/ServerStatus#69]
您好，当我将客户端`INTERVAL`设为60甚至120秒后，服务端并不会正常刷新数据，观察`stat.json`发现`online4`直接给出了false。不知道这个设定是什么，谢谢

**Comment by cppla** [comment]
调低web端刷新频率试试。 话说你为什么要搞1分钟。。。

**Comment by Chandler-Lu** [comment]
https://github.com/cppla/ServerStatus/blob/d94e6cadbfd3b2a3eee5f3fc578ff8f998c1ab7b/server/src/server.cpp#L167-L178
应该找到了，实测14秒是可以的，但是15秒后服务端没有收到客户端的报文就会timeout。。不过我还没试。
因为对于我服务器来说，前一秒和后一秒除了实时流量之外并没有什么区别。。所以我觉得这种秒级更新除了增加一些没有意义的流量之外好像实在没啥区别。。

**Comment by Chandler-Lu** [comment]
我觉得是不是可以做成只有web活跃的时候才会刷新，其他时候刷新频率降低这种设定

**Comment by cppla** [comment]
得前端来实现吧，不懂前段。。。。 @Chandler-Lu

**Comment by Chandler-Lu** [comment]
有空我研究研究看 = =同不懂前端

**Comment by cppla** [comment]
refer ： https://github.com/cppla/ServerStatus/issues/4 @Chandler-Lu
