### ISSUE TITLE
能否将在线时间精确到秒？

### ISSUE THREAD

**Issue by ghost** [cppla/ServerStatus#7]
超过1天的在线时间，精度只到天，不超过1天的却精确到秒，能否也让超过1天的在线时间精确到秒？最后更新也显示准确时间而不是几秒前

**Comment by cppla** [comment]
你更改一下client 处 获取 脚本就行了。 eg: https://tz.cloudcpp.com/json/stats.json ,  uptime 字段
@ClarkeCheng

**Comment by ghost** [comment]
@cppla 这个显示uptime的好像与 [server/src/main.cpp](https://github.com/cppla/ServerStatus/blob/master/server/src/main.cpp) 239行下面的代码有关，人家直接输出多少天的。可惜我看不懂它的代码。

**Comment by cppla** [comment]
去掉if else 强制精确时间 @ClarkeCheng ：

int Days = pClients[i].m_Stats.m_Uptime/60.0/60.0/24.0;
str_format(aUptime, sizeof(aUptime), "%02d:%02d:%02d", (int)(pClients[i].m_Stats.m_Uptime/60.0/60.0), (int)((pClients[i].m_Stats.m_Uptime/60)%60), (int)((pClients[i].m_Stats.m_Uptime)%60));

**Comment by ghost** [comment]
@cppla 我改成这个样子，能帮我看一下代码有没有错吗？我不会C++
```
str_format(aUptime, sizeof(aUptime), "%d天 %02d:%02d:%02d", Days, (int)((pClients[i].m_Stats.m_Uptime/60/60)%60), (int)((pClients[i].m_Stats.m_Uptime/60)%60), (int)((pClients[i].m_Stats.m_Uptime)%60));
```
目的就是输出W天 X:Y:Z这个格式的运行时间

**Comment by ghost** [comment]
@cppla 谢谢，功能实现了，是否有意将这个功能添加到仓库中？我可以PR。

**Comment by cppla** [comment]
客气，大佬fork一下就行了。 没必要整合。 个人需要而已 。 @ClarkeCheng
