### ISSUE TITLE
纯IPV6客户端 无法连接 IPV4V6双栈服务端

### ISSUE THREAD

**Issue by SoraKasvgano** [cppla/ServerStatus#70]
纯IPV6客户端 无法连接 IPV4V6双栈服务端

当客户端在只有V4环境下运行时，无法连接 aaa.COM域名的服务端，该域名同时有A记录和AAAA记录。

且当把地址直接改成IPV6地址时仍然连接不上

一直显示 连接中，重连

**Comment by SoraKasvgano** [comment]
据推测 config配置文件中port=35601只监听了IPV4端口没有监听IPV6端口，希望修复！！！

**Comment by cppla** [comment]
已经修复，   看最新更新日志。 @samondlee 

注意默认docker是不支持ipv6的, 如使用docker需要手动开启ipv6。 或者直接手工安装。

**Comment by cppla** [comment]
[如图所示，](https://s1.ax1x.com/2020/06/17/NV4tDs.png) ： https://s1.ax1x.com/2020/06/17/NV4tDs.png
server 为 linode ，网络支持 ipv4 & ipv6
client 为 vultr, 2.5刀， 网络仅支持ipv6

**Comment by lvillis** [comment]
> 已经修复， 看最新更新日志。 @samondlee
> 
> 注意默认docker是不支持ipv6的, 如使用docker需要手动开启ipv6。 或者直接手工安装。

大佬，docker容器内运行客户端，读取不到宿主机的信息。
因为手上小鸡比较多，已经写了一键脚本尽可能简化部署过程。但还是docker部署最为方便，我目前实在想不到如何读取宿主机的信息。这个技术上可以实现吗？

**Comment by cppla** [comment]
可以，docker容器只是缺少一些库而已。 挂载 然后 安装缺少库装上就了。 @sudoii
https://blog.csdn.net/wufolangren/article/details/86702274

但是网卡没办法，因为容器的网卡是nat后的。


客户端没必要docker吧，不是一句话吗，再说生产服务器也不重启
```
nohup python client-linux.py SERVER=45.79.67.132 USER=s04 &

**Comment by lvillis** [comment]
> 可以，docker容器只是缺少一些库而已。 挂载 然后 安装缺少库装上就了。 @sudoii
> https://blog.csdn.net/wufolangren/article/details/86702274
> 
> 但是网卡没办法，因为容器的网卡是nat后的。
> 
> 客户端没必要docker吧，不是一句话吗，再说生产服务器也不重启
> 
> ```
> nohup python client-linux.py SERVER=45.79.67.132 USER=s04 &
> ```

好的，谢谢大佬解答。
这样的话，vnstat就没办法了...  我做成docker其实略有强迫症的意思。 xD

**Comment by SoraKasvgano** [comment]
感谢！
