### ISSUE TITLE
Server config中host问题

### ISSUE THREAD

**Issue by aolaiqf** [cppla/ServerStatus#73]
server config.json文件中的host填写的IP与client ip不同 但是还是可以正确识别到服务器信息
请问server config.json文件中的host字段起什么用处？

**Comment by cppla** [comment]
这个字段纯粹是为了更好区分多个服务器，没实际作用，参考：https://tz.cloudcpp.com/json/stats.json

json比较全，比较方便调整前端自定义界面。。所以有了各种各样的前端皮。 @aolaiqf
