### ISSUE TITLE
双栈兼容建议

### ISSUE THREAD

**Issue by ruanhuilingscuec** [cppla/ServerStatus#74]
服务器支持双栈，同时拥有 IPv4、IPv6，IPv4 已经 MH370，但是 ServerStatus 默认会转为 IPv6 连接，状态就变成 MH361 了，明明服务器已经红了（其实现在天朝直接使用 IPv6 的不多），但监控还是绿的，变得不是那么准确了。

建议增加开关是否启用 IPv6，或者检测到有 IPv4 就自动关闭 IPv6 连接，或者 IPv4/IPv6 状态分别出来？

**Comment by cppla** [comment]
-------------
服务器 ipv4 被Q，   服务器 ipv6，没被Q， 现在显示MH361 ???
-------------

1、以前仅支持ipv4，仅作ipv4地址探测，所以显示是被Q的。
2、现在支持了双栈且你的服务器优先了ipv6出口（服务器在拥有双栈的情况下，会默认ipv6出口。这是linux的机制），client-linux客户端默认探测服务器默认出口，所以显示没被Q。

解决方法：
1、你可以主动选择协议啊，比如说禁用ipv6。
2、或者设置ipv4优先。linux中设置优先使用ipv4：https://blog.csdn.net/dhkfo66064/article/details/101746377

**Comment by cppla** [comment]
@ruanhuilingscuec

**Comment by ruanhuilingscuec** [comment]
> ## 服务器 ipv4 被Q， 服务器 ipv6，没被Q， 现在显示MH361 ???
> 1、以前仅支持ipv4，仅作ipv4地址探测，所以显示是被Q的。
> 2、现在支持了双栈且你的服务器优先了ipv6出口（服务器在拥有双栈的情况下，会默认ipv6出口。这是linux的机制），client-linux客户端默认探测服务器默认出口，所以显示没被Q。
> 
> 解决方法：
> 1、你可以主动选择协议啊，比如说禁用ipv6。
> 2、或者设置ipv4优先。linux中设置优先使用ipv4：https://blog.csdn.net/dhkfo66064/article/details/101746377

- 服务器 ipv4 被Q， 服务器 ipv6，没被Q， 现在显示MH361 ???
- 是的，

**Comment by cppla** [comment]
还有一个解决方案是，自定义 ipv4协议的 监控三网地址。   @ruanhuilingscuec 

目前用的域名会走双栈解析
```
cu.tz.cloudcpp.com
cm.tz.cloudcpp.com
ct.tz.cloudcpp.com
