### ISSUE TITLE
ct.tz.cloudcpp.com无法访问了

### ISSUE THREAD

**Issue by nmgliangwei** [cppla/ServerStatus#75]
ct.tz.cloudcpp.com 这个域名已经无法检测了. 443端口无法访问,80端口可以

**Comment by cppla** [comment]
建议换成自己本地宽带运营商的域名，ct.tz.cloudcpp.com（www.chinatelecom.com.cn）是为了通用，其在全球范围内80端口链路连通性都比较接近真实回程。  有更好的欢迎提供 @nmgliangwei
