### ISSUE TITLE
适合单服务器吗？

### ISSUE THREAD

**Issue by WymanY** [cppla/ServerStatus#77]
大佬想问下，我只有一个vps，也想监控下服务器的流量，磁盘使用情况，等基本信息。这个支持服务端和客户端装在同一台server里吗？

**Comment by cppla** [comment]
支持。 @WymanY

**Comment by WymanY** [comment]
感谢回答，那就是服务端脚本和客户端脚本都装在我那唯一的vps里是吧？我试了下不行，可能是我操作有什么问题，我再试试
