### ISSUE TITLE
你好，为什么我的丢包率一直是 0% ？ 还有一直显示MH370 ？

### ISSUE THREAD

**Issue by xingzhuanxing** [cppla/ServerStatus#78]
请问是什么问题？

**Comment by cppla** [comment]
https://github.com/cppla/ServerStatus/issues/60  
https://github.com/cppla/ServerStatus/issues/74

@xingzhuanxing 

你修改三网探测了吧。

**Comment by xingzhuanxing** [comment]
> #60
> #74
> 
> @xingzhuanxing
> 
> 你修改三网探测了吧。

没有改过。 服务端用你的docker， 
该如何修改三网探测？

**Comment by cppla** [comment]
探测改下地址 和 端口号 即可。 mh370证明当前出口协议不通。 估计是开了ipv6，却无法联网。 可以看下二楼发你的refer

```
PORBEPORT = 80
CU = "cu.tz.cloudcpp.com"
CT = "ct.tz.cloudcpp.com"
CM = "cm.tz.cloudcpp.com"
