### ISSUE TITLE
丢包监测在手机上显示不全

### ISSUE THREAD

**Issue by dovela** [cppla/ServerStatus#8]
即使开了访问桌面版也只能显示cu的丢包率。
顺便一提，客户端一键已加入更新功能

**Comment by cppla** [comment]
@dovela 大佬因为你的手机屏幕太小。。。你可以注释掉自适应匹配：https://github.com/cppla/ServerStatus/blob/master/web/css/dark.css ， media only screen and (max-width: 450px)

**Comment by dovela** [comment]
ok,谢谢

**Comment by dovela** [comment]
用平板也不行啊。。。应该是必须改代码了
