### ISSUE TITLE
一个idea

### ISSUE THREAD

**Issue by perfect-network** [cppla/ServerStatus#80]
将前端部署好后，不需要先在前端添加节点，这对批量操作很繁琐

换成，前端生成一个token，也就是api key，然后后端那边指定必要的参数就行

例如：
`python client-linux.py SERVER={$SERVER} KEY={$PASSWORD} NAME=测试机器01 TYPE=测试
`
这样就可以超级轻松的进行添加机器了，甚至都不需要上面指定name和type直接先把脚本运行起来，可以通过IP来判断机器，如果前端中没有这个IP的就新建一个机器，然后用户再为这个机器设定配置，

总之现在的方案不太方便。。。我有空了用PHP写一份前端，带后台功能的！！！！

**Comment by cppla** [comment]
好主意

**Comment by Acheng-dot** [comment]
所以大佬写好了吗 是不是搁浅了哈哈哈

**Comment by ghost** [comment]
好主意

**Comment by perfect-network** [comment]
> 所以大佬写好了吗 是不是搁浅了哈哈哈

有点无聊 现在准备用golang来写，直接编译出可执行文件，也可以弄出systemctl 管理的那种～比较方便，但是我go是才开始学的，不知道会不会做完。。。

**Comment by perfect-network** [comment]
前几天学go 还有TCP相关的东西去了，，，嗯  现在又重新开始尝试写？

**Comment by perfect-network** [comment]
名称 | 版本号 | 验证密钥 | 数据长度 | RSA加密后的密文
-- | -- | -- | -- | --
字节长度 | 1 | 16 | 1 | int（数据长度）
  |   |   |   |  
名称 | 版本号 | 结果 |   |  
  | 1 | 1 |   |
