### ISSUE TITLE
大佬，UDP连接数不显示

### ISSUE THREAD

**Issue by cncherisher** [cppla/ServerStatus#81]
![Snipaste_2020-08-04_20-50-50](https://user-images.githubusercontent.com/46522179/89295937-4affbf80-d694-11ea-82c2-17b2e34b3a01.jpg)
我这台服务器在跑pt，不可能没有UDP连接
![Snipaste_2020-08-04_20-50-59](https://user-images.githubusercontent.com/46522179/89296020-65399d80-d694-11ea-926c-1eee8a12637f.jpg)
演示站也没有UDP连接

**Comment by cppla** [comment]
@cncherisher  
下面命令可以看到是否有udp链接，试试。你确定开启udp了？？？ 
```
netstat -ant | grep tcp
netstat -ant | grep udp

**Comment by cppla** [comment]
一般都是UNCONN
```
ss -u -a

**Comment by cncherisher** [comment]
原来如此，谢谢大佬了！
