### ISSUE TITLE
监测ping延迟节点改成家里的公网ip不行吗？    

### ISSUE THREAD

**Issue by MaleiSiyin** [cppla/ServerStatus#83]
监测ping延迟节点改成家里的公网ip不行吗？       改成家里的公网ipping零延迟？？

**Comment by cppla** [comment]
@MaleiSiyin 需要开放端口，tcp探测，非ICMP。

refer：https://github.com/cppla/ServerStatus/issues/60

**Comment by MaleiSiyin** [comment]
ok 谢谢
