### ISSUE TITLE
美化前端

### ISSUE THREAD

**Issue by Nanhumly** [cppla/ServerStatus#84]
大佬，这里发现了三个美化的前端模板，可否抽空魔改一下。
链接：https://maofun.com/111.html

**Comment by cppla** [comment]
@Nanhumly  简洁即是美，有兴趣可以自己折腾，好不容易优化了cpu占用，用这种美化的web，cpu狂转。

**Comment by he-sb** [comment]
只有我一个人觉得这种所谓的“美化”完全是舍本逐末（而且并不“美”）吗，上面的横行和下面的卡片展示的内容有重复，啰哩啰嗦的。。

**Comment by cppla** [comment]
> 只有我一个人觉得这种所谓的“美化”完全是舍本逐末（而且并不“美”）吗，上面的横行和下面的卡片展示的内容有重复，啰哩啰嗦的。。

我也搞不明白，这个难道不是清晰简明看小鸡指标的吗。。那些国旗把我看晕了。

**Comment by he-sb** [comment]
> > 只有我一个人觉得这种所谓的“美化”完全是舍本逐末（而且并不“美”）吗，上面的横行和下面的卡片展示的内容有重复，啰哩啰嗦的。。
> 
> 我也搞不明白，这个难道不是清晰简明看小鸡指标的吗。。那些国旗把我看晕了。 

国旗啥的都还好，这个属于“美化”的范畴，主要是仔细看的话，上下两部分展示的信息很大部分是重合的，这就有点草，而且目前见到的几个基于这个项目的魔改/美化版本，无一例外都是这种风格，无非是配色和背景换了换，搞不明白有啥意义🙈

**Comment by Nanhumly** [comment]
> @Nanhumly 简洁即是美，有兴趣可以自己折腾，好不容易优化了cpu占用，用这种美化的web，cpu狂转。

好的，感谢大佬回复。
