### ISSUE TITLE
【如何快速跟随系统启动】能否加一个systemted自启之类的？

### ISSUE THREAD

**Issue by nttisbest** [cppla/ServerStatus#87]
用`nohup`的话，如果服务器重启，就又得重新敲一次这个指令；如果我想重启这个服务，先`kill`在`nohup`有点麻烦。
能不能写一个systemted？

**Comment by nttisbest** [comment]
我刚看到原版的仓库是有systemd 这个文件，我去试试

**Comment by he-sb** [comment]
可以用 supervisor 配置进程守护，我的配置可以参考下：
[一个简约有逼格的云探针 - ServerStatus 中文版配置 | HE-SB-技术栈](https://tech.he-sb.top/posts/usage-of-serverstatus/)

**Comment by nttisbest** [comment]
> 可以用 supervisor 配置进程守护，我的配置可以参考下：
> [一个简约有逼格的云探针 - ServerStatus 中文版配置 | HE-SB-技术栈](https://tech.he-sb.top/posts/usage-of-serverstatus/)

好，我去试试。谢谢

**Comment by cppla** [comment]
@nttisbest 重启非常简单啊，

chmod 755 /root/client-linux.py

vim /etc/crontab，尾部加入：
```
@reboot root /root/client-linux.py SERVER=$server USER=$user
```
即可。

**Comment by nttisbest** [comment]
> 可以用 supervisor 配置进程守护，我的配置可以参考下：
> [一个简约有逼格的云探针 - ServerStatus 中文版配置 | HE-SB-技术栈](https://tech.he-sb.top/posts/usage-of-serverstatus/)

遇到了一个问题，在我按照你博客上的教程安装好Supervisor之后，要启动的时候出现这个错误
`/usr/lib/python2.7/site-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist
For help, use /usr/bin/supervisord -h`

**Comment by nttisbest** [comment]
> @nttisbest 重启非常简单啊，
> 
> chmod 755 /root/client-linux.py
> 
> vim /etc/crontab，尾部加入：
> 
> ```
> @reboot root /root/client-linux.py SERVER=$server USER=$user
> ```
> 
> 即可。

非常感谢作者的回复！我想要更简单一些的systemed或者Supervisor或者init.d更方便记忆，不过he-sb这个大神已经给我提供了一个解决方案，我先尝试一下。

**Comment by ligongfu** [comment]
用C8系统行不通

> @nttisbest 重启非常简单啊，
> 
> chmod 755 /root/client-linux.py
> 
> vim /etc/crontab，尾部加入：
> 
> ```
> @reboot root /root/client-linux.py SERVER=$server USER=$user
> ```
> 
> 即可。

用C8系统行不通哦

**Comment by ligongfu** [comment]
> 用C8系统行不通
> 
> > @nttisbest 重启非常简单啊，
> > chmod 755 /root/client-linux.py
> > vim /etc/crontab，尾部加入：
> > ```
> > @reboot root /root/client-linux.py SERVER=$server USER=$user
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 即可。
> 
> 用C8系统行不通哦

刚用另一台C8仍然不行
