### ISSUE TITLE
手动安装无法连接

### ISSUE THREAD

**Issue by Acheng-dot** [cppla/ServerStatus#88]
我在justhost的debain系统上通过lnmp.org的一键安装包搭建了web服务，并按照步骤成功开启了网址探针服务端且连接上了本地客户端，但是在其他服务器客户端成功填写user，password，port并运行后一直无法连接，通过端口查看可以看到服务端35601已被监听，请问接下来我该如何排除错误

**Comment by cppla** [comment]
justhost 开防火墙了吧，可以在客户端telnet一下justhost端口是否通

**Comment by Acheng-dot** [comment]
真的是这样的 没想到能得到大佬的亲自回复 安装web环境前是可以正常连接的就没有去想防火墙的问题 探针真的很棒 是我见过最酷的 又学了个linux命令哈哈哈
