### ISSUE TITLE
ping: invalid option -- 'O' ！in Centos 6.1  python 3.6.1

### ISSUE THREAD

**Issue by forphuw** [cppla/ServerStatus#9]
大佬，client客户端中client-linux.py 和 client-psutil.py都尝试了。
都是出现

ping: invalid option -- 'O'
Usage: ping [-LRUbdfnqrvVaA] [-c count] [-i interval] [-w deadline]
            [-p pattern] [-s packetsize] [-t ttl] [-I interface or address]
            [-M mtu discovery hint] [-S sndbuf]
            [ -T timestamp option ] [ -Q tos ] [hop1 ...] destination
ping: invalid option -- 'O'
Usage: ping [-LRUbdfnqrvVaA] [-c count] [-i interval] [-w deadline]
            [-p pattern] [-s packetsize] [-t ttl] [-I interface or address]
            [-M mtu discovery hint] [-S sndbuf]
            [ -T timestamp option ] [ -Q tos ] [hop1 ...] destination
Connecting...
ping: invalid option -- 'O'
Usage: ping [-LRUbdfnqrvVaA] [-c count] [-i interval] [-w deadline]
            [-p pattern] [-s packetsize] [-t ttl] [-I interface or address]
            [-M mtu discovery hint] [-S sndbuf]
            [ -T timestamp option ] [ -Q tos ] [hop1 ...] destination
Caught Exception: a bytes-like object is required, not 'str'
Connecting...
Caught Exception: a bytes-like object is required, not 'str'

求解~感谢！

**Comment by cppla** [comment]
在执行下就可以了，已经修复 。切换成tcp ping 了
