### ISSUE TITLE
客户端一直在断开和重联的过程中

### ISSUE THREAD

**Issue by conease** [cppla/ServerStatus#90]
某一台服务器的客户端一直在断开和重联的过程中。运行client-linux.py后输出

> Authentication successful. Access granted.
> 
> You are connecting via: IPv4
> 
> Disconnected...
> Connecting...
> Authentication successful. Access granted.
> 
> You are connecting via: IPv4
> 
> Disconnected...
> Connecting...
> Disconnected...
> Connecting...

服务端web显示离线。其他服务器客户端节点无问题。

有没有日志可以查看是哪里的问题？

**Comment by cppla** [comment]
更新最新版的客户端，已经fix   这个bug了。@conease
```
wget https://raw.githubusercontent.com/cppla/ServerStatus/master/clients/client-linux.py
```

**Comment by cppla** [comment]
出现原因，装了一些tcp加速工具，会把一些小包合并到一起发送，已经fixed。 @conease
