### ISSUE TITLE
其他运维监控方案导论

### ISSUE THREAD

**Issue by CHN-STUDENT** [cppla/ServerStatus#91]
rt，
公司生产服务器不敢直接装开源软件配环境，风险非常大，管理很严格，出事非常严重。

所以前几天刚浅薄写一个批处理/脚本发送系统运行信息到制定邮箱，但是缺点不是自动的，检查项目也没现在server status多，目前借助Windows/Linux实现定时检测。

想考虑继续优化我的脚本，或者照着您的项目写一个其他语言版本的，不过我觉得我能力有点欠缺，希望大家提提意见，一起讨论？建立个群？然后一点点写代码实现...

目前我想到有以下几点（方向）

1.脱离运行环境，最好原生bash/batch或者c/c++实现，跨平台

2.监控服务器状态，应用状态，网络状态，并且模拟发包请求测试

3.导出execl报表

现在也打算一点点抽时间来做，所以还希望和大家一起，得到帮助

**Comment by cppla** [comment]
1.  你就说是你自己写的不就行了。
2. go可以一键跨平台， go build for anywhere。  execl报表就需要记录数据到文件了。

**Comment by CHN-STUDENT** [comment]
@cppla 哈哈考虑到您们很忙，所以我还是自己多写一点，不过还是想您们的意见

**Comment by CHN-STUDENT** [comment]
@cppla 抽空把 go 语言版本框架写了出来，现在还有三网延迟，三网丢包，实时网络速度还需要找您一同确认算法。
https://github.com/CHN-STUDENT/ServerStatus/tree/dev/clients/golang/awesomeProject
您有空也看下？帮帮忙？

![image](https://user-images.githubusercontent.com/21209416/101718526-59476780-3adc-11eb-9a06-9dfb48b688e1.png)

**Comment by cppla** [comment]
@CHN-STUDENT 这个有点尴尬，
```
“公司生产服务器不敢直接装开源软件配环境，风险非常大，管理很严格，出事非常严重。”
```
然后你go重写了一遍，又开源了。。。。。。

**Comment by CHN-STUDENT** [comment]
@cppla 啊哈，我们领导又说我是刚毕业的学生，不让我接触生产环境，给了我几个测试服务器，让我先自己学习玩玩，提升水平，不过我写的golang版本有issue会崩溃，现在也不知道怎么解决，所以还是开源希望大佬们帮帮我。
毕竟这可能是我未来的方向了。
您要不介意抽空您看看我的golang版本为什么崩溃？我还是需要帮助的，在我现在的公司由于公司性质没几个人懂开发技术的,,,

**Comment by cppla** [comment]
。。。

**Comment by CHN-STUDENT** [comment]
@cppla 

~~抽空大佬看看我写的网络联通、三网丢包和延迟计算算法吧。有问题，一跑就空指针异常，我也是新入门golang，所以还需要帮助。~~

Update 2020.12.24 现在程序貌似没有问题了，[一些数值因为使用的 golang 的 json-iterator 库转换问题不够精确](https://github.com/json-iterator/go/issues/522) ，正在和作者沟通交流。

我在尝试在windows 下编译 server 端，能编译成功，但是提示(10093 '应用程序没有调用 WSAStartup，或者 WSAStartup 失败） 错误，考虑要不要重写一个 server 端，不过以我的 C/C++ 水平，这个难度可不小....
