### ISSUE TITLE
网站显示以前的消息不更新

### ISSUE THREAD

**Issue by ghost** [cppla/ServerStatus#98]
以前的服务器重置系统后重新安装云探针，先装了前端，服务端都还没开启就显示这个
环境
Nginx 18
Centos7
![image](https://user-images.githubusercontent.com/83596484/116894683-ec886180-ac64-11eb-9d05-d9e80c6ee78e.png)

**Comment by cppla** [comment]
大佬 ，你这里是几手版本了。建议去修改源处提交 @LanceXOT
